// Flashcard lesson content.
// Each lesson is a 12-card mini-lesson. Images live in /public/lessons/<id>/.
// Map: garden slug -> lesson id. Add more gardens/levels here later.
export type FlashCard = {
  type: 'intro' | 'vocab' | 'practice' | 'recap'
  img: string
  fr: string
  en: string
  ex?: string
  ex_en?: string
  title_fr?: string
  title_en?: string
  words?: { fr: string; en: string }[]
}
export type FlashLesson = {
  id: string
  theme_en: string
  theme_fr: string
  imgBase: string
  cards: FlashCard[]
}
const P1_FRUITS: FlashLesson = {
  id: 'p1-fruits',
  theme_en: 'Fruits from the garden',
  theme_fr: 'Les fruits du jardin',
  imgBase: '/lessons/p1-fruits/',
  cards: [
    { type: 'intro', img: 'p1-fruits-01.jpg', title_fr: 'Les fruits du jardin', title_en: 'Fruits from the garden',
      fr: 'Aujourd’hui, nous apprenons les fruits du jardin.', en: 'Today we learn the fruits from the garden.',
      ex: 'Les fruits sont bons pour la santé.', ex_en: 'Fruits are good for our health.' },
    { type: 'vocab', img: 'p1-fruits-02.jpg', fr: 'La pomme', en: 'Apple', ex: 'Je mange une pomme.', ex_en: 'I eat an apple.' },
    { type: 'vocab', img: 'p1-fruits-03.jpg', fr: 'La banane', en: 'Banana', ex: 'La banane est jaune.', ex_en: 'The banana is yellow.' },
    { type: 'vocab', img: 'p1-fruits-04.jpg', fr: 'L’orange', en: 'Orange', ex: 'J’aime l’orange.', ex_en: 'I like oranges.' },
    { type: 'vocab', img: 'p1-fruits-05.jpg', fr: 'La fraise', en: 'Strawberry', ex: 'La fraise est rouge.', ex_en: 'The strawberry is red.' },
    { type: 'vocab', img: 'p1-fruits-06.jpg', fr: 'La pastèque', en: 'Watermelon', ex: 'La pastèque est grande.', ex_en: 'The watermelon is big.' },
    { type: 'vocab', img: 'p1-fruits-07.jpg', fr: 'L’ananas', en: 'Pineapple', ex: 'L’ananas est bon.', ex_en: 'The pineapple is good.' },
    { type: 'vocab', img: 'p1-fruits-08.jpg', fr: 'La mangue', en: 'Mango', ex: 'La mangue est sucrée.', ex_en: 'The mango is sweet.' },
    { type: 'vocab', img: 'p1-fruits-09.jpg', fr: 'La poire', en: 'Pear', ex: 'La poire est verte.', ex_en: 'The pear is green.' },
    { type: 'vocab', img: 'p1-fruits-10.jpg', fr: 'Les raisins', en: 'Grapes', ex: 'Les raisins sont violets.', ex_en: 'The grapes are purple.' },
    { type: 'practice', img: 'p1-fruits-11.jpg', title_fr: 'On utilise nos mots', title_en: 'Let’s use our words',
      fr: 'J’aime la pomme, la banane et l’orange.', en: 'I like apples, bananas and oranges.',
      ex: 'Les fruits sont délicieux.', ex_en: 'The fruits are delicious.' },
    { type: 'recap', img: 'p1-fruits-12.jpg', title_fr: 'Bravo !', title_en: 'Great job!',
      fr: 'Très bien ! À bientôt !', en: 'Well done! See you next lesson!',
      ex: 'Aujourd’hui, tu as appris 9 fruits.', ex_en: 'Today you learned 9 fruits.' },
  ],
}
const P2_GARDEN: FlashLesson = {
  id: 'p2-garden',
  theme_en: 'Vegetables from the garden',
  theme_fr: 'Les légumes du jardin',
  imgBase: '/lessons/p2-garden/',
  cards: [
    { type: 'intro', img: 'p2-garden-01.jpg', title_fr: 'Le jardin', title_en: 'Garden',
      fr: 'Qu’est-ce que c’est ?', en: 'What is this?',
      ex: 'C’est notre jardin.', ex_en: 'It is our garden.' },
    { type: 'vocab', img: 'p2-garden-02.jpg', title_fr: 'La tomate', title_en: 'Tomato',
      fr: 'Qu’est-ce que c’est ?', en: 'What is this?',
      ex: 'C’est une tomate.', ex_en: 'It is a tomato.' },
    { type: 'vocab', img: 'p2-garden-03.jpg', title_fr: 'L’oignon', title_en: 'Onion',
      fr: 'Tu vois les oignons ?', en: 'Do you see the onions?',
      ex: 'Oui, je vois les oignons.', ex_en: 'Yes, I see the onions.' },
    { type: 'vocab', img: 'p2-garden-04.jpg', title_fr: 'La carotte', title_en: 'Carrot',
      fr: 'Qu’est-ce que tu prends ?', en: 'What are you taking?',
      ex: 'Je prends une carotte.', ex_en: 'I am taking a carrot.' },
    { type: 'vocab', img: 'p2-garden-05.jpg', title_fr: 'La laitue', title_en: 'Lettuce',
      fr: 'Tu aimes la laitue ?', en: 'Do you like lettuce?',
      ex: 'Oui, j’aime la laitue.', ex_en: 'Yes, I like lettuce.' },
    { type: 'vocab', img: 'p2-garden-06.jpg', title_fr: 'Le concombre', title_en: 'Cucumber',
      fr: 'Qu’est-ce qui pousse ici ?', en: 'What is growing here?',
      ex: 'Un concombre pousse ici.', ex_en: 'A cucumber is growing here.' },
    { type: 'vocab', img: 'p2-garden-07.jpg', title_fr: 'Le poivron', title_en: 'Pepper',
      fr: 'De quelle couleur est le poivron ?', en: 'What colour is the pepper?',
      ex: 'Il est rouge.', ex_en: 'It is red.' },
    { type: 'vocab', img: 'p2-garden-08.jpg', title_fr: 'La citrouille', title_en: 'Pumpkin',
      fr: 'Regarde la citrouille !', en: 'Look at the pumpkin!',
      ex: 'Elle est très grosse !', ex_en: 'It is very big!' },
    { type: 'vocab', img: 'p2-garden-09.jpg', title_fr: 'Les épinards', title_en: 'Spinach',
      fr: 'Qu’est-ce que tu touches ?', en: 'What are you touching?',
      ex: 'Je touche les épinards.', ex_en: 'I am touching the spinach.' },
    { type: 'vocab', img: 'p2-garden-10.jpg', title_fr: 'Le gombo', title_en: 'Okra',
      fr: 'Tu connais le gombo ?', en: 'Do you know okra?',
      ex: 'Oui, voici le gombo.', ex_en: 'Yes, here is the okra.' },
    { type: 'practice', img: 'p2-garden-11.jpg', title_fr: 'La récolte', title_en: 'Harvest',
      fr: 'Que faisons-nous ?', en: 'What are we doing?',
      ex: 'Nous récoltons les légumes.', ex_en: 'We are harvesting the vegetables.' },
    { type: 'recap', img: 'p2-garden-12.jpg', title_fr: 'Récapitulatif', title_en: 'Review',
      fr: 'Qu’est-ce que tu as appris ?', en: 'What did you learn?',
      ex: 'J’ai appris les légumes du jardin !', ex_en: 'I learned about garden vegetables!' },
  ],
}
const P3_GARDEN: FlashLesson = {
  id: 'p3-garden',
  theme_en: 'Working in the garden',
  theme_fr: 'Travailler au jardin',
  imgBase: '/lessons/p3-garden/',
  cards: [
    { type: 'intro', img: 'p3-garden-01.jpg', title_fr: '🌱 Découvrir le jardin', title_en: '🌱 Découvrir le jardin',
      fr: 'A : Où sommes-nous ? B : Nous sommes dans le jardin de l’école.', en: 'A: Where are we? B: We are in the school garden.',
      ex: 'A : Qu’allons-nous apprendre ? B : Nous allons apprendre à jardiner !', ex_en: 'A: What are we going to learn? B: We are going to learn how to garden!' },
    { type: 'vocab', img: 'p3-garden-02.jpg', title_fr: '🪏 Creuser la terre', title_en: '🪏 Creuser la terre',
      fr: 'A : Que fais-tu ? B : Je creuse la terre.', en: 'A: What are you doing? B: I am digging the soil.',
      ex: 'A : Pourquoi ? B : Pour préparer le jardin.', ex_en: 'A: Why? B: To prepare the garden.' },
    { type: 'vocab', img: 'p3-garden-03.jpg', title_fr: '🌿 Préparer le sol', title_en: '🌿 Préparer le sol',
      fr: 'A : Que fais-tu avec la houe ? B : Je prépare le sol.', en: 'A: What are you doing with the hoe? B: I am preparing the soil.',
      ex: 'A : Le sol est-il prêt ? B : Oui, il est prêt !', ex_en: 'A: Is the soil ready? B: Yes, it is ready!' },
    { type: 'vocab', img: 'p3-garden-04.jpg', title_fr: '💧 Arroser les plantes', title_en: '💧 Arroser les plantes',
      fr: 'A : Que fais-tu ? B : J’arrose les plantes.', en: 'A: What are you doing? B: I am watering the plants.',
      ex: 'A : Pourquoi faut-il de l’eau ? B : Pour aider les plantes à pousser.', ex_en: 'A: Why do they need water? B: To help the plants grow.' },
    { type: 'vocab', img: 'p3-garden-05.jpg', title_fr: '🍂 Ramasser les feuilles', title_en: '🍂 Ramasser les feuilles',
      fr: 'A : Que ramasses-tu ? B : Je ramasse les feuilles sèches.', en: 'A: What are you collecting? B: I am collecting the dry leaves.',
      ex: 'A : Le jardin est propre maintenant ? B : Oui, il est propre !', ex_en: 'A: Is the garden clean now? B: Yes, it is clean!' },
    { type: 'vocab', img: 'p3-garden-06.jpg', title_fr: '🥕 Transporter les légumes', title_en: '🥕 Transporter les légumes',
      fr: 'A : Qu’y a-t-il dans la brouette ? B : Il y a des légumes.', en: 'A: What is in the wheelbarrow? B: There are vegetables.',
      ex: 'A : Où les emportes-tu ? B : Je les emporte à l’école.', ex_en: 'A: Where are you taking them? B: I am taking them to the school.' },
    { type: 'vocab', img: 'p3-garden-07.jpg', title_fr: '🌱 Planter', title_en: '🌱 Planter',
      fr: 'A : Que plantes-tu ? B : Je plante un jeune plant.', en: 'A: What are you planting? B: I am planting a young plant.',
      ex: 'A : Que fais-tu après ? B : Je mets de la terre autour.', ex_en: 'A: What do you do next? B: I put soil around it.' },
    { type: 'vocab', img: 'p3-garden-08.jpg', title_fr: '🥬 Récolter les légumes', title_en: '🥬 Récolter les légumes',
      fr: 'A : Qu’avez-vous récolté ? B : Nous avons récolté des légumes !', en: 'A: What have you harvested? B: We have harvested vegetables!',
      ex: 'A : Sont-ils frais ? B : Oui, ils sont très frais !', ex_en: 'A: Are they fresh? B: Yes, they are very fresh!' },
    { type: 'vocab', img: 'p3-garden-09.jpg', title_fr: '🌰 Semer les graines', title_en: '🌰 Semer les graines',
      fr: 'A : Que mets-tu dans la terre ? B : Je mets des graines.', en: 'A: What are you putting in the soil? B: I am putting seeds in it.',
      ex: 'A : Que vont-elles devenir ? B : Elles vont devenir des plantes.', ex_en: 'A: What will they become? B: They will become plants.' },
    { type: 'vocab', img: 'p3-garden-10.jpg', title_fr: '🌾 Ameublir le sol', title_en: '🌾 Ameublir le sol',
      fr: 'A : Pourquoi travailles-tu la terre ? B : Pour rendre le sol meuble.', en: 'A: Why are you working the soil? B: To make the soil loose.',
      ex: 'A : Est-ce bon pour les plantes ? B : Oui, très bon !', ex_en: 'A: Is that good for plants? B: Yes, very good!' },
    { type: 'practice', img: 'p3-garden-11.jpg', title_fr: '👩🏾‍🌾 Travailler ensemble', title_en: '👩🏾‍🌾 Travailler ensemble',
      fr: 'A : Que faisons-nous aujourd’hui ? B : Nous travaillons dans le jardin.', en: 'A: What are we doing today? B: We are working in the garden.',
      ex: 'A : Qui s’occupe du jardin ? B : Nous tous !', ex_en: 'A: Who takes care of the garden? B: All of us!' },
    { type: 'recap', img: 'p3-garden-12.jpg', title_fr: '🎉 Notre jardin', title_en: '🎉 Notre jardin',
      fr: 'A : Qu’avons-nous appris ? B : À planter, arroser et récolter.', en: 'A: What have we learned? B: To plant, water and harvest.',
      ex: 'A : Aimes-tu notre jardin ? B : Oui, j’adore notre jardin !', ex_en: 'A: Do you like our garden? B: Yes, I love our garden!' },
  ],
}

const P4_GARDEN: FlashLesson = {
  id: 'p4-garden',
  theme_en: 'Parts of the plant',
  theme_fr: 'Les parties de la plante',
  imgBase: '/lessons/p4-garden/',
  cards: [
    { type: 'intro', img: 'p4-garden-01.jpg', title_fr: 'aliment – sain – jardin (food – healthy – garden)', title_en: 'aliment – sain – jardin (food – healthy – garden)',
      fr: 'Les aliments du jardin sont sains.', en: 'Food from the garden is healthy.',
      ex: 'A : Quels aliments vois-tu ? B : Je vois des fruits et des légumes.', ex_en: 'A: What foods do you see? B: I see fruits and vegetables.' },
    { type: 'vocab', img: 'p4-garden-02.jpg', title_fr: 'fruit – arbre – cueillir (fruit – tree – pick)', title_en: 'fruit – arbre – cueillir (fruit – tree – pick)',
      fr: 'Nous cueillons des fruits dans le jardin.', en: 'We pick fruits in the garden.',
      ex: 'A : Que cueillez-vous ? B : Nous cueillons des fruits.', ex_en: 'A: What are you picking? B: We are picking fruits.' },
    { type: 'vocab', img: 'p4-garden-03.jpg', title_fr: 'fleur – tige – pousser (flower – stem – grow)', title_en: 'fleur – tige – pousser (flower – stem – grow)',
      fr: 'Les fleurs poussent sur la tige.', en: 'The flowers grow on the stem.',
      ex: 'A : Où poussent les fleurs ? B : Elles poussent sur la tige.', ex_en: 'A: Where do the flowers grow? B: They grow on the stem.' },
    { type: 'vocab', img: 'p4-garden-04.jpg', title_fr: 'feuille – verte – lumière (leaf – green – light)', title_en: 'feuille – verte – lumière (leaf – green – light)',
      fr: 'Les grandes feuilles vertes reçoivent la lumière.', en: 'The large green leaves receive light.',
      ex: 'A : De quelle couleur sont les feuilles ? B : Les feuilles sont vertes.', ex_en: 'A: What colour are the leaves? B: The leaves are green.' },
    { type: 'vocab', img: 'p4-garden-05.jpg', title_fr: 'papillon – nectar – visiter (butterfly – nectar – visit)', title_en: 'papillon – nectar – visiter (butterfly – nectar – visit)',
      fr: 'Le papillon visite la fleur pour le nectar.', en: 'The butterfly visits the flower for nectar.',
      ex: 'A : Que visite le papillon ? B : Il visite une fleur.', ex_en: 'A: What does the butterfly visit? B: It visits a flower.' },
    { type: 'vocab', img: 'p4-garden-06.jpg', title_fr: 'tomate – mûre – récolter (tomato – ripe – harvest)', title_en: 'tomate – mûre – récolter (tomato – ripe – harvest)',
      fr: 'Nous récoltons les tomates mûres.', en: 'We harvest the ripe tomatoes.',
      ex: 'A : Les tomates sont-elles mûres ? B : Oui, elles sont rouges et mûres.', ex_en: 'A: Are the tomatoes ripe? B: Yes, they are red and ripe.' },
    { type: 'vocab', img: 'p4-garden-07.jpg', title_fr: 'graine – germer – plantule (seed – germinate – seedling)', title_en: 'graine – germer – plantule (seed – germinate – seedling)',
      fr: 'La graine germe et devient une plantule.', en: 'The seed germinates and becomes a seedling.',
      ex: 'A : Que devient la graine ? B : Elle devient une plantule.', ex_en: 'A: What does the seed become? B: It becomes a seedling.' },
    { type: 'vocab', img: 'p4-garden-08.jpg', title_fr: 'arbre – branche – fruit (tree – branch – fruit)', title_en: 'arbre – branche – fruit (tree – branch – fruit)',
      fr: 'Les fruits poussent sur les branches de l’arbre.', en: 'The fruits grow on the branches of the tree.',
      ex: 'A : Que vois-tu sur l’arbre ? B : Je vois des branches, des feuilles et des fruits.', ex_en: 'A: What do you see on the tree? B: I see branches, leaves and fruits.' },
    { type: 'vocab', img: 'p4-garden-09.jpg', title_fr: 'tronc – écorce – rugueux (trunk – bark – rough)', title_en: 'tronc – écorce – rugueux (trunk – bark – rough)',
      fr: 'L’écorce protège le tronc de l’arbre.', en: 'The bark protects the trunk of the tree.',
      ex: 'A : Comment est l’écorce ? B : Elle est dure et rugueuse.', ex_en: 'A: What is the bark like? B: It is hard and rough.' },
    { type: 'vocab', img: 'p4-garden-10.jpg', title_fr: 'sol – racine – absorber (soil – root – absorb)', title_en: 'sol – racine – absorber (soil – root – absorb)',
      fr: 'Les racines absorbent l’eau du sol.', en: 'The roots absorb water from the soil.',
      ex: 'A : Où sont les racines ? B : Les racines sont dans le sol.', ex_en: 'A: Where are the roots? B: The roots are in the soil.' },
    { type: 'practice', img: 'p4-garden-11.jpg', title_fr: 'observer – plante – partie (observe – plant – part)', title_en: 'observer – plante – partie (observe – plant – part)',
      fr: 'Nous observons les différentes parties de la plante.', en: 'We observe the different parts of the plant.',
      ex: 'A : Quelles parties vois-tu ? B : Je vois les racines, la tige, les feuilles et les fruits.', ex_en: 'A: Which parts do you see? B: I see the roots, stem, leaves and fruits.' },
    { type: 'recap', img: 'p4-garden-12.jpg', title_fr: 'racine – tige – feuille – fleur – fruit (root – stem – leaf – flower – fruit)', title_en: 'racine – tige – feuille – fleur – fruit (root – stem – leaf – flower – fruit)',
      fr: 'La plante a des racines, une tige, des feuilles, des fleurs et des fruits.', en: 'The plant has roots, a stem, leaves, flowers and fruits.',
      ex: 'A : Peux-tu nommer les parties de la plante ? B : Oui : les racines, la tige, les feuilles, les fleurs et les fruits.', ex_en: 'A: Can you name the parts of the plant? B: Yes: the roots, stem, leaves, flowers and fruits.' },
  ],
}
const P5_GARDEN: FlashLesson = {
  id: 'p5-garden',
  theme_en: 'Healthy eating & the school garden',
  theme_fr: 'Bien manger et le jardin scolaire',
  imgBase: '/lessons/p5-garden/',
  cards: [
    { type: 'intro', img: 'p5-garden-01.jpg', title_fr: '🥗 Une alimentation saine', title_en: 'Healthy eating',
      fr: 'A : Regarde tous les aliments sur la table. Il y a beaucoup de fruits et de légumes. Ils ont l’air délicieux ! B : Oui, j’aime manger des aliments frais. Ils nous donnent de l’énergie et nous aident à rester en bonne santé. A : Quel aliment préfères-tu ? J’aime beaucoup les fruits. B : Moi, je préfère les légumes. J’aime surtout les carottes et les tomates.', en: 'A: Look at all the food on the table. There are many fruits and vegetables. They look delicious! B: Yes, I like eating fresh food. It gives us energy and helps us stay healthy. A: Which food do you prefer? I really like fruits. B: I prefer vegetables. I especially like carrots and tomatoes.',
      words: [{ fr: 'les aliments', en: 'food' }, { fr: 'les légumes', en: 'vegetables' }, { fr: 'l\'énergie', en: 'energy' }, { fr: 'en bonne santé', en: 'healthy' }] },
    { type: 'vocab', img: 'p5-garden-02.jpg', title_fr: '🍊 La récolte des fruits', title_en: 'Harvesting fruits',
      fr: 'A : Regarde tous les fruits dans le jardin ! Les élèves sont en train de les récolter. Les arbres ont donné beaucoup de fruits. B : Oui, je vois des oranges, des bananes et des papayes. Nous allons remplir nos paniers avec les fruits mûrs. A : Comment sais-tu qu’un fruit est mûr ? B : On peut regarder sa couleur et le toucher doucement. Il faut aussi demander au professeur si on n’est pas sûr.', en: 'A: Look at all the fruits in the garden! The pupils are harvesting them. The trees have produced many fruits. B: Yes, I can see oranges, bananas and papayas. We are going to fill our baskets with ripe fruits. A: How do you know that a fruit is ripe? B: We can look at its colour and touch it gently. We should also ask the teacher if we are not sure.',
      words: [{ fr: 'récolter', en: 'to harvest' }, { fr: 'les fruits', en: 'fruits' }, { fr: 'mûr/mûre', en: 'ripe' }, { fr: 'le panier', en: 'basket' }] },
    { type: 'vocab', img: 'p5-garden-03.jpg', title_fr: '🥕 La récolte des légumes', title_en: 'Harvesting vegetables',
      fr: 'A : Que font les élèves dans le jardin ? Je les vois avec de grands paniers. B : Ils récoltent les légumes qu’ils ont cultivés. Il y a des tomates, des carottes et des légumes verts. A : Pourquoi cultivons-nous des légumes à l’école ? B : Nous apprenons comment les aliments poussent. Nous pouvons aussi manger les légumes frais après la récolte.', en: 'A: What are the pupils doing in the garden? I can see them with big baskets. B: They are harvesting the vegetables they have grown. There are tomatoes, carrots and green vegetables. A: Why do we grow vegetables at school? B: We learn how food grows. We can also eat the fresh vegetables after harvesting them.',
      words: [{ fr: 'les légumes', en: 'vegetables' }, { fr: 'cultiver', en: 'to grow' }, { fr: 'la récolte', en: 'harvest' }, { fr: 'frais/fraîche', en: 'fresh' }] },
    { type: 'vocab', img: 'p5-garden-04.jpg', title_fr: '🌽 La récolte du maïs', title_en: 'Harvesting maize',
      fr: 'A : Qu’est-ce que tu fais avec ce maïs ? Je vois que tu as déjà récolté plusieurs épis. B : Je récolte le maïs avec mes camarades. Ensuite, nous mettons les épis frais dans les paniers. A : Est-ce que le maïs est important dans notre alimentation ? B : Oui, nous pouvons préparer plusieurs repas avec le maïs. C’est aussi une bonne source d’énergie.', en: 'A: What are you doing with this maize? I can see that you have already harvested several ears. B: I am harvesting maize with my classmates. Then, we put the fresh ears into the baskets. A: Is maize important in our diet? B: Yes, we can prepare several meals with maize. It is also a good source of energy.',
      words: [{ fr: 'le maïs', en: 'maize' }, { fr: 'un épi', en: 'an ear of maize' }, { fr: 'récolter', en: 'to harvest' }, { fr: 'le panier', en: 'basket' }] },
    { type: 'vocab', img: 'p5-garden-05.jpg', title_fr: '🌽 Le maïs frais', title_en: 'Fresh maize',
      fr: 'A : Ce maïs vient-il de notre jardin ? Il a l’air très frais. B : Oui, nous venons de le récolter. Nous avons choisi les épis qui étaient prêts. A : Qu’allons-nous faire après la récolte ? B : Nous allons compter les épis et les mettre dans les paniers. Ensuite, nous pourrons les utiliser pour préparer un repas.', en: 'A: Does this maize come from our garden? It looks very fresh. B: Yes, we have just harvested it. We chose the ears that were ready. A: What are we going to do after the harvest? B: We are going to count the ears and put them in the baskets. Then, we can use them to prepare a meal.',
      words: [{ fr: 'le maïs frais', en: 'fresh maize' }, { fr: 'récolter', en: 'to harvest' }, { fr: 'compter', en: 'to count' }, { fr: 'préparer', en: 'to prepare' }] },
    { type: 'vocab', img: 'p5-garden-06.jpg', title_fr: '🫘 La récolte des haricots', title_en: 'Harvesting beans',
      fr: 'A : Que cueilles-tu sur cette plante ? Je vois beaucoup de gousses vertes. B : Je cueille des haricots frais. Je les mets doucement dans mon panier. A : Pourquoi faut-il faire attention pendant la récolte ? B : Il ne faut pas abîmer la plante. Nous devons aussi laisser les haricots qui ne sont pas encore prêts.', en: 'A: What are you picking from this plant? I can see many green pods. B: I am picking fresh beans. I am gently putting them in my basket. A: Why should we be careful during harvesting? B: We should not damage the plant. We should also leave the beans that are not ready yet.',
      words: [{ fr: 'les haricots', en: 'beans' }, { fr: 'cueillir', en: 'to pick' }, { fr: 'la plante', en: 'plant' }, { fr: 'le panier', en: 'basket' }] },
    { type: 'vocab', img: 'p5-garden-07.jpg', title_fr: '🥛 Le lait et le repas sain', title_en: 'Milk and a healthy meal',
      fr: 'A : Qu’est-ce que tu manges aujourd’hui ? Ton repas a l’air très bon. B : Je mange des légumes et je bois du lait. J’essaie de choisir des aliments différents pour mon repas. A : Pourquoi est-il important de bien manger ? B : Une bonne alimentation aide notre corps à grandir. Elle nous donne aussi de l’énergie pour apprendre et jouer.', en: 'A: What are you eating today? Your meal looks very good. B: I am eating vegetables and drinking milk. I try to choose different foods for my meal. A: Why is it important to eat well? B: Good food helps our bodies grow. It also gives us energy to learn and play.',
      words: [{ fr: 'le lait', en: 'milk' }, { fr: 'un repas sain', en: 'a healthy meal' }, { fr: 'grandir', en: 'to grow' }, { fr: 'l\'énergie', en: 'energy' }] },
    { type: 'vocab', img: 'p5-garden-08.jpg', title_fr: '💧 L’eau propre', title_en: 'Clean water',
      fr: 'A : J’ai soif après avoir travaillé dans le jardin. Est-ce que je peux boire cette eau ? B : Oui, c’est de l’eau propre. Nous devons boire suffisamment d’eau, surtout quand il fait chaud. A : Je vois aussi un système pour récupérer l’eau. À quoi sert-il ? B : Il nous aide à récupérer de l’eau pour le jardin. Nous pouvons ainsi mieux gérer l’eau disponible.', en: 'A: I am thirsty after working in the garden. Can I drink this water? B: Yes, it is clean water. We need to drink enough water, especially when it is hot. A: I can also see a system for collecting water. What is it used for? B: It helps us collect water for the garden. This way, we can manage the available water better.',
      words: [{ fr: 'l\'eau propre', en: 'clean water' }, { fr: 'avoir soif', en: 'to be thirsty' }, { fr: 'récupérer l\'eau', en: 'to collect water' }, { fr: 'le jardin', en: 'garden' }] },
    { type: 'vocab', img: 'p5-garden-09.jpg', title_fr: '🧺 Les aliments du jardin', title_en: 'Food from the garden',
      fr: 'A : Quelle belle récolte ! Vos paniers sont remplis de fruits et de légumes. B : Oui, nous avons beaucoup travaillé dans le jardin. Aujourd’hui, nous sommes contents de voir le résultat. A : Quel légume as-tu récolté toi-même ? B : J’ai récolté des tomates et des carottes. J’étais très content de les mettre dans mon panier.', en: 'A: What a beautiful harvest! Your baskets are filled with fruits and vegetables. B: Yes, we have worked hard in the garden. Today, we are happy to see the result. A: Which vegetable did you harvest yourself? B: I harvested tomatoes and carrots. I was very happy to put them in my basket.',
      words: [{ fr: 'la récolte', en: 'harvest' }, { fr: 'les fruits', en: 'fruits' }, { fr: 'les légumes', en: 'vegetables' }, { fr: 'le jardin scolaire', en: 'school garden' }] },
    { type: 'vocab', img: 'p5-garden-10.jpg', title_fr: '⚽ Manger sainement et rester actif', title_en: 'Eating well and staying active',
      fr: 'A : Tu cours très vite aujourd’hui ! Tu as encore beaucoup d’énergie après les cours. B : Oui, j’aime jouer au football avec mes amis. Je mange aussi bien pour avoir de l’énergie. A : Est-ce que l’activité physique est importante ? B : Oui, elle aide notre corps à rester fort. C’est aussi amusant de jouer ensemble.', en: 'A: You are running very fast today! You still have a lot of energy after class. B: Yes, I like playing football with my friends. I also eat well so that I have energy. A: Is physical activity important? B: Yes, it helps our bodies stay strong. It is also fun to play together.',
      words: [{ fr: 'jouer au football', en: 'to play football' }, { fr: 'courir', en: 'to run' }, { fr: 'rester actif', en: 'to stay active' }, { fr: 'l\'énergie', en: 'energy' }] },
    { type: 'practice', img: 'p5-garden-11.jpg', title_fr: '🍲 Préparer un repas sain', title_en: 'Preparing a healthy meal',
      fr: 'A : Qu’est-ce que nous allons préparer avec notre récolte ? Nous avons beaucoup de légumes frais. B : Nous allons préparer un repas sain ensemble. Nous pouvons utiliser les tomates, les carottes et les légumes verts. A : Est-ce que je peux aider à préparer le repas ? B : Bien sûr ! Tu peux commencer par laver les légumes avec de l’eau propre.', en: 'A: What are we going to prepare with our harvest? We have lots of fresh vegetables. B: We are going to prepare a healthy meal together. We can use the tomatoes, carrots and green vegetables. A: Can I help prepare the meal? B: Of course! You can start by washing the vegetables with clean water.',
      words: [{ fr: 'préparer', en: 'to prepare' }, { fr: 'un repas sain', en: 'a healthy meal' }, { fr: 'laver', en: 'to wash' }, { fr: 'les légumes', en: 'vegetables' }] },
    { type: 'recap', img: 'p5-garden-12.jpg', title_fr: '🎉 Célébrons notre récolte', title_en: 'Celebrating our harvest',
      fr: 'A : Tout le monde semble très content aujourd’hui. Qu’est-ce que nous célébrons ? B : Nous célébrons notre belle récolte. Nous avons cultivé et récolté beaucoup d’aliments dans notre jardin. A : Qu’as-tu appris grâce au jardin scolaire ? B : J’ai appris à planter, à prendre soin des plantes et à récolter les aliments. J’ai aussi appris qu’il faut travailler ensemble pour avoir un beau jardin.', en: 'A: Everyone seems very happy today. What are we celebrating? B: We are celebrating our beautiful harvest. We have grown and harvested lots of food from our garden. A: What have you learned from the school garden? B: I have learned to plant, care for plants and harvest food. I have also learned that we need to work together to have a beautiful garden.',
      words: [{ fr: 'célébrer', en: 'to celebrate' }, { fr: 'la récolte', en: 'harvest' }, { fr: 'prendre soin de', en: 'to take care of' }, { fr: 'travailler ensemble', en: 'to work together' }] },
  ],
}
const P6_GARDEN: FlashLesson = {
  id: 'p6-garden',
  theme_en: 'Caring for a sustainable garden',
  theme_fr: 'Prendre soin d’un jardin durable',
  imgBase: '/lessons/p6-garden/',
  cards: [
    { type: 'intro', img: 'p6-garden-01.jpg', title_fr: '🌱 Prendre soin du jardin', title_en: 'Taking Care of the Garden',
      fr: 'A : Que font les élèves dans le jardin ? B : Ils enlèvent les mauvaises herbes et prennent soin des légumes. A : Pourquoi faut-il enlever les mauvaises herbes ? B : Parce qu’elles prennent l’eau et les éléments nutritifs dont les plantes ont besoin.', en: 'A: What are the pupils doing in the garden? B: They are removing weeds and taking care of the vegetables. A: Why should we remove weeds? B: Because they take water and nutrients that the plants need.',
      words: [{ fr: 'entretenir le jardin', en: 'to care for the garden' }, { fr: 'désherber', en: 'to weed' }, { fr: 'les légumes', en: 'vegetables' }, { fr: 'prendre soin de', en: 'to take care of' }] },
    { type: 'vocab', img: 'p6-garden-02.jpg', title_fr: '♻️ Faire du compost', title_en: 'Making Compost',
      fr: 'A : Pourquoi mettez-vous les feuilles dans ce bac ? B : Nous les utilisons pour faire du compost. A : À quoi sert le compost ? B : Il enrichit le sol et aide les plantes à pousser.', en: 'A: Why are you putting the leaves in this bin? B: We use them to make compost. A: What is compost used for? B: It enriches the soil and helps plants grow.',
      words: [{ fr: 'le compost', en: 'compost' }, { fr: 'les déchets organiques', en: 'organic waste' }, { fr: 'les feuilles mortes', en: 'dead leaves' }, { fr: 'enrichir le sol', en: 'to enrich the soil' }] },
    { type: 'vocab', img: 'p6-garden-03.jpg', title_fr: '🍂 Le paillis', title_en: 'Mulch',
      fr: 'A : Pourquoi couvrez-vous le sol avec des feuilles sèches ? B : Nous faisons du paillis pour protéger le sol. A : Est-ce que le paillis aide à conserver l’eau ? B : Oui, il réduit la perte d’eau du sol.', en: 'A: Why are you covering the soil with dry leaves? B: We are making mulch to protect the soil. A: Does mulch help conserve water? B: Yes, it reduces water loss from the soil.',
      words: [{ fr: 'le paillis', en: 'mulch' }, { fr: 'pailler', en: 'to mulch' }, { fr: 'garder l\'humidité', en: 'to retain moisture' }, { fr: 'protéger le sol', en: 'to protect the soil' }] },
    { type: 'vocab', img: 'p6-garden-04.jpg', title_fr: '💧 Bien utiliser l’eau', title_en: 'Using Water Wisely',
      fr: 'A : Pourquoi arrosez-vous près des plantes ? B : Pour donner de l’eau directement aux racines. A : Pourquoi faut-il éviter de gaspiller l’eau ? B : Parce que l’eau est une ressource importante.', en: 'A: Why are you watering near the plants? B: To give water directly to the roots. A: Why should we avoid wasting water? B: Because water is an important resource.',
      words: [{ fr: 'arroser', en: 'to water' }, { fr: 'l\'arrosoir', en: 'watering can' }, { fr: 'l\'irrigation', en: 'irrigation' }, { fr: 'économiser l\'eau', en: 'to save water' }] },
    { type: 'vocab', img: 'p6-garden-05.jpg', title_fr: '🐝 La biodiversité', title_en: 'Biodiversity',
      fr: 'A : Regarde les abeilles et les papillons dans le jardin ! B : Oui, ils visitent les fleurs. A : Pourquoi avons-nous différentes plantes ici ? B : Elles favorisent la biodiversité dans le jardin.', en: 'A: Look at the bees and butterflies in the garden! B: Yes, they are visiting the flowers. A: Why do we have different plants here? B: They support biodiversity in the garden.',
      words: [{ fr: 'les pollinisateurs', en: 'pollinators' }, { fr: 'le papillon', en: 'butterfly' }, { fr: 'les fleurs', en: 'flowers' }, { fr: 'la biodiversité', en: 'biodiversity' }] },
    { type: 'vocab', img: 'p6-garden-06.jpg', title_fr: '🌿 L’écosystème du jardin', title_en: 'The Garden Ecosystem',
      fr: 'A : Pourquoi y a-t-il des plantes, des oiseaux et des insectes dans le jardin ? B : Ils font tous partie de l’écosystème. A : Est-ce qu’ils sont liés ? B : Oui, les êtres vivants dépendent les uns des autres et de leur environnement.', en: 'A: Why are there plants, birds and insects in the garden? B: They are all part of the ecosystem. A: Are they connected? B: Yes, living things depend on one another and on their environment.',
      words: [{ fr: 'observer', en: 'to observe' }, { fr: 'les cultures', en: 'crops' }, { fr: 'les légumes frais', en: 'fresh vegetables' }, { fr: 'la croissance', en: 'growth' }] },
    { type: 'vocab', img: 'p6-garden-07.jpg', title_fr: '♻️ Trier les déchets', title_en: 'Sorting Waste',
      fr: 'A : Pourquoi utilisez-vous différentes poubelles ? B : Nous trions les déchets. A : Que faisons-nous des matériaux recyclables ? B : Nous les séparons pour qu’ils puissent être recyclés.', en: 'A: Why are you using different bins? B: We are sorting the waste. A: What do we do with recyclable materials? B: We separate them so they can be recycled.',
      words: [{ fr: 'trier les déchets', en: 'to sort waste' }, { fr: 'recycler', en: 'to recycle' }, { fr: 'la poubelle de recyclage', en: 'recycling bin' }, { fr: 'protéger l\'environnement', en: 'to protect the environment' }] },
    { type: 'vocab', img: 'p6-garden-08.jpg', title_fr: '🌧️ Récupérer l’eau de pluie', title_en: 'Collecting Rainwater',
      fr: 'A : D’où vient l’eau dans ce réservoir ? B : C’est de l’eau de pluie récupérée du toit. A : Comment pouvons-nous utiliser cette eau ? B : Nous pouvons l’utiliser pour arroser le jardin.', en: 'A: Where does the water in this tank come from? B: It is rainwater collected from the roof. A: How can we use this water? B: We can use it to water the garden.',
      words: [{ fr: 'récupérer l\'eau de pluie', en: 'to collect rainwater' }, { fr: 'le réservoir', en: 'water tank' }, { fr: 'arroser le jardin', en: 'to water the garden' }, { fr: 'économiser l\'eau', en: 'to save water' }] },
    { type: 'vocab', img: 'p6-garden-09.jpg', title_fr: '🧺 La récolte du jardin', title_en: 'The Garden Harvest',
      fr: 'A : Que mettez-vous dans les paniers ? B : Nous récoltons les légumes mûrs du jardin. A : Comment savez-vous qu’ils sont prêts ? B : Nous observons leur taille et leur couleur.', en: 'A: What are you putting in the baskets? B: We are harvesting ripe vegetables from the garden. A: How do you know they are ready? B: We observe their size and colour.',
      words: [{ fr: 'la récolte', en: 'harvest' }, { fr: 'récolter', en: 'to harvest' }, { fr: 'les produits du jardin', en: 'garden produce' }, { fr: 'le panier', en: 'basket' }] },
    { type: 'vocab', img: 'p6-garden-10.jpg', title_fr: '☀️ L’énergie solaire', title_en: 'Solar Energy',
      fr: 'A : À quoi servent les panneaux solaires ? B : Ils utilisent l’énergie du soleil pour produire de l’électricité. A : Peut-on utiliser cette énergie dans le jardin ? B : Oui, elle peut alimenter certains équipements.', en: 'A: What are the solar panels used for? B: They use energy from the sun to produce electricity. A: Can we use this energy in the garden? B: Yes, it can power some equipment.',
      words: [{ fr: 'le jardin durable', en: 'sustainable garden' }, { fr: 'l\'énergie solaire', en: 'solar energy' }, { fr: 'cultiver', en: 'to grow' }, { fr: 'préserver les ressources', en: 'to conserve resources' }] },
    { type: 'practice', img: 'p6-garden-11.jpg', title_fr: '🥬 Récolter sans gaspiller', title_en: 'Harvesting Without Waste',
      fr: 'A : Pourquoi ne récoltez-vous que certains légumes ? B : Parce que nous choisissons seulement ceux qui sont mûrs. A : Pourquoi ne faut-il pas trop récolter ? B : Pour éviter de gaspiller les aliments.', en: 'A: Why are you harvesting only some vegetables? B: Because we choose only those that are ripe. A: Why shouldn\'t we harvest too much? B: To avoid wasting food.',
      words: [{ fr: 'travailler ensemble', en: 'to work together' }, { fr: 'entretenir', en: 'to maintain' }, { fr: 'récolter les légumes', en: 'to harvest vegetables' }, { fr: 'le jardin scolaire', en: 'school garden' }] },
    { type: 'recap', img: 'p6-garden-12.jpg', title_fr: '🎉 Ce que nous avons appris', title_en: 'What We Have Learned',
      fr: 'A : Qu’as-tu appris dans le jardin cette année ? B : J’ai appris à protéger le sol, l’eau et les plantes. A : Et quelle est ta leçon préférée ? B : J’ai appris que la nourriture, l’eau et l’énergie sont liées.', en: 'A: What have you learned in the garden this year? B: I have learned to protect the soil, water and plants. A: And what is your favourite lesson? B: I learned that food, water and energy are connected.',
      words: [{ fr: 'célébrer', en: 'to celebrate' }, { fr: 'la réussite', en: 'success' }, { fr: 'la récolte', en: 'harvest' }, { fr: 'être fier/fière de', en: 'to be proud of' }] },
  ],
}
// Which garden + class shows which flashcard lesson.
// The fruits lesson is Primary 1 content specifically.
// Key format: "<gardenSlug>|<classKey>". Falls back to garden-only if no class.
const LESSON_BY_GARDEN_CLASS: Record<string, FlashLesson> = {
  'primary-nutrition|primary-1': P1_FRUITS,
  'primary-nutrition|primary-2': P2_GARDEN,
  'primary-nutrition|primary-3': P3_GARDEN,
  'primary-nutrition|primary-4': P4_GARDEN,
  'primary-nutrition|primary-5': P5_GARDEN,
  'primary-nutrition|primary-6': P6_GARDEN,
}
// gardens where the free flashcards tool exists at all (any class)
const FREE_FLASH_GARDENS = ['nursery-nutrition', 'primary-nutrition', 'jss-nutrition', 'sss-nutrition']
export function lessonForGarden(slug: string, klass?: string): FlashLesson | null {
  if (klass) {
    const hit = LESSON_BY_GARDEN_CLASS[slug + '|' + klass]
    if (hit) return hit
  }
  return null
}
export function gardenHasFlashcards(slug: string): boolean {
  return FREE_FLASH_GARDENS.includes(slug)
}
