// AUTO-GENERATED Primary 5 FRENCH LANGUAGE quiz — 150 questions, 6 categories.
// From Gabe's primary_5_french_language_quiz_150 doc.

import type { LangCategory } from './lang-p1'

export const P5_LANG: LangCategory[] = [
  {
    slug: "obj-word", name: "Picture → Word", icon: "🖼️", color: "#3E7CA6",
    questions: [
      { diff: "easy", avatar: "✈️", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["avion", "magasin", "horloge", "ordinateur"], correct: 0 },
      { diff: "easy", avatar: "🚆", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["train", "médecin", "magasin", "appareil photo"], correct: 0 },
      { diff: "easy", avatar: "🚢", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["bateau", "médecin", "magasin", "cuisinier"], correct: 0 },
      { diff: "easy", avatar: "🚦", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["feu de circulation", "école", "livre", "chaise"], correct: 0 },
      { diff: "easy", avatar: "🗺️", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["carte", "enseignante", "rivière", "bateau"], correct: 0 },
      { diff: "easy", avatar: "🏦", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["banque", "recyclage", "bateau", "tournesol"], correct: 0 },
      { diff: "easy", avatar: "🏪", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["magasin", "avion", "marché", "tournesol"], correct: 0 },
      { diff: "medium", avatar: "🏛️", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["musée", "feu de circulation", "livre", "tournesol"], correct: 0 },
      { diff: "medium", avatar: "🏟️", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["stade", "banque", "rivière", "horloge"], correct: 0 },
      { diff: "medium", avatar: "⛪", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["église", "tournesol", "lampe de poche", "jardin"], correct: 0 },
      { diff: "medium", avatar: "💻", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["ordinateur", "téléphone", "médecin", "agriculteur"], correct: 0 },
      { diff: "medium", avatar: "📱", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["téléphone", "avion", "magasin", "jardin"], correct: 0 },
      { diff: "medium", avatar: "📷", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["appareil photo", "médecin", "enseignante", "policier"], correct: 0 },
      { diff: "medium", avatar: "🕰️", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["horloge", "appareil photo", "champ", "marché"], correct: 0 },
      { diff: "medium", avatar: "🔦", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["lampe de poche", "téléphone", "ordinateur", "tournesol"], correct: 0 },
      { diff: "medium", avatar: "🌻", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["tournesol", "médecin", "ordinateur", "chemise"], correct: 0 },
      { diff: "medium", avatar: "🌾", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["champ", "horloge", "médecin", "stade"], correct: 0 },
      { diff: "hard", avatar: "♻️", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["recyclage", "jardin", "école", "magasin"], correct: 0 },
      { diff: "hard", avatar: "☀️", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["énergie solaire", "chaise", "banque", "champ"], correct: 0 },
      { diff: "hard", avatar: "💦", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["goutte d’eau", "feu de circulation", "champ", "médecin"], correct: 0 },
      { diff: "hard", avatar: "👨‍⚕️", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["médecin", "enseignante", "recyclage", "stade"], correct: 0 },
      { diff: "hard", avatar: "👩‍🏫", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["enseignante", "banque", "jardin", "chemise"], correct: 0 },
      { diff: "hard", avatar: "👨‍🌾", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["agriculteur", "vélo", "carte", "école"], correct: 0 },
      { diff: "hard", avatar: "👨‍🍳", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["cuisinier", "champ", "agriculteur", "musée"], correct: 0 },
      { diff: "hard", avatar: "👮", q: "Quel est le mot ou groupe de mots français pour cette image ?", options: ["policier", "recyclage", "lampe de poche", "chaise"], correct: 0 },
    ],
  },
  {
    slug: "word-obj", name: "Word → Picture", icon: "🔤", color: "#5C9E3A",
    questions: [
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« avion »** ?", options: ["✈️ Airplane", "☀️ Solar energy", "🔦 Flashlight", "🌾 Field"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« train »** ?", options: ["🚆 Train", "💦 Drop of water", "🏪 Shop", "👩‍🏫 Teacher"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« bateau »** ?", options: ["🚢 Boat", "⛪ Church", "🚆 Train", "🏟️ Stadium"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« feu de circulation »** ?", options: ["🚦 Traffic light", "👩‍🏫 Teacher", "👮 Police officer", "📷 Camera"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« carte »** ?", options: ["🗺️ Map", "🔦 Flashlight", "📱 Phone", "👨‍🍳 Cook"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« banque »** ?", options: ["🏦 Bank", "📷 Camera", "☀️ Solar energy", "👩‍🏫 Teacher"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« magasin »** ?", options: ["🏪 Shop", "✈️ Airplane", "🚆 Train", "📷 Camera"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« musée »** ?", options: ["🏛️ Museum", "👨‍🍳 Cook", "👨‍🌾 Farmer", "🏪 Shop"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« stade »** ?", options: ["🏟️ Stadium", "🌾 Field", "📱 Phone", "♻️ Recycling"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« église »** ?", options: ["⛪ Church", "💻 Computer", "♻️ Recycling", "🕰️ Clock"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« ordinateur »** ?", options: ["💻 Computer", "🏟️ Stadium", "👩‍🏫 Teacher", "🌾 Field"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« téléphone »** ?", options: ["📱 Phone", "🏪 Shop", "👨‍🌾 Farmer", "🏛️ Museum"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« appareil photo »** ?", options: ["📷 Camera", "🏦 Bank", "☀️ Solar energy", "🏪 Shop"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« horloge »** ?", options: ["🕰️ Clock", "👨‍🌾 Farmer", "👨‍🍳 Cook", "📱 Phone"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« lampe de poche »** ?", options: ["🔦 Flashlight", "🌻 Sunflower", "💦 Drop of water", "👩‍🏫 Teacher"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« tournesol »** ?", options: ["🌻 Sunflower", "🌾 Field", "✈️ Airplane", "👨‍🍳 Cook"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« champ »** ?", options: ["🌾 Field", "🚆 Train", "☀️ Solar energy", "🚦 Traffic light"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« recyclage »** ?", options: ["♻️ Recycling", "👨‍⚕️ Doctor", "🌾 Field", "🏟️ Stadium"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« énergie solaire »** ?", options: ["☀️ Solar energy", "🏦 Bank", "🌻 Sunflower", "🏪 Shop"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« goutte d’eau »** ?", options: ["💦 Drop of water", "👩‍🏫 Teacher", "👨‍🌾 Farmer", "🕰️ Clock"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« médecin »** ?", options: ["👨‍⚕️ Doctor", "🚦 Traffic light", "🕰️ Clock", "🏪 Shop"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« enseignante »** ?", options: ["👩‍🏫 Teacher", "⛪ Church", "🏪 Shop", "🌾 Field"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« agriculteur »** ?", options: ["👨‍🌾 Farmer", "✈️ Airplane", "👨‍🍳 Cook", "👨‍⚕️ Doctor"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« cuisinier »** ?", options: ["👨‍🍳 Cook", "🏛️ Museum", "🌻 Sunflower", "☀️ Solar energy"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« policier »** ?", options: ["👮 Police officer", "🌻 Sunflower", "💦 Drop of water", "🏪 Shop"], correct: 0 },
    ],
  },
  {
    slug: "spelling", name: "Spelling", icon: "🔤", color: "#C8912E",
    questions: [
      { diff: "easy", avatar: null, q: "Complète : ord□nateur.", options: ["i", "e", "a", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : téléph□ne.", options: ["o", "a", "e", "i"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : mus□e.", options: ["é", "è", "ê", "e"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : agric□lteur.", options: ["u", "o", "a", "i"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : cuisin□er.", options: ["i", "e", "a", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : pol□cier.", options: ["i", "e", "a", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : recycl□ge.", options: ["a", "e", "i", "o"], correct: 0 },
      { diff: "medium", avatar: null, q: "Complète : éner□ie.", options: ["g", "j", "q", "c"], correct: 0 },
      { diff: "medium", avatar: null, q: "Complète : horl□ge.", options: ["o", "a", "e", "i"], correct: 0 },
      { diff: "medium", avatar: null, q: "Complète : mag□sin.", options: ["a", "e", "i", "o"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["ordinateur", "ordinatteur", "ordinatuer", "ordenateur"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["téléphone", "téléfone", "telephône", "téléphonne"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["médecin", "médécin", "medecin", "médecain"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["agriculteur", "agriculteure", "agricolteur", "agriculteurr"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["enseignante", "ensegnante", "enseignente", "ensaignante"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["circulation", "circulassion", "circulacion", "circulattion"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["environnement", "environement", "environnemant", "environnemment"], correct: 0 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["électricité", "éléctricité", "electricité", "électricitée"], correct: 0 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["température", "temperature", "tempèrature", "températture"], correct: 0 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["protéger", "protèger", "proteger", "protéjér"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : nécess□ire.", options: ["a", "e", "i", "o"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : diff□rent.", options: ["é", "è", "ê", "e"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : préf□ré.", options: ["é", "è", "ê", "e"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : deuxi□me.", options: ["è", "é", "ê", "e"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : premi□re.", options: ["è", "é", "ê", "e"], correct: 0 },
    ],
  },
  {
    slug: "meaning", name: "Meaning", icon: "💬", color: "#E0574C",
    questions: [
      { diff: "easy", avatar: null, q: "Que veut dire « avion » ?", options: ["Airplane", "Train", "Boat", "Bicycle"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « banque » ?", options: ["Bank", "Museum", "School", "Hospital"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « magasin » ?", options: ["Shop", "Stadium", "Bank", "Church"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « musée » ?", options: ["Museum", "Market", "Farm", "Library"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « ordinateur » ?", options: ["Computer", "Phone", "Camera", "Clock"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « agriculteur » ?", options: ["Farmer", "Doctor", "Teacher", "Police officer"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « médecin » ?", options: ["Doctor", "Farmer", "Cook", "Teacher"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « protéger » ?", options: ["To protect", "To waste", "To break", "To forget"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « économiser » ?", options: ["To save/conserve", "To waste", "To sell", "To throw"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « recycler » ?", options: ["To recycle", "To burn", "To buy", "To sleep"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « environnement » ?", options: ["Environment", "Homework", "Transport", "Breakfast"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « énergie » ?", options: ["Energy", "Food", "Road", "Clothing"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « dangereux » ?", options: ["Dangerous", "Safe", "Easy", "Clean"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « sûr » ?", options: ["Safe", "Dangerous", "Dirty", "Expensive"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « cher » ?", options: ["Expensive", "Cheap", "Fast", "Young"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « bon marché » ?", options: ["Inexpensive", "Expensive", "Dangerous", "Heavy"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « souvent » ?", options: ["Often", "Never", "Tomorrow", "Slowly"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « quelquefois » ?", options: ["Sometimes", "Always", "Yesterday", "Quickly"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « parce que » ?", options: ["Because", "But", "Where", "When"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « mais » ?", options: ["But", "Because", "With", "Under"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « devant » ?", options: ["In front of", "Behind", "Inside", "Between"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « derrière » ?", options: ["Behind", "In front of", "Above", "Next to"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « entre » ?", options: ["Between", "Behind", "Under", "Far from"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « près de » ?", options: ["Near", "Far from", "Between", "Behind"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « loin de » ?", options: ["Far from", "Near", "Inside", "Above"], correct: 0 },
    ],
  },
  {
    slug: "matching", name: "Matching", icon: "🔗", color: "#7A7488",
    questions: [
      { diff: "easy", avatar: null, q: "Lequel est un métier ?", options: ["médecin", "ordinateur", "avion", "banque"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un moyen de transport ?", options: ["train", "musée", "médecin", "champ"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un appareil numérique ?", options: ["ordinateur", "tournesol", "stade", "agriculteur"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un lieu public ?", options: ["musée", "téléphone", "champ", "avion"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est lié à l’environnement ?", options: ["recyclage", "horloge", "policier", "magasin"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel produit de l’énergie renouvelable ?", options: ["soleil", "charbon", "plastique", "essence"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel aide à économiser l’eau ?", options: ["fermer le robinet", "laisser couler l’eau", "jeter l’eau", "salir l’eau"], correct: 0 },
      { diff: "medium", avatar: null, q: "Lequel est une préposition de lieu ?", options: ["derrière", "souvent", "médecin", "recycler"], correct: 0 },
      { diff: "medium", avatar: null, q: "Médecin, enseignant et policier sont des…", options: ["métiers", "transports", "appareils", "aliments"], correct: 0 },
      { diff: "medium", avatar: null, q: "Train, avion et bateau sont des…", options: ["transports", "métiers", "vêtements", "animaux"], correct: 0 },
      { diff: "medium", avatar: null, q: "Ordinateur et téléphone sont des…", options: ["appareils", "plantes", "métiers", "lieux"], correct: 0 },
      { diff: "medium", avatar: null, q: "Banque et musée sont des…", options: ["lieux", "actions", "animaux", "couleurs"], correct: 0 },
      { diff: "medium", avatar: null, q: "Recycler et économiser sont des…", options: ["actions", "métiers", "lieux", "objets"], correct: 0 },
      { diff: "medium", avatar: null, q: "Solaire et éolienne sont des énergies…", options: ["renouvelables", "jetables", "sales", "alimentaires"], correct: 0 },
      { diff: "medium", avatar: null, q: "Cher et bon marché parlent du…", options: ["prix", "temps", "corps", "climat"], correct: 0 },
      { diff: "medium", avatar: null, q: "Devant et derrière indiquent la…", options: ["position", "couleur", "profession", "nourriture"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel mot va avec 👨‍🌾 ?", options: ["agriculteur", "médecin", "policier", "cuisinier"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot va avec 💻 ?", options: ["ordinateur", "téléphone", "horloge", "carte"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot va avec ♻️ ?", options: ["recyclage", "électricité", "transport", "cuisine"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot va avec ✈️ ?", options: ["avion", "train", "bateau", "vélo"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour voir des objets historiques, je vais au…", options: ["musée", "stade", "magasin", "champ"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour acheter un produit, je vais au…", options: ["magasin", "stade", "champ", "musée"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour protéger la Terre, je peux…", options: ["recycler", "gaspiller", "polluer", "jeter partout"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour économiser l’électricité, je peux…", options: ["éteindre la lumière", "laisser tout allumé", "ouvrir le robinet", "jeter les déchets"], correct: 0 },
      { diff: "hard", avatar: null, q: "Un agriculteur travaille souvent dans un…", options: ["champ", "musée", "stade", "avion"], correct: 0 },
    ],
  },
  {
    slug: "context", name: "Context", icon: "📖", color: "#3E9B7C",
    questions: [
      { diff: "easy", avatar: null, q: "Je ____ à l’école en bus chaque matin.", options: ["vais", "va", "allez", "vont"], correct: 0 },
      { diff: "easy", avatar: null, q: "Nous ____ nos devoirs après l’école.", options: ["faisons", "fait", "faites", "font"], correct: 0 },
      { diff: "easy", avatar: null, q: "Elle ____ un ordinateur pour apprendre.", options: ["utilise", "utilisent", "utilisons", "utilisez"], correct: 0 },
      { diff: "easy", avatar: null, q: "Ils ____ au football dans le stade.", options: ["jouent", "joue", "jouons", "jouez"], correct: 0 },
      { diff: "easy", avatar: null, q: "Le médecin ____ les personnes malades.", options: ["aide", "aident", "aidons", "aidez"], correct: 0 },
      { diff: "easy", avatar: null, q: "L’agriculteur ____ des légumes.", options: ["cultive", "cultivent", "cultivons", "cultivez"], correct: 0 },
      { diff: "easy", avatar: null, q: "Je ferme le robinet ____ économiser l’eau.", options: ["pour", "mais", "derrière", "entre"], correct: 0 },
      { diff: "medium", avatar: null, q: "Nous recyclons ____ nous voulons protéger la Terre.", options: ["parce que", "devant", "avec", "sous"], correct: 0 },
      { diff: "medium", avatar: null, q: "Le livre est ____ la table.", options: ["sur", "souvent", "mais", "demain"], correct: 0 },
      { diff: "medium", avatar: null, q: "Le sac est ____ la chaise.", options: ["sous", "parce que", "toujours", "vite"], correct: 0 },
      { diff: "medium", avatar: null, q: "La banque est ____ le magasin et le musée.", options: ["entre", "souvent", "hier", "jamais"], correct: 0 },
      { diff: "medium", avatar: null, q: "Le bus est ____ l’école.", options: ["devant", "souvent", "parce que", "toujours"], correct: 0 },
      { diff: "medium", avatar: null, q: "Le jardin est ____ de ma maison; je peux y aller à pied.", options: ["près", "cher", "lent", "sale"], correct: 0 },
      { diff: "medium", avatar: null, q: "L’aéroport est ____ de notre école; le trajet est long.", options: ["loin", "propre", "petit", "heureux"], correct: 0 },
      { diff: "medium", avatar: null, q: "Je préfère le train ____ il est confortable.", options: ["parce que", "derrière", "sous", "jamais"], correct: 0 },
      { diff: "medium", avatar: null, q: "Cette chemise coûte beaucoup d’argent; elle est ____.", options: ["chère", "bon marché", "lente", "propre"], correct: 0 },
      { diff: "medium", avatar: null, q: "Ce cahier coûte peu; il est ____.", options: ["bon marché", "dangereux", "loin", "sale"], correct: 0 },
      { diff: "hard", avatar: null, q: "Le feu rouge signifie qu’il faut ____.", options: ["s’arrêter", "accélérer", "dormir", "manger"], correct: 0 },
      { diff: "hard", avatar: null, q: "Avant de traverser la route, je regarde à gauche et à ____.", options: ["droite", "demain", "souvent", "dessus"], correct: 0 },
      { diff: "hard", avatar: null, q: "L’énergie du soleil est appelée énergie ____.", options: ["solaire", "alimentaire", "routière", "scolaire"], correct: 0 },
      { diff: "hard", avatar: null, q: "Nous devons ____ l’eau parce qu’elle est précieuse.", options: ["économiser", "gaspiller", "salir", "jeter"], correct: 0 },
      { diff: "hard", avatar: null, q: "Les bouteilles en plastique peuvent être ____.", options: ["recyclées", "mangées", "lues", "portées"], correct: 0 },
      { diff: "hard", avatar: null, q: "Si aujourd’hui est mercredi, après-demain est ____.", options: ["vendredi", "jeudi", "samedi", "mardi"], correct: 0 },
      { diff: "hard", avatar: null, q: "Il y a soixante minutes dans une ____.", options: ["heure", "semaine", "année", "journée"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour poser une question poliment, je peux dire « ____ ? »", options: ["S’il vous plaît", "Jamais", "Derrière", "Hier"], correct: 0 },
    ],
  },
]

export function p5LangCategoryBySlug(slug: string): LangCategory | undefined {
  return P5_LANG.find((c) => c.slug === slug)
}
