// AUTO-GENERATED Primary 1 FRENCH LANGUAGE quiz — 150 questions, 6 categories.
// From Gabe's primary_1_french_language_quiz_150 doc. Emoji avatars, no images.

export type LangQuestion = { diff: string; avatar: string | null; q: string; options: string[]; correct: number }
export type LangCategory = { slug: string; name: string; icon: string; color: string; questions: LangQuestion[] }

export const P1_LANG: LangCategory[] = [
  {
    slug: "obj-word", name: "Picture → Word", icon: "🖼️", color: "#3E7CA6",
    questions: [
      { diff: "easy", avatar: "🍎", q: "Quel est le mot français pour cet objet ?", options: ["pomme", "banane", "orange", "carotte"], correct: 0 },
      { diff: "easy", avatar: "🍌", q: "Quel est le mot français pour cet objet ?", options: ["banane", "pomme", "mangue", "tomate"], correct: 0 },
      { diff: "easy", avatar: "🐱", q: "Quel est le mot français pour cet objet ?", options: ["chat", "chien", "poisson", "oiseau"], correct: 0 },
      { diff: "easy", avatar: "🐶", q: "Quel est le mot français pour cet objet ?", options: ["chien", "chat", "lapin", "poule"], correct: 0 },
      { diff: "easy", avatar: "🐟", q: "Quel est le mot français pour cet objet ?", options: ["poisson", "chien", "oiseau", "chat"], correct: 0 },
      { diff: "easy", avatar: "🐦", q: "Quel est le mot français pour cet objet ?", options: ["oiseau", "poisson", "chat", "lapin"], correct: 0 },
      { diff: "easy", avatar: "🌳", q: "Quel est le mot français pour cet objet ?", options: ["arbre", "fleur", "livre", "table"], correct: 0 },
      { diff: "easy", avatar: "🌸", q: "Quel est le mot français pour cet objet ?", options: ["fleur", "arbre", "porte", "chaise"], correct: 0 },
      { diff: "easy", avatar: "☀️", q: "Quel est le mot français pour cet objet ?", options: ["soleil", "lune", "pluie", "eau"], correct: 0 },
      { diff: "easy", avatar: "🌙", q: "Quel est le mot français pour cet objet ?", options: ["lune", "soleil", "étoile", "nuage"], correct: 0 },
      { diff: "medium", avatar: "💧", q: "Quel est le mot français pour cet objet ?", options: ["eau", "lait", "pain", "riz"], correct: 0 },
      { diff: "medium", avatar: "🥛", q: "Quel est le mot français pour cet objet ?", options: ["lait", "eau", "jus", "riz"], correct: 0 },
      { diff: "medium", avatar: "🍞", q: "Quel est le mot français pour cet objet ?", options: ["pain", "riz", "lait", "œuf"], correct: 0 },
      { diff: "medium", avatar: "🥚", q: "Quel est le mot français pour cet objet ?", options: ["œuf", "pain", "riz", "pomme"], correct: 0 },
      { diff: "medium", avatar: "📘", q: "Quel est le mot français pour cet objet ?", options: ["livre", "stylo", "table", "sac"], correct: 0 },
      { diff: "medium", avatar: "✏️", q: "Quel est le mot français pour cet objet ?", options: ["crayon", "livre", "règle", "chaise"], correct: 0 },
      { diff: "medium", avatar: "🖊️", q: "Quel est le mot français pour cet objet ?", options: ["stylo", "crayon", "livre", "sac"], correct: 0 },
      { diff: "medium", avatar: "🎒", q: "Quel est le mot français pour cet objet ?", options: ["sac", "livre", "porte", "table"], correct: 0 },
      { diff: "medium", avatar: "🚪", q: "Quel est le mot français pour cet objet ?", options: ["porte", "table", "chaise", "fenêtre"], correct: 0 },
      { diff: "hard", avatar: "🪑", q: "Quel est le mot français pour cet objet ?", options: ["chaise", "table", "porte", "lit"], correct: 0 },
      { diff: "hard", avatar: "🚗", q: "Quel est le mot français pour cet objet ?", options: ["voiture", "vélo", "bus", "maison"], correct: 0 },
      { diff: "hard", avatar: "🚲", q: "Quel est le mot français pour cet objet ?", options: ["vélo", "voiture", "bus", "bateau"], correct: 0 },
      { diff: "hard", avatar: "🏠", q: "Quel est le mot français pour cet objet ?", options: ["maison", "école", "jardin", "voiture"], correct: 0 },
      { diff: "hard", avatar: "👦", q: "Quel est le mot français pour cet objet ?", options: ["garçon", "fille", "maman", "papa"], correct: 0 },
      { diff: "hard", avatar: "👧", q: "Quel est le mot français pour cet objet ?", options: ["fille", "garçon", "maman", "bébé"], correct: 0 },
    ],
  },
  {
    slug: "word-obj", name: "Word → Picture", icon: "🔤", color: "#5C9E3A",
    questions: [
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« pomme »** ?", options: ["🍎 Apple", "🍌 Banana", "🥕 Carrot", "🍅 Tomato"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« chat »** ?", options: ["🐱 Cat", "🐶 Dog", "🐟 Fish", "🐦 Bird"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« chien »** ?", options: ["🐶 Dog", "🐱 Cat", "🐰 Rabbit", "🐔 Chicken"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« poisson »** ?", options: ["🐟 Fish", "🐦 Bird", "🐶 Dog", "🐱 Cat"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« oiseau »** ?", options: ["🐦 Bird", "🐟 Fish", "🐱 Cat", "🐶 Dog"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« arbre »** ?", options: ["🌳 Tree", "🌸 Flower", "☀️ Sun", "🏠 House"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« fleur »** ?", options: ["🌸 Flower", "🌳 Tree", "🍎 Apple", "💧 Water"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« soleil »** ?", options: ["☀️ Sun", "🌙 Moon", "⭐ Star", "☁️ Cloud"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« lune »** ?", options: ["🌙 Moon", "☀️ Sun", "⭐ Star", "🌧️ Rain"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« eau »** ?", options: ["💧 Water", "🥛 Milk", "🍞 Bread", "🍚 Rice"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« lait »** ?", options: ["🥛 Milk", "💧 Water", "🍎 Apple", "🥚 Egg"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« pain »** ?", options: ["🍞 Bread", "🥚 Egg", "🍌 Banana", "🥛 Milk"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« œuf »** ?", options: ["🥚 Egg", "🍞 Bread", "🍎 Apple", "🥕 Carrot"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« livre »** ?", options: ["📘 Book", "✏️ Pencil", "🎒 Bag", "🪑 Chair"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« crayon »** ?", options: ["✏️ Pencil", "📘 Book", "📏 Ruler", "🎒 Bag"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« sac »** ?", options: ["🎒 Bag", "📘 Book", "🚪 Door", "🪑 Chair"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« porte »** ?", options: ["🚪 Door", "🪑 Chair", "🏠 House", "📘 Book"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« chaise »** ?", options: ["🪑 Chair", "🚪 Door", "🎒 Bag", "🚗 Car"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« voiture »** ?", options: ["🚗 Car", "🚲 Bicycle", "🏠 House", "🚌 Bus"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« vélo »** ?", options: ["🚲 Bicycle", "🚗 Car", "🚌 Bus", "🚪 Door"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« maison »** ?", options: ["🏠 House", "🏫 School", "🚗 Car", "🌳 Tree"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« garçon »** ?", options: ["👦 Boy", "👧 Girl", "👩 Mother", "👶 Baby"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« fille »** ?", options: ["👧 Girl", "👦 Boy", "👨 Father", "👶 Baby"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« maman »** ?", options: ["👩 Mother", "👨 Father", "👦 Boy", "👧 Girl"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« papa »** ?", options: ["👨 Father", "👩 Mother", "👶 Baby", "👧 Girl"], correct: 0 },
    ],
  },
  {
    slug: "spelling", name: "Spelling", icon: "✏️", color: "#C8912E",
    questions: [
      { diff: "easy", avatar: null, q: "Complète : p□mme.", options: ["o", "a", "i", "u"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : ch□t.", options: ["a", "o", "i", "e"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : chi□n.", options: ["e", "a", "o", "u"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : l□it.", options: ["a", "e", "i", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : p□in.", options: ["a", "o", "u", "e"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : l□vre.", options: ["i", "a", "o", "u"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : s□c.", options: ["a", "e", "i", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : p□rte.", options: ["o", "a", "i", "u"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : tabl□.", options: ["e", "a", "i", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : f□lle.", options: ["i", "a", "o", "u"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["banane", "benane", "banene", "bonane"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["pomme", "pame", "pumme", "pimme"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["chat", "chet", "chot", "chut"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["chien", "chian", "cheon", "chiin"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["livre", "levre", "lavre", "lovre"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["école", "écolee", "écolle", "écale"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["maison", "meson", "maisson", "mason"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["soleil", "solail", "soleille", "soliel"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["fleur", "flour", "fler", "fleure"], correct: 0 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["rouge", "ruoge", "rouje", "roge"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : v□iture.", options: ["o", "a", "e", "u"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : jard□n.", options: ["i", "a", "o", "e"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : éc□le.", options: ["o", "a", "i", "u"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : s□leil.", options: ["o", "a", "i", "e"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : fl□ur.", options: ["e", "a", "i", "o"], correct: 0 },
    ],
  },
  {
    slug: "meaning", name: "Meaning", icon: "💡", color: "#B0568C",
    questions: [
      { diff: "easy", avatar: null, q: "Que veut dire « pomme » ?", options: ["Apple", "Banana", "Orange", "Carrot"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « chat » ?", options: ["Cat", "Dog", "Fish", "Bird"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « chien » ?", options: ["Dog", "Cat", "Rabbit", "Bird"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « eau » ?", options: ["Water", "Milk", "Bread", "Rice"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « lait » ?", options: ["Milk", "Water", "Juice", "Egg"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « pain » ?", options: ["Bread", "Rice", "Milk", "Apple"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « livre » ?", options: ["Book", "Pen", "Bag", "Chair"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « école » ?", options: ["School", "House", "Market", "Garden"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « maison » ?", options: ["House", "School", "Car", "Tree"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « arbre » ?", options: ["Tree", "Flower", "Water", "Sun"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « fleur » ?", options: ["Flower", "Tree", "Fruit", "Book"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « soleil » ?", options: ["Sun", "Moon", "Star", "Rain"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « lune » ?", options: ["Moon", "Sun", "Cloud", "Water"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « rouge » ?", options: ["Red", "Blue", "Green", "Yellow"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « bleu » ?", options: ["Blue", "Red", "Black", "White"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « vert » ?", options: ["Green", "Yellow", "Red", "Blue"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « jaune » ?", options: ["Yellow", "Green", "Blue", "Black"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « garçon » ?", options: ["Boy", "Girl", "Mother", "Baby"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « fille » ?", options: ["Girl", "Boy", "Father", "Baby"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « maman » ?", options: ["Mother", "Father", "Sister", "Boy"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « papa » ?", options: ["Father", "Mother", "Girl", "Baby"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « voiture » ?", options: ["Car", "Bicycle", "House", "Bus"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « vélo » ?", options: ["Bicycle", "Car", "Bus", "Boat"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « jardin » ?", options: ["Garden", "School", "House", "Road"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « merci » ?", options: ["Thank you", "Hello", "Goodbye", "Please"], correct: 0 },
    ],
  },
  {
    slug: "matching", name: "Matching", icon: "🔗", color: "#3E9B7C",
    questions: [
      { diff: "easy", avatar: null, q: "Lequel est un fruit ?", options: ["pomme", "chaise", "livre", "porte"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un animal ?", options: ["chien", "table", "école", "crayon"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est une boisson ?", options: ["eau", "livre", "chaise", "porte"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est à l'école ?", options: ["livre", "poisson", "banane", "chien"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un membre de la famille ?", options: ["maman", "pomme", "table", "soleil"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est une couleur ?", options: ["rouge", "chien", "eau", "livre"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est dans le ciel ?", options: ["soleil", "chaise", "pain", "sac"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est une plante ?", options: ["arbre", "voiture", "livre", "chien"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un aliment ?", options: ["pain", "porte", "stylo", "vélo"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un moyen de transport ?", options: ["voiture", "fleur", "pomme", "livre"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel mot va avec 🍌 ?", options: ["banane", "pomme", "carotte", "pain"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel mot va avec 🐱 ?", options: ["chat", "chien", "oiseau", "poisson"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel mot va avec 🌸 ?", options: ["fleur", "arbre", "soleil", "eau"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel mot va avec 📘 ?", options: ["livre", "sac", "crayon", "chaise"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel mot va avec 🚲 ?", options: ["vélo", "voiture", "maison", "porte"], correct: 0 },
      { diff: "medium", avatar: null, q: "Pomme et banane sont des…", options: ["fruits", "animaux", "couleurs", "meubles"], correct: 0 },
      { diff: "medium", avatar: null, q: "Chat et chien sont des…", options: ["animaux", "fruits", "boissons", "livres"], correct: 0 },
      { diff: "medium", avatar: null, q: "Rouge et bleu sont des…", options: ["couleurs", "animaux", "écoles", "aliments"], correct: 0 },
      { diff: "medium", avatar: null, q: "Maman et papa sont la…", options: ["famille", "classe", "maison", "couleur"], correct: 0 },
      { diff: "hard", avatar: null, q: "Livre et crayon sont des objets de…", options: ["école", "jardin", "cuisine", "route"], correct: 0 },
      { diff: "hard", avatar: null, q: "Arbre et fleur sont dans le…", options: ["jardin", "bus", "livre", "lait"], correct: 0 },
      { diff: "hard", avatar: null, q: "Eau et lait sont des…", options: ["boissons", "animaux", "couleurs", "meubles"], correct: 0 },
      { diff: "hard", avatar: null, q: "Voiture et vélo servent à se…", options: ["déplacer", "manger", "boire", "lire"], correct: 0 },
      { diff: "hard", avatar: null, q: "Le soleil donne de la…", options: ["lumière", "chaise", "pomme", "porte"], correct: 0 },
      { diff: "hard", avatar: null, q: "Nous buvons de l’…", options: ["eau", "arbre", "livre", "soleil"], correct: 0 },
    ],
  },
  {
    slug: "context", name: "French in Use", icon: "💬", color: "#7A7488",
    questions: [
      { diff: "easy", avatar: null, q: "Je bois de l’____.", options: ["eau", "livre", "chaise", "école"], correct: 0 },
      { diff: "easy", avatar: null, q: "Je mange une ____.", options: ["pomme", "porte", "table", "voiture"], correct: 0 },
      { diff: "easy", avatar: null, q: "Le chat est un ____.", options: ["animal", "fruit", "livre", "couleur"], correct: 0 },
      { diff: "easy", avatar: null, q: "Le soleil est dans le ____.", options: ["ciel", "sac", "livre", "lait"], correct: 0 },
      { diff: "easy", avatar: null, q: "Je lis un ____.", options: ["livre", "chien", "eau", "vélo"], correct: 0 },
      { diff: "easy", avatar: null, q: "J’écris avec un ____.", options: ["crayon", "arbre", "poisson", "pain"], correct: 0 },
      { diff: "easy", avatar: null, q: "Je vais à l’____ pour apprendre.", options: ["école", "pomme", "lune", "chaise"], correct: 0 },
      { diff: "easy", avatar: null, q: "Maman et papa sont ma ____.", options: ["famille", "couleur", "boisson", "classe"], correct: 0 },
      { diff: "easy", avatar: null, q: "Une banane est un ____.", options: ["fruit", "animal", "meuble", "véhicule"], correct: 0 },
      { diff: "easy", avatar: null, q: "Un chien est un ____.", options: ["animal", "fruit", "aliment", "livre"], correct: 0 },
      { diff: "medium", avatar: null, q: "Le lait est une ____.", options: ["boisson", "couleur", "école", "plante"], correct: 0 },
      { diff: "medium", avatar: null, q: "La fleur pousse dans le ____.", options: ["jardin", "livre", "bus", "sac"], correct: 0 },
      { diff: "medium", avatar: null, q: "La voiture roule sur la ____.", options: ["route", "lune", "table", "fleur"], correct: 0 },
      { diff: "medium", avatar: null, q: "Je m’assois sur une ____.", options: ["chaise", "pomme", "eau", "porte"], correct: 0 },
      { diff: "medium", avatar: null, q: "J’ouvre la ____.", options: ["porte", "banane", "lune", "poisson"], correct: 0 },
      { diff: "medium", avatar: null, q: "Le ciel peut être ____.", options: ["bleu", "manger", "livre", "chien"], correct: 0 },
      { diff: "medium", avatar: null, q: "Une feuille est souvent ____.", options: ["verte", "boire", "école", "poisson"], correct: 0 },
      { diff: "medium", avatar: null, q: "Le soleil est souvent ____.", options: ["jaune", "chat", "eau", "sac"], correct: 0 },
      { diff: "medium", avatar: null, q: "Je dis « ____ » pour remercier.", options: ["merci", "chat", "rouge", "pain"], correct: 0 },
      { diff: "hard", avatar: null, q: "Je dis « ____ » pour saluer.", options: ["bonjour", "banane", "chaise", "vert"], correct: 0 },
      { diff: "hard", avatar: null, q: "Deux vient après ____.", options: ["un", "trois", "quatre", "cinq"], correct: 0 },
      { diff: "hard", avatar: null, q: "Trois vient avant ____.", options: ["quatre", "deux", "un", "zéro"], correct: 0 },
      { diff: "hard", avatar: null, q: "J’ai deux ____.", options: ["yeux", "livres", "soleils", "maisons"], correct: 0 },
      { diff: "hard", avatar: null, q: "J’écoute avec mes ____.", options: ["oreilles", "pommes", "portes", "fleurs"], correct: 0 },
      { diff: "hard", avatar: null, q: "Je marche avec mes ____.", options: ["pieds", "livres", "chats", "arbres"], correct: 0 },
    ],
  },
]

export function langCategoryBySlug(slug: string): LangCategory | undefined { return P1_LANG.find(c => c.slug === slug) }