// AUTO-GENERATED JSS 1 FRENCH LANGUAGE quiz — 150 questions, 6 categories.

import type { LangCategory } from './lang-p1'

export const JSS1_LANG: LangCategory[] = [
  {
    slug: "obj-word", name: "Picture → Word", icon: "🖼️", color: "#3E7CA6",
    questions: [
      { diff: "easy", avatar: "🧑‍🎓", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["professeure", "recyclage", "basket-ball", "élève"], correct: 3 },
      { diff: "easy", avatar: "👩‍🏫", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["gare", "professeure", "hôpital", "recyclage"], correct: 1 },
      { diff: "easy", avatar: "🏫", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["collège", "ordinateur", "gare", "dictionnaire"], correct: 0 },
      { diff: "easy", avatar: "📓", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["lecture", "gare", "professeure", "cahier"], correct: 3 },
      { diff: "easy", avatar: "📖", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["dictionnaire", "vélo", "peinture", "imprimante"], correct: 0 },
      { diff: "easy", avatar: "🧪", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["banque", "collège", "laboratoire", "peinture"], correct: 2 },
      { diff: "medium", avatar: "💻", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["maison", "professeure", "gare", "ordinateur"], correct: 3 },
      { diff: "medium", avatar: "⌨️", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["rivière", "basket-ball", "clavier", "hôpital"], correct: 2 },
      { diff: "medium", avatar: "🖥️", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["ordinateur", "marché", "écran", "professeure"], correct: 2 },
      { diff: "medium", avatar: "🖨️", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["environnement", "imprimante", "peinture", "hôpital"], correct: 1 },
      { diff: "medium", avatar: "🏥", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["football", "professeure", "hôpital", "recyclage"], correct: 2 },
      { diff: "medium", avatar: "🏦", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["peinture", "route", "jardin", "banque"], correct: 3 },
      { diff: "medium", avatar: "🏪", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["supermarché", "dictionnaire", "ordinateur", "professeure"], correct: 0 },
      { diff: "medium", avatar: "🚉", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["environnement", "énergie solaire", "ordinateur", "gare"], correct: 3 },
      { diff: "medium", avatar: "🛣️", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["chaise", "écran", "chemise", "route"], correct: 3 },
      { diff: "medium", avatar: "🌍", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["monde", "énergie solaire", "montagne", "peinture"], correct: 0 },
      { diff: "hard", avatar: "🌳", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["football", "gare", "environnement", "ordinateur"], correct: 2 },
      { diff: "hard", avatar: "♻️", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["marché", "gare", "recyclage", "hôpital"], correct: 2 },
      { diff: "hard", avatar: "💧", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["chemise", "eau potable", "environnement", "basket-ball"], correct: 1 },
      { diff: "hard", avatar: "☀️", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["ordinateur", "professeure", "environnement", "énergie solaire"], correct: 3 },
      { diff: "hard", avatar: "⚽", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["football", "route", "collège", "supermarché"], correct: 0 },
      { diff: "hard", avatar: "🏀", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["football", "chemise", "basket-ball", "énergie solaire"], correct: 2 },
      { diff: "hard", avatar: "🎵", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["monde", "musique", "recyclage", "imprimante"], correct: 1 },
      { diff: "hard", avatar: "🎨", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["cahier", "vélo", "peinture", "montagne"], correct: 2 },
      { diff: "hard", avatar: "📚", q: "Quel mot ou groupe de mots français correspond à cette image ?", options: ["lecture", "laboratoire", "écran", "monde"], correct: 0 },
    ],
  },
  {
    slug: "word-obj", name: "Word → Picture", icon: "🔤", color: "#5C9E3A",
    questions: [
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« élève »** ?", options: ["🌍 World", "⌨️ Keyboard", "🏀 Basketball", "🧑‍🎓 Student"], correct: 3 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« professeure »** ?", options: ["🖨️ Printer", "👩‍🏫 Teacher", "🌍 World", "🛣️ Road"], correct: 1 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« collège »** ?", options: ["🚉 Train station", "🏥 Hospital", "🏫 Secondary school", "🖨️ Printer"], correct: 2 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« cahier »** ?", options: ["💧 Drinking water", "📚 Reading", "🏦 Bank", "📓 Notebook"], correct: 3 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« dictionnaire »** ?", options: ["💧 Drinking water", "⚽ Football", "📖 Dictionary", "🌳 Environment"], correct: 2 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« laboratoire »** ?", options: ["🧪 Laboratory", "🌳 Environment", "🛣️ Road", "🧑‍🎓 Student"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« ordinateur »** ?", options: ["🏥 Hospital", "💻 Computer", "⌨️ Keyboard", "🌍 World"], correct: 1 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« clavier »** ?", options: ["🏀 Basketball", "☀️ Solar energy", "♻️ Recycling", "⌨️ Keyboard"], correct: 3 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« écran »** ?", options: ["🏥 Hospital", "🎵 Music", "🖥️ Screen", "🧑‍🎓 Student"], correct: 2 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« imprimante »** ?", options: ["🖨️ Printer", "👩‍🏫 Teacher", "🏫 Secondary school", "🛣️ Road"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« hôpital »** ?", options: ["🏥 Hospital", "⚽ Football", "🏦 Bank", "⌨️ Keyboard"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« banque »** ?", options: ["🎨 Painting", "📖 Dictionary", "🌍 World", "🏦 Bank"], correct: 3 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« supermarché »** ?", options: ["💧 Drinking water", "🏪 Supermarket", "☀️ Solar energy", "🎵 Music"], correct: 1 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« gare »** ?", options: ["☀️ Solar energy", "🚉 Train station", "🌳 Environment", "🏦 Bank"], correct: 1 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« route »** ?", options: ["👩‍🏫 Teacher", "🏪 Supermarket", "🛣️ Road", "🖨️ Printer"], correct: 2 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« monde »** ?", options: ["☀️ Solar energy", "🌍 World", "📓 Notebook", "💧 Drinking water"], correct: 1 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« environnement »** ?", options: ["🏀 Basketball", "🖨️ Printer", "📚 Reading", "🌳 Environment"], correct: 3 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« recyclage »** ?", options: ["🖨️ Printer", "📚 Reading", "💧 Drinking water", "♻️ Recycling"], correct: 3 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« eau potable »** ?", options: ["📚 Reading", "🌳 Environment", "🖨️ Printer", "💧 Drinking water"], correct: 3 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« énergie solaire »** ?", options: ["🏀 Basketball", "🖥️ Screen", "☀️ Solar energy", "🧑‍🎓 Student"], correct: 2 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« football »** ?", options: ["🏥 Hospital", "⚽ Football", "🏪 Supermarket", "🚉 Train station"], correct: 1 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« basket-ball »** ?", options: ["🏦 Bank", "🖥️ Screen", "🏀 Basketball", "🎵 Music"], correct: 2 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« musique »** ?", options: ["📓 Notebook", "🛣️ Road", "🎵 Music", "💧 Drinking water"], correct: 2 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« peinture »** ?", options: ["🎨 Painting", "🌍 World", "🏫 Secondary school", "☀️ Solar energy"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« lecture »** ?", options: ["🎨 Painting", "🖥️ Screen", "🌍 World", "📚 Reading"], correct: 3 },
    ],
  },
  {
    slug: "grammar", name: "Grammar & Spelling", icon: "✍️", color: "#C8912E",
    questions: [
      { diff: "easy", avatar: null, q: "Choisis le bon article : ____ collège.", options: ["les", "la", "le", "une"], correct: 2 },
      { diff: "easy", avatar: null, q: "Choisis le bon article : ____ école.", options: ["un", "l’", "le", "la"], correct: 1 },
      { diff: "easy", avatar: null, q: "Choisis le bon article : ____ élèves.", options: ["un", "les", "la", "le"], correct: 1 },
      { diff: "easy", avatar: null, q: "Complète : Je ____ français.", options: ["parlez", "parlons", "parle", "parles"], correct: 2 },
      { diff: "easy", avatar: null, q: "Complète : Tu ____ un cahier.", options: ["avez", "avons", "a", "as"], correct: 3 },
      { diff: "easy", avatar: null, q: "Complète : Nous ____ à l’école.", options: ["vais", "allons", "va", "allez"], correct: 1 },
      { diff: "medium", avatar: null, q: "Complète : Ils ____ des livres.", options: ["lisent", "lit", "lisons", "lisez"], correct: 0 },
      { diff: "medium", avatar: null, q: "Complète : Elle ____ quinze ans.", options: ["avons", "a", "ont", "as"], correct: 1 },
      { diff: "medium", avatar: null, q: "Choisis le pluriel de « livre ».", options: ["livrees", "livrés", "livre", "livres"], correct: 3 },
      { diff: "medium", avatar: null, q: "Choisis le féminin de « petit ».", options: ["petit", "petite", "petites", "petitte"], correct: 1 },
      { diff: "medium", avatar: null, q: "Choisis le féminin de « heureux ».", options: ["heureuse", "heureux", "heureuxe", "heureuses"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le pluriel de « animal ».", options: ["animaux", "animals", "animau", "animales"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["dictionnaire", "dictiionnaire", "dictionaire", "dictionnare"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["professeur", "profeseur", "proffesseur", "professeure"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["environement", "environnemant", "environnemment", "environnement"], correct: 3 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["bibliotèque", "bibliotheque", "bibliothéque", "bibliothèque"], correct: 3 },
      { diff: "hard", avatar: null, q: "Complète : Je n’____ pas de stylo.", options: ["as", "avons", "a", "ai"], correct: 3 },
      { diff: "hard", avatar: null, q: "Complète : Nous ne ____ pas en retard.", options: ["suis", "sont", "sommes", "êtes"], correct: 2 },
      { diff: "hard", avatar: null, q: "Complète : Est-ce que tu ____ le français ?", options: ["comprenez", "comprend", "comprends", "comprenons"], correct: 2 },
      { diff: "hard", avatar: null, q: "Complète : Mes amis ____ au football.", options: ["jouent", "jouons", "joue", "jouez"], correct: 0 },
      { diff: "hard", avatar: null, q: "Choisis la bonne forme : Marie est ____.", options: ["intelligentes", "intelligents", "intelligent", "intelligente"], correct: 3 },
      { diff: "hard", avatar: null, q: "Choisis la bonne forme : Paul et Jean sont ____.", options: ["grands", "grand", "grande", "grandes"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : J’____ étudier le français.", options: ["aimes", "aimons", "aime", "aimez"], correct: 2 },
      { diff: "hard", avatar: null, q: "Complète : Vous ____ un ordinateur.", options: ["avez", "as", "avons", "ont"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : Elles ____ à la bibliothèque.", options: ["allons", "va", "vont", "allez"], correct: 2 },
    ],
  },
  {
    slug: "meaning", name: "Meaning & Function", icon: "💬", color: "#B0568C",
    questions: [
      { diff: "easy", avatar: null, q: "Que veut dire « collège » ?", options: ["Secondary school", "Market", "Hospital", "Farm"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « cahier » ?", options: ["Chair", "Computer", "Notebook", "Dictionary"], correct: 2 },
      { diff: "easy", avatar: null, q: "Que veut dire « clavier » ?", options: ["Keyboard", "Printer", "Phone", "Screen"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « supermarché » ?", options: ["Bank", "Station", "Supermarket", "Hospital"], correct: 2 },
      { diff: "easy", avatar: null, q: "Que veut dire « eau potable » ?", options: ["Dirty water", "Sea water", "Rain only", "Drinking water"], correct: 3 },
      { diff: "easy", avatar: null, q: "Que veut dire « lecture » ?", options: ["Running", "Painting", "Reading", "Writing"], correct: 2 },
      { diff: "medium", avatar: null, q: "Que veut dire « devoirs » ?", options: ["Clothes", "Breakfast", "Homework", "Holidays"], correct: 2 },
      { diff: "medium", avatar: null, q: "Que veut dire « emploi du temps » ?", options: ["Timetable", "Classroom", "Dictionary", "Uniform"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « matière scolaire » ?", options: ["Teacher", "School subject", "Break time", "School bag"], correct: 1 },
      { diff: "medium", avatar: null, q: "Que veut dire « récréation » ?", options: ["Homework", "Lesson", "Break/recess", "Examination"], correct: 2 },
      { diff: "medium", avatar: null, q: "Que veut dire « commencer » ?", options: ["To begin", "To forget", "To finish", "To close"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « terminer » ?", options: ["To buy", "To begin", "To enter", "To finish"], correct: 3 },
      { diff: "medium", avatar: null, q: "Que veut dire « comprendre » ?", options: ["To close", "To sell", "To forget", "To understand"], correct: 3 },
      { diff: "medium", avatar: null, q: "Que veut dire « répondre » ?", options: ["To answer", "To ask", "To sleep", "To leave"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « demander » ?", options: ["To finish", "To answer", "To drink", "To ask"], correct: 3 },
      { diff: "medium", avatar: null, q: "Que veut dire « tôt » ?", options: ["Often", "Late", "Early", "Never"], correct: 2 },
      { diff: "hard", avatar: null, q: "Que veut dire « tard » ?", options: ["Early", "Always", "Near", "Late"], correct: 3 },
      { diff: "hard", avatar: null, q: "Que veut dire « quelque chose » ?", options: ["Someone", "Something", "Nothing", "Everywhere"], correct: 1 },
      { diff: "hard", avatar: null, q: "Que veut dire « quelqu’un » ?", options: ["Nobody", "Someone", "Something", "Never"], correct: 1 },
      { diff: "hard", avatar: null, q: "Que veut dire « pourquoi » ?", options: ["When", "Why", "Who", "Where"], correct: 1 },
      { diff: "hard", avatar: null, q: "Que veut dire « comment » ?", options: ["Which", "When", "Why", "How"], correct: 3 },
      { diff: "hard", avatar: null, q: "Que veut dire « combien » ?", options: ["Where", "How", "Who", "How much/how many"], correct: 3 },
      { diff: "hard", avatar: null, q: "Que veut dire « puisque » ?", options: ["Under", "Tomorrow", "Since/because", "However"], correct: 2 },
      { diff: "hard", avatar: null, q: "Que veut dire « aussi » ?", options: ["Behind", "Also", "Yesterday", "Never"], correct: 1 },
      { diff: "hard", avatar: null, q: "Que veut dire « surtout » ?", options: ["Yesterday", "Especially", "Under", "Slowly"], correct: 1 },
    ],
  },
  {
    slug: "match", name: "Matching & School Life", icon: "🏫", color: "#3E9B7C",
    questions: [
      { diff: "easy", avatar: null, q: "Lequel est une matière scolaire ?", options: ["gare", "banque", "chemise", "mathématiques"], correct: 3 },
      { diff: "easy", avatar: null, q: "Lequel est un appareil informatique ?", options: ["route", "football", "clavier", "cahier"], correct: 2 },
      { diff: "easy", avatar: null, q: "Lequel est un lieu où l’on peut emprunter des livres ?", options: ["banque", "stade", "bibliothèque", "gare"], correct: 2 },
      { diff: "easy", avatar: null, q: "Lequel est une activité de loisir ?", options: ["hôpital", "route", "musique", "clavier"], correct: 2 },
      { diff: "easy", avatar: null, q: "Lequel est une action écologique ?", options: ["gaspiller", "jeter partout", "polluer", "recycler"], correct: 3 },
      { diff: "easy", avatar: null, q: "Lequel est une énergie renouvelable ?", options: ["essence", "charbon", "diesel", "énergie solaire"], correct: 3 },
      { diff: "medium", avatar: null, q: "Lequel est un mot interrogatif ?", options: ["pourquoi", "surtout", "aussi", "tard"], correct: 0 },
      { diff: "medium", avatar: null, q: "Lequel exprime une fréquence ?", options: ["clavier", "élève", "souvent", "gare"], correct: 2 },
      { diff: "medium", avatar: null, q: "Français, anglais et mathématiques sont des…", options: ["matières", "métiers", "transports", "aliments"], correct: 0 },
      { diff: "medium", avatar: null, q: "Clavier, écran et imprimante sont liés à l’…", options: ["informatique", "agriculture", "musique", "sport"], correct: 0 },
      { diff: "medium", avatar: null, q: "Football et basket-ball sont des…", options: ["lieux", "sports", "matières", "professions"], correct: 1 },
      { diff: "medium", avatar: null, q: "Lecture, musique et peinture peuvent être des…", options: ["loisirs", "énergies", "transports", "professions"], correct: 0 },
      { diff: "medium", avatar: null, q: "Bibliothèque et laboratoire sont des lieux d’…", options: ["transport", "habitation", "commerce", "apprentissage"], correct: 3 },
      { diff: "medium", avatar: null, q: "Recycler et économiser l’eau protègent l’…", options: ["ordinateur", "emploi du temps", "environnement", "football"], correct: 2 },
      { diff: "medium", avatar: null, q: "Quel mot va avec 🖥️ ?", options: ["imprimante", "clavier", "cahier", "écran"], correct: 3 },
      { diff: "medium", avatar: null, q: "Quel mot va avec 🧪 ?", options: ["gare", "banque", "bibliothèque", "laboratoire"], correct: 3 },
      { diff: "hard", avatar: null, q: "Quel mot va avec 🏀 ?", options: ["lecture", "football", "peinture", "basket-ball"], correct: 3 },
      { diff: "hard", avatar: null, q: "Quel mot va avec 📓 ?", options: ["ordinateur", "dictionnaire", "cahier", "écran"], correct: 2 },
      { diff: "hard", avatar: null, q: "Pour chercher le sens d’un mot, j’utilise un…", options: ["ballon", "clavier", "ticket", "dictionnaire"], correct: 3 },
      { diff: "hard", avatar: null, q: "Pour imprimer un document, j’utilise une…", options: ["banque", "gare", "imprimante", "route"], correct: 2 },
      { diff: "hard", avatar: null, q: "Pour voyager en train, je vais à la…", options: ["banque", "bibliothèque", "classe", "gare"], correct: 3 },
      { diff: "hard", avatar: null, q: "Pour acheter beaucoup de produits alimentaires, je peux aller au…", options: ["laboratoire", "collège", "stade", "supermarché"], correct: 3 },
      { diff: "hard", avatar: null, q: "Pour éviter le gaspillage d’eau, je dois…", options: ["laisser couler l’eau", "polluer l’eau", "fermer le robinet", "jeter les déchets"], correct: 2 },
      { diff: "hard", avatar: null, q: "Un bon élève doit généralement…", options: ["refuser de lire", "faire ses devoirs", "arriver toujours en retard", "ignorer les cours"], correct: 1 },
      { diff: "hard", avatar: null, q: "Dans une conversation polie, après « merci », on peut répondre…", options: ["pourquoi", "de rien", "jamais", "derrière"], correct: 1 },
    ],
  },
  {
    slug: "context", name: "Context & Comprehension", icon: "📖", color: "#E0574C",
    questions: [
      { diff: "easy", avatar: null, q: "Je ____ au collège tous les jours.", options: ["vais", "va", "allez", "allons"], correct: 0 },
      { diff: "easy", avatar: null, q: "Nous ____ le français le lundi.", options: ["étudions", "étudient", "étudie", "étudiez"], correct: 0 },
      { diff: "easy", avatar: null, q: "Mon professeur ____ la leçon.", options: ["expliquons", "expliquez", "expliquent", "explique"], correct: 3 },
      { diff: "easy", avatar: null, q: "Les élèves ____ leurs devoirs.", options: ["fait", "faites", "faisons", "font"], correct: 3 },
      { diff: "easy", avatar: null, q: "Tu ____ la réponse à cette question.", options: ["connaissons", "connaît", "connaissez", "connais"], correct: 3 },
      { diff: "easy", avatar: null, q: "Vous ____ attentivement le professeur.", options: ["écoutez", "écoutent", "écoute", "écoutons"], correct: 0 },
      { diff: "medium", avatar: null, q: "Je n’____ pas mon dictionnaire aujourd’hui.", options: ["avons", "a", "as", "ai"], correct: 3 },
      { diff: "medium", avatar: null, q: "Nous ne ____ pas de déchets dans la rue.", options: ["jetez", "jette", "jetons", "jettent"], correct: 2 },
      { diff: "medium", avatar: null, q: "Pourquoi apprends-tu le français ? — ____ j’aime les langues.", options: ["Parce que", "Jamais", "Derrière", "Sous"], correct: 0 },
      { diff: "medium", avatar: null, q: "____ commence le cours ? — À huit heures.", options: ["Combien", "Pourquoi", "Quand", "Qui"], correct: 2 },
      { diff: "medium", avatar: null, q: "____ est ton professeur de français ? — Madame Diallo.", options: ["Quand", "Où", "Combien", "Qui"], correct: 3 },
      { diff: "medium", avatar: null, q: "____ coûte ce dictionnaire ? — Dix euros.", options: ["Comment", "Qui", "Pourquoi", "Combien"], correct: 3 },
      { diff: "medium", avatar: null, q: "____ vas-tu après les cours ? — À la maison.", options: ["Où", "Qui", "Combien", "Pourquoi"], correct: 0 },
      { diff: "medium", avatar: null, q: "____ vas-tu à l’école ? — En bus.", options: ["Quand", "Pourquoi", "Comment", "Qui"], correct: 2 },
      { diff: "medium", avatar: null, q: "Mon frère est ____ que moi; il a seize ans et j’en ai treize.", options: ["plus jeune", "plus âgé", "moins âgé", "aussi petit"], correct: 1 },
      { diff: "medium", avatar: null, q: "Cette salle est ____ que l’autre; elle contient plus d’élèves.", options: ["aussi petite", "moins grande", "plus petite", "plus grande"], correct: 3 },
      { diff: "hard", avatar: null, q: "J’aime le français, ____ je trouve certains exercices difficiles.", options: ["hier", "mais", "sous", "devant"], correct: 1 },
      { diff: "hard", avatar: null, q: "Je fais mes devoirs ____ de regarder la télévision.", options: ["avant", "jamais", "loin", "derrière"], correct: 0 },
      { diff: "hard", avatar: null, q: "____ avoir fini mes devoirs, je joue au football.", options: ["Après", "Sans", "Sous", "Entre"], correct: 0 },
      { diff: "hard", avatar: null, q: "Nous recyclons le papier ____ protéger les arbres.", options: ["jamais", "derrière", "mais", "pour"], correct: 3 },
      { diff: "hard", avatar: null, q: "Si tu ne comprends pas, tu peux ____ une question.", options: ["dormir", "vendre", "poser", "fermer"], correct: 2 },
      { diff: "hard", avatar: null, q: "Un élève responsable arrive à l’école à l’____.", options: ["heure", "écran", "eau", "énergie"], correct: 0 },
      { diff: "hard", avatar: null, q: "Il y a ____ mois dans une année.", options: ["sept", "douze", "dix", "vingt"], correct: 1 },
      { diff: "hard", avatar: null, q: "Si le cours commence à 8 h et finit à 9 h, il dure ____ heure.", options: ["deux", "quatre", "trois", "une"], correct: 3 },
      { diff: "hard", avatar: null, q: "Pour mieux parler français, il faut ____ régulièrement.", options: ["éviter", "pratiquer", "arrêter", "oublier"], correct: 1 },
    ],
  },
]

export function jss1LangCategoryBySlug(slug: string): LangCategory | undefined {
  return JSS1_LANG.find((c) => c.slug === slug)
}
