// AUTO-GENERATED Primary 6 FRENCH LANGUAGE quiz — 150 questions, 6 categories.

import type { LangCategory } from './lang-p1'

export const P6_LANG: LangCategory[] = [
  {
    slug: "obj-word", name: "Picture → Word", icon: "🖼️", color: "#3E7CA6",
    questions: [
      { diff: "easy", avatar: "🌍", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["planète", "énergie solaire", "calendrier", "marché"], correct: 0 },
      { diff: "easy", avatar: "🌱", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["semis", "informaticien", "forêt", "artiste"], correct: 0 },
      { diff: "easy", avatar: "🌳", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["environnement", "médecin", "agriculture", "chaise"], correct: 0 },
      { diff: "easy", avatar: "💧", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["eau potable", "bureau de poste", "livre", "poubelle"], correct: 0 },
      { diff: "easy", avatar: "♻️", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["recyclage", "énergie solaire", "microscope", "établissement scolaire"], correct: 0 },
      { diff: "easy", avatar: "☀️", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["énergie solaire", "ordinateur", "livre", "semis"], correct: 0 },
      { diff: "medium", avatar: "💨", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["énergie éolienne", "robinet", "bibliothèque", "poubelle"], correct: 0 },
      { diff: "medium", avatar: "🌾", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["agriculture", "microscope", "semis", "planète"], correct: 0 },
      { diff: "medium", avatar: "🚰", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["robinet", "aéroport", "livre", "thermomètre"], correct: 0 },
      { diff: "medium", avatar: "🗑️", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["poubelle", "vélo", "calendrier", "gare"], correct: 0 },
      { diff: "medium", avatar: "🏥", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["hôpital", "artiste", "recyclage", "gare"], correct: 0 },
      { diff: "medium", avatar: "🏫", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["établissement scolaire", "thermomètre", "électricité", "rivière"], correct: 0 },
      { diff: "medium", avatar: "🏤", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["bureau de poste", "recyclage", "calendrier", "énergie solaire"], correct: 0 },
      { diff: "medium", avatar: "🚉", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["gare", "rivière", "pompier", "semis"], correct: 0 },
      { diff: "medium", avatar: "🛫", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["aéroport", "agriculture", "électricité", "vélo"], correct: 0 },
      { diff: "medium", avatar: "🧑‍🔬", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["scientifique", "ordinateur", "eau potable", "rivière"], correct: 0 },
      { diff: "hard", avatar: "🧑‍💻", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["informaticien", "énergie éolienne", "marché", "thermomètre"], correct: 0 },
      { diff: "hard", avatar: "🧑‍⚕️", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["médecin", "vélo", "microscope", "gare"], correct: 0 },
      { diff: "hard", avatar: "🧑‍🚒", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["pompier", "établissement scolaire", "planète", "thermomètre"], correct: 0 },
      { diff: "hard", avatar: "🧑‍🎨", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["artiste", "calendrier", "planète", "pompier"], correct: 0 },
      { diff: "hard", avatar: "📅", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["calendrier", "vélo", "thermomètre", "livre"], correct: 0 },
      { diff: "hard", avatar: "🌡️", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["thermomètre", "batterie", "environnement", "établissement scolaire"], correct: 0 },
      { diff: "hard", avatar: "🔋", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["batterie", "pompier", "thermomètre", "énergie éolienne"], correct: 0 },
      { diff: "hard", avatar: "🔌", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["électricité", "thermomètre", "eau potable", "microscope"], correct: 0 },
      { diff: "hard", avatar: "🔬", q: "Quel est le mot ou groupe de mots français qui correspond à cette image ?", options: ["microscope", "agriculture", "semis", "rivière"], correct: 0 },
    ],
  },
  {
    slug: "word-obj", name: "Word → Picture", icon: "🔤", color: "#5C9E3A",
    questions: [
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« planète »** ?", options: ["🌍 Planet", "🌱 Seedling", "💨 Wind energy", "☀️ Solar energy"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« semis »** ?", options: ["🌱 Seedling", "🧑‍🚒 Firefighter", "🔋 Battery", "🔌 Electricity"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« environnement »** ?", options: ["🌳 Environment", "💨 Wind energy", "🔬 Microscope", "♻️ Recycling"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« eau potable »** ?", options: ["💧 Drinking water", "🧑‍🚒 Firefighter", "🛫 Airport", "♻️ Recycling"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« recyclage »** ?", options: ["♻️ Recycling", "🧑‍🚒 Firefighter", "💧 Drinking water", "🏥 Hospital"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« énergie solaire »** ?", options: ["☀️ Solar energy", "🔌 Electricity", "🚉 Train station", "🧑‍🎨 Artist"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« énergie éolienne »** ?", options: ["💨 Wind energy", "📅 Calendar", "🚰 Tap", "🌳 Environment"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« agriculture »** ?", options: ["🌾 Agriculture", "🔬 Microscope", "🌱 Seedling", "🧑‍💻 Computer specialist"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« robinet »** ?", options: ["🚰 Tap", "🔋 Battery", "🌳 Environment", "☀️ Solar energy"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« poubelle »** ?", options: ["🗑️ Bin", "🧑‍🚒 Firefighter", "🧑‍💻 Computer specialist", "🏤 Post office"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« hôpital »** ?", options: ["🏥 Hospital", "💨 Wind energy", "📅 Calendar", "💧 Drinking water"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« établissement scolaire »** ?", options: ["🏫 School", "🚰 Tap", "🛫 Airport", "🔌 Electricity"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« bureau de poste »** ?", options: ["🏤 Post office", "💨 Wind energy", "🚰 Tap", "🛫 Airport"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« gare »** ?", options: ["🚉 Train station", "🌳 Environment", "🏫 School", "☀️ Solar energy"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« aéroport »** ?", options: ["🛫 Airport", "🏤 Post office", "☀️ Solar energy", "🔋 Battery"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« scientifique »** ?", options: ["🧑‍🔬 Scientist", "💨 Wind energy", "🔬 Microscope", "♻️ Recycling"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« informaticien »** ?", options: ["🧑‍💻 Computer specialist", "🧑‍🎨 Artist", "🌾 Agriculture", "🌳 Environment"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« médecin »** ?", options: ["🧑‍⚕️ Doctor", "🌍 Planet", "💧 Drinking water", "🧑‍🎨 Artist"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« pompier »** ?", options: ["🧑‍🚒 Firefighter", "🏤 Post office", "💧 Drinking water", "🧑‍⚕️ Doctor"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« artiste »** ?", options: ["🧑‍🎨 Artist", "📅 Calendar", "☀️ Solar energy", "🧑‍🚒 Firefighter"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« calendrier »** ?", options: ["📅 Calendar", "🚰 Tap", "🔬 Microscope", "🧑‍💻 Computer specialist"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« thermomètre »** ?", options: ["🌡️ Thermometer", "🧑‍⚕️ Doctor", "🏤 Post office", "🚉 Train station"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« batterie »** ?", options: ["🔋 Battery", "🌾 Agriculture", "🔌 Electricity", "💧 Drinking water"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« électricité »** ?", options: ["🔌 Electricity", "🏥 Hospital", "🗑️ Bin", "🔋 Battery"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot ou groupe de mots **« microscope »** ?", options: ["🔬 Microscope", "🗑️ Bin", "🚰 Tap", "🌍 Planet"], correct: 0 },
    ],
  },
  {
    slug: "spelling", name: "Spelling", icon: "🔤", color: "#C8912E",
    questions: [
      { diff: "easy", avatar: null, q: "Complète : environnem□nt.", options: ["e", "a", "i", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : électric□té.", options: ["i", "e", "a", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : scientif□que.", options: ["i", "e", "a", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : informatic□en.", options: ["i", "e", "a", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : thermom□tre.", options: ["è", "é", "ê", "e"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : a□roport.", options: ["é", "è", "ê", "e"], correct: 0 },
      { diff: "medium", avatar: null, q: "Complète : agric□lture.", options: ["u", "o", "a", "i"], correct: 0 },
      { diff: "medium", avatar: null, q: "Complète : recycl□ge.", options: ["a", "e", "i", "o"], correct: 0 },
      { diff: "medium", avatar: null, q: "Complète : calendr□er.", options: ["i", "e", "a", "o"], correct: 0 },
      { diff: "medium", avatar: null, q: "Complète : micr□scope.", options: ["o", "a", "e", "i"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["développement", "developpement", "dévelopement", "dévelloppement"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["renouvelable", "renouvellable", "renouvelabble", "renouvalable"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["pollution", "polution", "pollussion", "polluttion"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["température", "tempèrature", "temperature", "températture"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["communauté", "comunauté", "communautée", "communaute"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["responsable", "responsabble", "résponsable", "responsabel"], correct: 0 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["protection", "protéction", "protecttion", "protecsion"], correct: 0 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["éducation", "education", "éducassion", "éducattion"], correct: 0 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["technologie", "tecnologie", "technolojie", "technologiee"], correct: 0 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["bibliothèque", "bibliotèque", "bibliothéque", "bibliotheque"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : nécess□ire.", options: ["a", "e", "i", "o"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : am□liorer.", options: ["é", "è", "ê", "e"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : r□duire.", options: ["é", "è", "ê", "e"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : prot□ger.", options: ["é", "è", "ê", "e"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : pr□server.", options: ["é", "è", "ê", "e"], correct: 0 },
    ],
  },
  {
    slug: "meaning", name: "Meaning", icon: "💬", color: "#E0574C",
    questions: [
      { diff: "easy", avatar: null, q: "Que veut dire « environnement » ?", options: ["Environment", "Transport", "Homework", "Clothing"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « eau potable » ?", options: ["Drinking water", "Rainwater only", "Dirty water", "Sea water"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « énergie éolienne » ?", options: ["Wind energy", "Solar energy", "Food energy", "Fuel"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « poubelle » ?", options: ["Bin", "Tap", "Battery", "Calendar"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « gare » ?", options: ["Train station", "Airport", "Hospital", "Market"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « pompier » ?", options: ["Firefighter", "Doctor", "Scientist", "Artist"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « scientifique » ?", options: ["Scientist", "Farmer", "Cook", "Driver"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « améliorer » ?", options: ["To improve", "To destroy", "To forget", "To waste"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « réduire » ?", options: ["To reduce", "To increase", "To sell", "To arrive"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « préserver » ?", options: ["To preserve", "To damage", "To waste", "To remove"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « pollution » ?", options: ["Pollution", "Education", "Agriculture", "Transport"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « communauté » ?", options: ["Community", "Battery", "Weather", "Journey"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « responsable » ?", options: ["Responsible", "Careless", "Expensive", "Distant"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « nécessaire » ?", options: ["Necessary", "Impossible", "Dirty", "Cheap"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « avant » ?", options: ["Before", "After", "During", "Without"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « après » ?", options: ["After", "Before", "Under", "Never"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « pendant » ?", options: ["During", "Before", "Behind", "Far"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « donc » ?", options: ["Therefore/so", "But", "Where", "Under"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « cependant » ?", options: ["However", "Because", "Always", "Inside"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « ensuite » ?", options: ["Then/next", "Yesterday", "Never", "Below"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « meilleur » ?", options: ["Better/best", "Worse", "Smaller", "Slower"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « pire » ?", options: ["Worse/worst", "Better", "Cleaner", "Younger"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « devoir » comme verbe ?", options: ["Must / to have to", "To want", "To know", "To see"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « pouvoir » ?", options: ["Can / to be able to", "Must", "To eat", "To leave"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « vouloir » ?", options: ["To want", "To be able to", "To have to", "To know"], correct: 0 },
    ],
  },
  {
    slug: "matching", name: "Matching", icon: "🔗", color: "#7A7488",
    questions: [
      { diff: "easy", avatar: null, q: "Lequel est une source d’énergie renouvelable ?", options: ["énergie solaire", "charbon", "essence", "diesel"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un métier scientifique ?", options: ["scientifique", "poubelle", "gare", "batterie"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel mesure la température ?", options: ["thermomètre", "calendrier", "microscope", "robinet"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel sert à observer de très petits objets ?", options: ["microscope", "thermomètre", "calendrier", "batterie"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un lieu de transport ?", options: ["gare", "poubelle", "microscope", "semis"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est lié à la gestion des déchets ?", options: ["recyclage", "aéroport", "calendrier", "médecin"], correct: 0 },
      { diff: "medium", avatar: null, q: "Lequel est une action positive pour l’environnement ?", options: ["réduire les déchets", "jeter partout", "gaspiller l’eau", "brûler du plastique"], correct: 0 },
      { diff: "medium", avatar: null, q: "Lequel exprime une obligation ?", options: ["devoir", "pouvoir", "vouloir", "regarder"], correct: 0 },
      { diff: "medium", avatar: null, q: "Solaire et éolienne sont des énergies…", options: ["renouvelables", "fossiles", "alimentaires", "scolaires"], correct: 0 },
      { diff: "medium", avatar: null, q: "Médecin, pompier et scientifique sont des…", options: ["professions", "énergies", "déchets", "transports"], correct: 0 },
      { diff: "medium", avatar: null, q: "Gare et aéroport sont liés au…", options: ["transport", "recyclage", "jardinage", "corps"], correct: 0 },
      { diff: "medium", avatar: null, q: "Thermomètre et microscope sont des…", options: ["instruments", "vêtements", "aliments", "métiers"], correct: 0 },
      { diff: "medium", avatar: null, q: "Réduire, réutiliser et recycler aident à gérer les…", options: ["déchets", "professions", "saisons", "vêtements"], correct: 0 },
      { diff: "medium", avatar: null, q: "Protéger et préserver ont des sens…", options: ["proches", "opposés", "numériques", "sans rapport"], correct: 0 },
      { diff: "medium", avatar: null, q: "Meilleur et pire expriment une…", options: ["comparaison", "profession", "direction", "date"], correct: 0 },
      { diff: "medium", avatar: null, q: "Avant et après indiquent l’…", options: ["ordre temporel", "couleur", "prix", "métier"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot va avec 🌡️ ?", options: ["thermomètre", "microscope", "calendrier", "batterie"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot va avec 🧑‍🚒 ?", options: ["pompier", "médecin", "artiste", "scientifique"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot va avec 🗑️ ?", options: ["poubelle", "robinet", "batterie", "gare"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot va avec 💨 ?", options: ["énergie éolienne", "énergie solaire", "électricité", "agriculture"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour envoyer une lettre, je vais au…", options: ["bureau de poste", "aéroport", "hôpital", "stade"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour prendre un train, je vais à la…", options: ["gare", "banque", "bibliothèque", "ferme"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour éviter le gaspillage d’eau, je dois…", options: ["fermer le robinet", "laisser couler l’eau", "polluer la rivière", "jeter les déchets"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour protéger l’environnement, une communauté peut…", options: ["recycler ses déchets", "brûler le plastique", "gaspiller l’eau", "jeter les déchets dans la rue"], correct: 0 },
      { diff: "hard", avatar: null, q: "Une batterie peut stocker de l’…", options: ["énergie", "agriculture", "pollution", "éducation"], correct: 0 },
    ],
  },
  {
    slug: "context", name: "Context", icon: "📖", color: "#3E9B7C",
    questions: [
      { diff: "easy", avatar: null, q: "Nous ____ protéger notre environnement.", options: ["devons", "pouvons pas", "voulez", "doit"], correct: 0 },
      { diff: "easy", avatar: null, q: "Je ____ économiser l’eau à la maison.", options: ["peux", "peut", "pouvons", "pouvez"], correct: 0 },
      { diff: "easy", avatar: null, q: "Les élèves ____ apprendre à recycler.", options: ["peuvent", "peux", "pouvez", "peut"], correct: 0 },
      { diff: "easy", avatar: null, q: "Elle ____ devenir scientifique plus tard.", options: ["veut", "veux", "voulons", "voulez"], correct: 0 },
      { diff: "easy", avatar: null, q: "Nous ____ des arbres dans la cour de l’école.", options: ["plantons", "plante", "plantez", "plantent"], correct: 0 },
      { diff: "easy", avatar: null, q: "Le soleil ____ de l’énergie renouvelable.", options: ["fournit", "fournissent", "fournissons", "fournissez"], correct: 0 },
      { diff: "medium", avatar: null, q: "Il faut fermer le robinet ____ économiser l’eau.", options: ["pour", "mais", "derrière", "pendant"], correct: 0 },
      { diff: "medium", avatar: null, q: "Nous recyclons; ____, nous réduisons les déchets.", options: ["ainsi", "sous", "hier", "loin"], correct: 0 },
      { diff: "medium", avatar: null, q: "La pollution est dangereuse; ____ nous devons la réduire.", options: ["donc", "derrière", "pendant", "jamais"], correct: 0 },
      { diff: "medium", avatar: null, q: "Le plastique est utile; ____, il peut polluer l’environnement.", options: ["cependant", "dessous", "demain", "toujours"], correct: 0 },
      { diff: "medium", avatar: null, q: "D’abord, je trie les déchets; ____, je les mets dans les bonnes poubelles.", options: ["ensuite", "derrière", "jamais", "avant-hier"], correct: 0 },
      { diff: "medium", avatar: null, q: "____ de quitter la classe, j’éteins la lumière.", options: ["Avant", "Sous", "Loin", "Jamais"], correct: 0 },
      { diff: "medium", avatar: null, q: "Je me lave les mains ____ avoir travaillé dans le jardin.", options: ["après", "devant", "souvent", "entre"], correct: 0 },
      { diff: "medium", avatar: null, q: "Nous devons boire de l’eau ____ quand il fait chaud.", options: ["potable", "sale", "polluée", "salée"], correct: 0 },
      { diff: "medium", avatar: null, q: "L’énergie solaire vient du ____.", options: ["soleil", "charbon", "pétrole", "plastique"], correct: 0 },
      { diff: "medium", avatar: null, q: "L’énergie éolienne utilise le ____.", options: ["vent", "sol", "riz", "livre"], correct: 0 },
      { diff: "hard", avatar: null, q: "Un thermomètre mesure la ____.", options: ["température", "distance", "vitesse", "masse"], correct: 0 },
      { diff: "hard", avatar: null, q: "Un microscope aide le scientifique à ____ de petits objets.", options: ["observer", "conduire", "cuisiner", "nager"], correct: 0 },
      { diff: "hard", avatar: null, q: "Le pompier aide à combattre les ____.", options: ["incendies", "livres", "examens", "récoltes"], correct: 0 },
      { diff: "hard", avatar: null, q: "Si nous gaspillons moins d’eau, nous aidons à ____ cette ressource.", options: ["préserver", "polluer", "détruire", "jeter"], correct: 0 },
      { diff: "hard", avatar: null, q: "Une ville plus propre est ____ pour la santé.", options: ["meilleure", "pire", "plus sale", "plus dangereuse"], correct: 0 },
      { diff: "hard", avatar: null, q: "Le vélo peut être ____ polluant qu’une voiture à essence.", options: ["moins", "plus", "aussi toujours", "jamais"], correct: 0 },
      { diff: "hard", avatar: null, q: "Si aujourd’hui est jeudi, trois jours plus tard sera ____.", options: ["dimanche", "vendredi", "samedi", "lundi"], correct: 0 },
      { diff: "hard", avatar: null, q: "Une année normale compte ____ jours.", options: ["365", "360", "300", "400"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour être un citoyen responsable, je dois respecter les autres et ____ l’environnement.", options: ["protéger", "polluer", "gaspiller", "détruire"], correct: 0 },
    ],
  },
]

export function p6LangCategoryBySlug(slug: string): LangCategory | undefined {
  return P6_LANG.find((c) => c.slug === slug)
}
