// AUTO-GENERATED Primary 3 FRENCH LANGUAGE quiz — 150 questions, 6 categories.
// From Gabe's primary_3_french_language_quiz_150 doc.

import type { LangCategory } from './lang-p1'

export const P3_LANG: LangCategory[] = [
  {
    slug: "obj-word", name: "Picture → Word", icon: "🖼️", color: "#3E7CA6",
    questions: [
      { diff: "easy", avatar: "🍍", q: "Quel est le mot français pour cet objet ?", options: ["ananas", "vent", "heure", "lit"], correct: 0 },
      { diff: "easy", avatar: "🍇", q: "Quel est le mot français pour cet objet ?", options: ["raisin", "jardin", "Terre", "chaussure"], correct: 0 },
      { diff: "easy", avatar: "🍉", q: "Quel est le mot français pour cet objet ?", options: ["pastèque", "jardin", "école", "chemise"], correct: 0 },
      { diff: "easy", avatar: "🌽", q: "Quel est le mot français pour cet objet ?", options: ["maïs", "cheval", "pantalon", "soleil"], correct: 0 },
      { diff: "easy", avatar: "🧅", q: "Quel est le mot français pour cet objet ?", options: ["oignon", "pantalon", "voiture", "maïs"], correct: 0 },
      { diff: "easy", avatar: "🐎", q: "Quel est le mot français pour cet objet ?", options: ["cheval", "chaise", "lit", "chaussure"], correct: 0 },
      { diff: "easy", avatar: "🐑", q: "Quel est le mot français pour cet objet ?", options: ["mouton", "livres", "abeille", "maïs"], correct: 0 },
      { diff: "easy", avatar: "🦆", q: "Quel est le mot français pour cet objet ?", options: ["canard", "chaussure", "chemise", "montagne"], correct: 0 },
      { diff: "medium", avatar: "🐝", q: "Quel est le mot français pour cet objet ?", options: ["abeille", "oignon", "bras", "canard"], correct: 0 },
      { diff: "medium", avatar: "🐘", q: "Quel est le mot français pour cet objet ?", options: ["éléphant", "chaussure", "livres", "lit"], correct: 0 },
      { diff: "medium", avatar: "🌈", q: "Quel est le mot français pour cet objet ?", options: ["arc-en-ciel", "chaussure", "ananas", "bouche"], correct: 0 },
      { diff: "medium", avatar: "🌬️", q: "Quel est le mot français pour cet objet ?", options: ["vent", "pantalon", "chien", "pomme"], correct: 0 },
      { diff: "medium", avatar: "🌍", q: "Quel est le mot français pour cet objet ?", options: ["Terre", "vent", "canard", "pastèque"], correct: 0 },
      { diff: "medium", avatar: "🌊", q: "Quel est le mot français pour cet objet ?", options: ["rivière", "bras", "canard", "oignon"], correct: 0 },
      { diff: "medium", avatar: "⛰️", q: "Quel est le mot français pour cet objet ?", options: ["montagne", "éléphant", "cheval", "canard"], correct: 0 },
      { diff: "medium", avatar: "🕐", q: "Quel est le mot français pour cet objet ?", options: ["heure", "chaussure", "ananas", "maïs"], correct: 0 },
      { diff: "medium", avatar: "📚", q: "Quel est le mot français pour cet objet ?", options: ["livres", "soleil", "lit", "bouche"], correct: 0 },
      { diff: "medium", avatar: "🧹", q: "Quel est le mot français pour cet objet ?", options: ["balai", "Terre", "pomme", "eau"], correct: 0 },
      { diff: "hard", avatar: "🛏️", q: "Quel est le mot français pour cet objet ?", options: ["lit", "jardin", "bouche", "eau"], correct: 0 },
      { diff: "hard", avatar: "👕", q: "Quel est le mot français pour cet objet ?", options: ["chemise", "pantalon", "voiture", "oignon"], correct: 0 },
      { diff: "hard", avatar: "👖", q: "Quel est le mot français pour cet objet ?", options: ["pantalon", "ananas", "jardin", "pomme"], correct: 0 },
      { diff: "hard", avatar: "👟", q: "Quel est le mot français pour cet objet ?", options: ["chaussure", "pomme", "bras", "canard"], correct: 0 },
      { diff: "hard", avatar: "🦷", q: "Quel est le mot français pour cet objet ?", options: ["dent", "heure", "ananas", "école"], correct: 0 },
      { diff: "hard", avatar: "👄", q: "Quel est le mot français pour cet objet ?", options: ["bouche", "pantalon", "arc-en-ciel", "voiture"], correct: 0 },
      { diff: "hard", avatar: "💪", q: "Quel est le mot français pour cet objet ?", options: ["bras", "jardin", "pastèque", "cheval"], correct: 0 },
    ],
  },
  {
    slug: "word-obj", name: "Word → Picture", icon: "🔤", color: "#5C9E3A",
    questions: [
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« ananas »** ?", options: ["🍍 Pineapple", "👖 Trousers", "💪 Arm", "🌈 Rainbow"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« raisin »** ?", options: ["🍇 Grapes", "🕐 Time", "🐘 Elephant", "⛰️ Mountain"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« pastèque »** ?", options: ["🍉 Watermelon", "🧹 Broom", "⛰️ Mountain", "🐘 Elephant"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« maïs »** ?", options: ["🌽 Corn", "📚 Books", "👖 Trousers", "🌊 River"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« oignon »** ?", options: ["🧅 Onion", "🍍 Pineapple", "🌊 River", "🌬️ Wind"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« cheval »** ?", options: ["🐎 Horse", "🌬️ Wind", "🐑 Sheep", "🌽 Corn"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« mouton »** ?", options: ["🐑 Sheep", "🐎 Horse", "👄 Mouth", "🌬️ Wind"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« canard »** ?", options: ["🦆 Duck", "👖 Trousers", "🌈 Rainbow", "🐎 Horse"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« abeille »** ?", options: ["🐝 Bee", "💪 Arm", "🌍 Earth", "⛰️ Mountain"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« éléphant »** ?", options: ["🐘 Elephant", "⛰️ Mountain", "🌬️ Wind", "👟 Shoe"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« arc-en-ciel »** ?", options: ["🌈 Rainbow", "🌍 Earth", "👕 Shirt", "🦷 Tooth"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« vent »** ?", options: ["🌬️ Wind", "🧹 Broom", "🍇 Grapes", "💪 Arm"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« Terre »** ?", options: ["🌍 Earth", "👟 Shoe", "💪 Arm", "🍍 Pineapple"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« rivière »** ?", options: ["🌊 River", "🦆 Duck", "📚 Books", "🍉 Watermelon"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« montagne »** ?", options: ["⛰️ Mountain", "🐝 Bee", "👕 Shirt", "🍉 Watermelon"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« heure »** ?", options: ["🕐 Time", "👕 Shirt", "🌽 Corn", "🐑 Sheep"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« livres »** ?", options: ["📚 Books", "🐑 Sheep", "👖 Trousers", "🍉 Watermelon"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« balai »** ?", options: ["🧹 Broom", "🍉 Watermelon", "🦷 Tooth", "🍍 Pineapple"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« lit »** ?", options: ["🛏️ Bed", "👕 Shirt", "🌊 River", "📚 Books"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« chemise »** ?", options: ["👕 Shirt", "🦷 Tooth", "🌬️ Wind", "🍍 Pineapple"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« pantalon »** ?", options: ["👖 Trousers", "🧅 Onion", "🌊 River", "🍍 Pineapple"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« chaussure »** ?", options: ["👟 Shoe", "🍉 Watermelon", "🧅 Onion", "⛰️ Mountain"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« dent »** ?", options: ["🦷 Tooth", "🍇 Grapes", "🍍 Pineapple", "🛏️ Bed"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« bouche »** ?", options: ["👄 Mouth", "🐑 Sheep", "🧹 Broom", "🦆 Duck"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« bras »** ?", options: ["💪 Arm", "👟 Shoe", "🌽 Corn", "🌈 Rainbow"], correct: 0 },
    ],
  },
  {
    slug: "spelling", name: "Spelling", icon: "🔤", color: "#C8912E",
    questions: [
      { diff: "easy", avatar: null, q: "Complète : anan□s.", options: ["a", "e", "i", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : rais□n.", options: ["i", "a", "o", "u"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : past□que.", options: ["è", "é", "e", "a"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : ma□s.", options: ["ï", "i", "î", "é"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : oign□n.", options: ["o", "a", "e", "i"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : chev□l.", options: ["a", "e", "i", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : mout□n.", options: ["o", "a", "i", "u"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : can□rd.", options: ["a", "e", "i", "o"], correct: 0 },
      { diff: "medium", avatar: null, q: "Complète : ab□ille.", options: ["e", "a", "i", "o"], correct: 0 },
      { diff: "medium", avatar: null, q: "Complète : éléph□nt.", options: ["a", "e", "i", "o"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["rivière", "riviére", "riviere", "rivièrre"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["montagne", "montaigne", "montagnee", "montange"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["chemise", "chamise", "chemisse", "chemize"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["pantalon", "pantallon", "pantalone", "pentallon"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["chaussure", "chausure", "chaussurre", "chossure"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["bouche", "buche", "bouch", "boushe"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["école", "ecole", "écolle", "école"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["maître", "maitre", "maîttre", "mêtre"], correct: 0 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["élève", "éleve", "èlève", "élèvve"], correct: 0 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["fenêtre", "fenetre", "fénêtre", "fenêttre"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : aujourd’hu□.", options: ["i", "e", "a", "o"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : merc□.", options: ["i", "e", "a", "o"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : fam□lle.", options: ["i", "e", "a", "o"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : cuis□ne.", options: ["i", "e", "a", "o"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : mat□n.", options: ["i", "e", "a", "o"], correct: 0 },
    ],
  },
  {
    slug: "meaning", name: "Meaning", icon: "💬", color: "#E0574C",
    questions: [
      { diff: "easy", avatar: null, q: "Que veut dire « ananas » ?", options: ["Pineapple", "Grapes", "Watermelon", "Onion"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « raisin » ?", options: ["Grapes", "Pineapple", "Corn", "Carrot"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « cheval » ?", options: ["Horse", "Sheep", "Duck", "Goat"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « mouton » ?", options: ["Sheep", "Horse", "Cow", "Chicken"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « abeille » ?", options: ["Bee", "Butterfly", "Bird", "Duck"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « rivière » ?", options: ["River", "Mountain", "Road", "Garden"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « montagne » ?", options: ["Mountain", "River", "School", "House"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « vent » ?", options: ["Wind", "Rain", "Sun", "Cloud"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « chemise » ?", options: ["Shirt", "Trousers", "Shoe", "Hat"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « pantalon » ?", options: ["Trousers", "Shirt", "Shoe", "Dress"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « bouche » ?", options: ["Mouth", "Tooth", "Arm", "Ear"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « dent » ?", options: ["Tooth", "Mouth", "Hand", "Foot"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « matin » ?", options: ["Morning", "Evening", "Night", "Week"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « soir » ?", options: ["Evening", "Morning", "Month", "Year"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « aujourd’hui » ?", options: ["Today", "Tomorrow", "Yesterday", "Morning"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « demain » ?", options: ["Tomorrow", "Today", "Yesterday", "Night"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « hier » ?", options: ["Yesterday", "Tomorrow", "Today", "Week"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « grand » ?", options: ["Big", "Small", "Fast", "Cold"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « petit » ?", options: ["Small", "Big", "Hot", "Long"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « chaud » ?", options: ["Hot", "Cold", "Small", "Young"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « froid » ?", options: ["Cold", "Hot", "Big", "Happy"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « heureux » ?", options: ["Happy", "Sad", "Cold", "Slow"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « triste » ?", options: ["Sad", "Happy", "Hot", "Fast"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « jouer » ?", options: ["To play", "To eat", "To sleep", "To read"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « travailler » ?", options: ["To work", "To play", "To drink", "To jump"], correct: 0 },
    ],
  },
  {
    slug: "matching", name: "Matching", icon: "🔗", color: "#7A7488",
    questions: [
      { diff: "easy", avatar: null, q: "Lequel est un vêtement ?", options: ["chemise", "rivière", "abeille", "livre"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un animal ?", options: ["cheval", "pantalon", "montagne", "heure"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est une partie du corps ?", options: ["dent", "chemise", "maïs", "balai"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel décrit le temps qu’il fait ?", options: ["vent", "livre", "lit", "pantalon"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un lieu naturel ?", options: ["montagne", "chemise", "chaussure", "balai"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est une action ?", options: ["jouer", "rivière", "jaune", "cheval"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel décrit une émotion ?", options: ["heureux", "chemise", "rivière", "maïs"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel indique le temps ?", options: ["demain", "chaussure", "abeille", "bras"], correct: 0 },
      { diff: "medium", avatar: null, q: "Ananas et raisin sont des…", options: ["fruits", "animaux", "vêtements", "actions"], correct: 0 },
      { diff: "medium", avatar: null, q: "Cheval et mouton sont des…", options: ["animaux", "fruits", "couleurs", "meubles"], correct: 0 },
      { diff: "medium", avatar: null, q: "Chemise et pantalon sont des…", options: ["vêtements", "animaux", "aliments", "lieux"], correct: 0 },
      { diff: "medium", avatar: null, q: "Bouche et dent sont des parties du…", options: ["corps", "jardin", "ciel", "livre"], correct: 0 },
      { diff: "medium", avatar: null, q: "Matin et soir sont des moments de la…", options: ["journée", "famille", "classe", "couleur"], correct: 0 },
      { diff: "medium", avatar: null, q: "Heureux et triste sont des…", options: ["émotions", "fruits", "vêtements", "animaux"], correct: 0 },
      { diff: "medium", avatar: null, q: "Chaud et froid sont des…", options: ["contraires", "animaux", "nombres", "aliments"], correct: 0 },
      { diff: "medium", avatar: null, q: "Grand et petit sont des…", options: ["contraires", "boissons", "lieux", "personnes"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel mot va avec 🌈 ?", options: ["arc-en-ciel", "rivière", "vent", "montagne"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel mot va avec 👕 ?", options: ["chemise", "pantalon", "chaussure", "chapeau"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot va avec 🦷 ?", options: ["dent", "bouche", "bras", "main"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot va avec 🌽 ?", options: ["maïs", "raisin", "oignon", "ananas"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour dormir, j’utilise un…", options: ["lit", "balai", "livre", "bus"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour nettoyer le sol, j’utilise un…", options: ["balai", "lit", "chemise", "raisin"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour apprendre, je vais à l’…", options: ["école", "rivière", "montagne", "ferme"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour jouer au football, j’utilise mes…", options: ["pieds", "oreilles", "dents", "yeux"], correct: 0 },
      { diff: "hard", avatar: null, q: "Une abeille peut produire du…", options: ["miel", "lait", "pain", "riz"], correct: 0 },
    ],
  },
  {
    slug: "context", name: "Context", icon: "📖", color: "#3E9B7C",
    questions: [
      { diff: "easy", avatar: null, q: "Je ____ au football avec mes amis.", options: ["joue", "mange", "dors", "bois"], correct: 0 },
      { diff: "easy", avatar: null, q: "Nous ____ à l’école le matin.", options: ["allons", "mangeons", "dormons", "buvons"], correct: 0 },
      { diff: "easy", avatar: null, q: "Elle ____ un livre en classe.", options: ["lit", "boit", "court", "mange"], correct: 0 },
      { diff: "easy", avatar: null, q: "Il ____ de l’eau après le sport.", options: ["boit", "lit", "écrit", "dort"], correct: 0 },
      { diff: "easy", avatar: null, q: "Je porte une ____ sur le corps.", options: ["chemise", "rivière", "abeille", "montagne"], correct: 0 },
      { diff: "easy", avatar: null, q: "Je mets mes ____ pour marcher.", options: ["chaussures", "livres", "nuages", "dents"], correct: 0 },
      { diff: "easy", avatar: null, q: "Le cheval est plus ____ qu’une abeille.", options: ["grand", "petit", "froid", "triste"], correct: 0 },
      { diff: "easy", avatar: null, q: "Une abeille est plus ____ qu’un cheval.", options: ["petite", "grande", "chaude", "longue"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quand je souris, je suis ____.", options: ["heureux", "froid", "grand", "lent"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quand je pleure, je suis ____.", options: ["triste", "chaud", "petit", "rapide"], correct: 0 },
      { diff: "medium", avatar: null, q: "Le matin vient avant le ____.", options: ["soir", "livre", "vent", "bras"], correct: 0 },
      { diff: "medium", avatar: null, q: "Aujourd’hui vient avant ____.", options: ["demain", "hier", "matin", "soir"], correct: 0 },
      { diff: "medium", avatar: null, q: "Hier vient avant ____.", options: ["aujourd’hui", "demain", "soir", "semaine"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quand il fait très froid, je porte une ____.", options: ["chemise", "pastèque", "rivière", "abeille"], correct: 0 },
      { diff: "medium", avatar: null, q: "La rivière contient de l’____.", options: ["eau", "pain", "livre", "soleil"], correct: 0 },
      { diff: "medium", avatar: null, q: "Les plantes ont besoin d’eau et de ____.", options: ["soleil", "chaussures", "livres", "ciseaux"], correct: 0 },
      { diff: "medium", avatar: null, q: "Je mange avec ma ____.", options: ["bouche", "oreille", "main", "jambe"], correct: 0 },
      { diff: "medium", avatar: null, q: "Je mâche avec mes ____.", options: ["dents", "bras", "oreilles", "pieds"], correct: 0 },
      { diff: "hard", avatar: null, q: "Je porte mon sac avec mon ____.", options: ["bras", "nez", "œil", "pied"], correct: 0 },
      { diff: "hard", avatar: null, q: "L’abeille vole dans le ____.", options: ["ciel", "lit", "livre", "bus"], correct: 0 },
      { diff: "hard", avatar: null, q: "Dix plus un fait ____.", options: ["onze", "neuf", "douze", "huit"], correct: 0 },
      { diff: "hard", avatar: null, q: "Douze vient après ____.", options: ["onze", "treize", "dix", "neuf"], correct: 0 },
      { diff: "hard", avatar: null, q: "Il y a sept jours dans une ____.", options: ["semaine", "journée", "heure", "année"], correct: 0 },
      { diff: "hard", avatar: null, q: "Je dis « au revoir » quand je ____.", options: ["pars", "arrive", "mange", "dors"], correct: 0 },
      { diff: "hard", avatar: null, q: "À l’école, le maître aide les ____ à apprendre.", options: ["élèves", "rivières", "chemises", "abeilles"], correct: 0 },
    ],
  },
]

export function p3LangCategoryBySlug(slug: string): LangCategory | undefined {
  return P3_LANG.find((c) => c.slug === slug)
}
