// AUTO-GENERATED Primary 2 FRENCH LANGUAGE quiz — 150 questions, 6 categories.
// From Gabe's primary_2_french_language_quiz_150 doc. Emoji avatars, no images.

import type { LangCategory } from './lang-p1'

export const P2_LANG: LangCategory[] = [
  {
    slug: "obj-word", name: "Picture → Word", icon: "🖼️", color: "#3E7CA6",
    questions: [
      { diff: "easy", avatar: "🍊", q: "Quel est le mot français pour cet objet ?", options: ["orange", "papillon", "ciseaux", "tomate"], correct: 0 },
      { diff: "easy", avatar: "🥭", q: "Quel est le mot français pour cet objet ?", options: ["mangue", "chaise", "étoile", "chèvre"], correct: 0 },
      { diff: "easy", avatar: "🍅", q: "Quel est le mot français pour cet objet ?", options: ["tomate", "main", "poule", "règle"], correct: 0 },
      { diff: "easy", avatar: "🥕", q: "Quel est le mot français pour cet objet ?", options: ["carotte", "école", "pomme de terre", "oreille"], correct: 0 },
      { diff: "easy", avatar: "🥔", q: "Quel est le mot français pour cet objet ?", options: ["pomme de terre", "étoile", "livre", "carotte"], correct: 0 },
      { diff: "easy", avatar: "🐰", q: "Quel est le mot français pour cet objet ?", options: ["lapin", "mangue", "crayon de couleur", "nez"], correct: 0 },
      { diff: "easy", avatar: "🐔", q: "Quel est le mot français pour cet objet ?", options: ["poule", "chien", "plante", "étoile"], correct: 0 },
      { diff: "easy", avatar: "🐄", q: "Quel est le mot français pour cet objet ?", options: ["vache", "chèvre", "carotte", "oreille"], correct: 0 },
      { diff: "medium", avatar: "🐐", q: "Quel est le mot français pour cet objet ?", options: ["chèvre", "œil", "crayon de couleur", "étoile"], correct: 0 },
      { diff: "medium", avatar: "🦋", q: "Quel est le mot français pour cet objet ?", options: ["papillon", "chat", "nez", "nuage"], correct: 0 },
      { diff: "medium", avatar: "☁️", q: "Quel est le mot français pour cet objet ?", options: ["nuage", "école", "étoile", "livre"], correct: 0 },
      { diff: "medium", avatar: "🌧️", q: "Quel est le mot français pour cet objet ?", options: ["pluie", "carotte", "œil", "tomate"], correct: 0 },
      { diff: "medium", avatar: "⭐", q: "Quel est le mot français pour cet objet ?", options: ["étoile", "chien", "crayon de couleur", "bus"], correct: 0 },
      { diff: "medium", avatar: "🌱", q: "Quel est le mot français pour cet objet ?", options: ["plante", "chien", "chat", "pluie"], correct: 0 },
      { diff: "medium", avatar: "🍃", q: "Quel est le mot français pour cet objet ?", options: ["feuille", "nez", "pied", "chat"], correct: 0 },
      { diff: "medium", avatar: "📏", q: "Quel est le mot français pour cet objet ?", options: ["règle", "mangue", "nez", "livre"], correct: 0 },
      { diff: "medium", avatar: "✂️", q: "Quel est le mot français pour cet objet ?", options: ["ciseaux", "livre", "lapin", "chaise"], correct: 0 },
      { diff: "medium", avatar: "🖍️", q: "Quel est le mot français pour cet objet ?", options: ["crayon de couleur", "main", "poule", "livre"], correct: 0 },
      { diff: "hard", avatar: "🏫", q: "Quel est le mot français pour cet objet ?", options: ["école", "chat", "carotte", "étoile"], correct: 0 },
      { diff: "hard", avatar: "🚌", q: "Quel est le mot français pour cet objet ?", options: ["bus", "règle", "chat", "orange"], correct: 0 },
      { diff: "hard", avatar: "👃", q: "Quel est le mot français pour cet objet ?", options: ["nez", "poule", "eau", "étoile"], correct: 0 },
      { diff: "hard", avatar: "👂", q: "Quel est le mot français pour cet objet ?", options: ["oreille", "nuage", "mangue", "pomme"], correct: 0 },
      { diff: "hard", avatar: "👁️", q: "Quel est le mot français pour cet objet ?", options: ["œil", "main", "pluie", "oreille"], correct: 0 },
      { diff: "hard", avatar: "🖐️", q: "Quel est le mot français pour cet objet ?", options: ["main", "œil", "étoile", "chaise"], correct: 0 },
      { diff: "hard", avatar: "🦶", q: "Quel est le mot français pour cet objet ?", options: ["pied", "tomate", "pomme de terre", "chèvre"], correct: 0 },
    ],
  },
  {
    slug: "word-obj", name: "Word → Picture", icon: "🔤", color: "#5C9E3A",
    questions: [
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« orange »** ?", options: ["🍊 Orange", "👂 Ear", "🦶 Foot", "🐄 Cow"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« mangue »** ?", options: ["🥭 Mango", "👂 Ear", "🖐️ Hand", "🥔 Potato"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« tomate »** ?", options: ["🍅 Tomato", "🥭 Mango", "🐄 Cow", "🍃 Leaf"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« carotte »** ?", options: ["🥕 Carrot", "🥔 Potato", "🐰 Rabbit", "🚌 Bus"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« pomme de terre »** ?", options: ["🥔 Potato", "📏 Ruler", "🥭 Mango", "🥕 Carrot"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« lapin »** ?", options: ["🐰 Rabbit", "✂️ Scissors", "🖐️ Hand", "🖍️ Crayon"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« poule »** ?", options: ["🐔 Chicken", "🥔 Potato", "🚌 Bus", "☁️ Cloud"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« vache »** ?", options: ["🐄 Cow", "👁️ Eye", "🦶 Foot", "✂️ Scissors"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« chèvre »** ?", options: ["🐐 Goat", "✂️ Scissors", "🦶 Foot", "🍅 Tomato"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« papillon »** ?", options: ["🦋 Butterfly", "👂 Ear", "🖐️ Hand", "⭐ Star"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« nuage »** ?", options: ["☁️ Cloud", "🥕 Carrot", "👃 Nose", "🐐 Goat"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« pluie »** ?", options: ["🌧️ Rain", "🥕 Carrot", "🍊 Orange", "🐰 Rabbit"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« étoile »** ?", options: ["⭐ Star", "🖍️ Crayon", "🌧️ Rain", "👂 Ear"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« plante »** ?", options: ["🌱 Plant", "🍅 Tomato", "☁️ Cloud", "🥕 Carrot"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« feuille »** ?", options: ["🍃 Leaf", "🐰 Rabbit", "👂 Ear", "🖐️ Hand"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« règle »** ?", options: ["📏 Ruler", "👃 Nose", "🌱 Plant", "🖐️ Hand"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« ciseaux »** ?", options: ["✂️ Scissors", "🐐 Goat", "🐰 Rabbit", "🥭 Mango"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« crayon de couleur »** ?", options: ["🖍️ Crayon", "🍅 Tomato", "🐔 Chicken", "🌧️ Rain"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« école »** ?", options: ["🏫 School", "👁️ Eye", "🥕 Carrot", "🐔 Chicken"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« bus »** ?", options: ["🚌 Bus", "🖍️ Crayon", "🐐 Goat", "📏 Ruler"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« nez »** ?", options: ["👃 Nose", "🍅 Tomato", "🐰 Rabbit", "🍊 Orange"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« oreille »** ?", options: ["👂 Ear", "🐐 Goat", "🥕 Carrot", "🏫 School"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« œil »** ?", options: ["👁️ Eye", "📏 Ruler", "🚌 Bus", "🐔 Chicken"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« main »** ?", options: ["🖐️ Hand", "⭐ Star", "🌧️ Rain", "🥕 Carrot"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« pied »** ?", options: ["🦶 Foot", "🖐️ Hand", "✂️ Scissors", "🐰 Rabbit"], correct: 0 },
    ],
  },
  {
    slug: "spelling", name: "Spelling", icon: "🔤", color: "#C8912E",
    questions: [
      { diff: "easy", avatar: null, q: "Complète : or□nge.", options: ["a", "e", "i", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : mang□e.", options: ["u", "a", "i", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : tom□te.", options: ["a", "o", "e", "i"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : car□tte.", options: ["o", "a", "e", "u"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : lap□n.", options: ["i", "a", "o", "e"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : p□ule.", options: ["o", "a", "i", "u"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : vach□.", options: ["e", "a", "i", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : ch□vre.", options: ["è", "é", "a", "i"], correct: 0 },
      { diff: "medium", avatar: null, q: "Complète : nu□ge.", options: ["a", "o", "i", "e"], correct: 0 },
      { diff: "medium", avatar: null, q: "Complète : pl□ie.", options: ["u", "a", "i", "o"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["papillon", "papilon", "pappillon", "papillan"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["étoile", "étoille", "étoale", "étoil"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["feuille", "feuil", "feuille", "feulle"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["règle", "régle", "règle", "regle"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["ciseaux", "cisaux", "ciseaus", "siseaux"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["oreille", "oreile", "orreille", "oraile"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["main", "mein", "maan", "moin"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["pied", "pié", "peid", "piet"], correct: 0 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["école", "écolle", "écôle", "école"], correct: 0 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["jardin", "jerdin", "jardain", "jardin"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : fr□re.", options: ["è", "é", "a", "i"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : s□ur.", options: ["œ", "o", "e", "u"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : cl□sse.", options: ["a", "e", "i", "o"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : tabl□au.", options: ["e", "a", "i", "o"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : fen□tre.", options: ["ê", "é", "è", "e"], correct: 0 },
    ],
  },
  {
    slug: "meaning", name: "Meaning", icon: "💬", color: "#E0574C",
    questions: [
      { diff: "easy", avatar: null, q: "Que veut dire « orange » ?", options: ["Orange", "Mango", "Tomato", "Carrot"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « mangue » ?", options: ["Mango", "Banana", "Apple", "Orange"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « carotte » ?", options: ["Carrot", "Tomato", "Potato", "Onion"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « lapin » ?", options: ["Rabbit", "Chicken", "Cow", "Goat"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « vache » ?", options: ["Cow", "Goat", "Rabbit", "Chicken"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « chèvre » ?", options: ["Goat", "Cow", "Dog", "Cat"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « pluie » ?", options: ["Rain", "Sun", "Cloud", "Wind"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « nuage » ?", options: ["Cloud", "Rain", "Sun", "Tree"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « étoile » ?", options: ["Star", "Moon", "Sun", "Cloud"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « feuille » ?", options: ["Leaf", "Flower", "Tree", "Fruit"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « règle » ?", options: ["Ruler", "Book", "Pen", "Bag"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « ciseaux » ?", options: ["Scissors", "Ruler", "Pencil", "Book"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « nez » ?", options: ["Nose", "Ear", "Eye", "Hand"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « oreille » ?", options: ["Ear", "Nose", "Eye", "Foot"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « main » ?", options: ["Hand", "Foot", "Eye", "Ear"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « frère » ?", options: ["Brother", "Sister", "Mother", "Father"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « sœur » ?", options: ["Sister", "Brother", "Mother", "Baby"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « classe » ?", options: ["Classroom", "Garden", "Market", "Road"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « fenêtre » ?", options: ["Window", "Door", "Chair", "Table"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « manger » ?", options: ["To eat", "To drink", "To read", "To run"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « boire » ?", options: ["To drink", "To eat", "To write", "To sleep"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « lire » ?", options: ["To read", "To write", "To walk", "To sing"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « écrire » ?", options: ["To write", "To read", "To drink", "To jump"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « courir » ?", options: ["To run", "To sleep", "To sit", "To eat"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « bonjour » ?", options: ["Hello", "Goodbye", "Thank you", "Please"], correct: 0 },
    ],
  },
  {
    slug: "matching", name: "Matching", icon: "🔗", color: "#7A7488",
    questions: [
      { diff: "easy", avatar: null, q: "Lequel est un légume ?", options: ["carotte", "mangue", "livre", "chat"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un animal de la ferme ?", options: ["vache", "livre", "soleil", "chaise"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est une partie du corps ?", options: ["nez", "règle", "nuage", "bus"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un objet scolaire ?", options: ["règle", "chèvre", "pluie", "mangue"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel décrit la météo ?", options: ["pluie", "livre", "pied", "bus"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un membre de la famille ?", options: ["frère", "carotte", "étoile", "règle"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est une action ?", options: ["courir", "maison", "jaune", "lapin"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel pousse sur une plante ?", options: ["feuille", "bus", "ciseaux", "nez"], correct: 0 },
      { diff: "medium", avatar: null, q: "Lequel peut voler ?", options: ["papillon", "vache", "carotte", "table"], correct: 0 },
      { diff: "medium", avatar: null, q: "Lequel sert à couper du papier ?", options: ["ciseaux", "règle", "livre", "sac"], correct: 0 },
      { diff: "medium", avatar: null, q: "Mangue et orange sont des…", options: ["fruits", "animaux", "meubles", "actions"], correct: 0 },
      { diff: "medium", avatar: null, q: "Carotte et tomate sont des…", options: ["légumes", "couleurs", "animaux", "boissons"], correct: 0 },
      { diff: "medium", avatar: null, q: "Vache et chèvre sont des…", options: ["animaux", "fruits", "écoles", "couleurs"], correct: 0 },
      { diff: "medium", avatar: null, q: "Nez et oreille sont des parties du…", options: ["corps", "jardin", "bus", "livre"], correct: 0 },
      { diff: "medium", avatar: null, q: "Règle et ciseaux sont des objets de…", options: ["classe", "ferme", "route", "ciel"], correct: 0 },
      { diff: "medium", avatar: null, q: "Pluie et nuage parlent de la…", options: ["météo", "famille", "classe", "nourriture"], correct: 0 },
      { diff: "medium", avatar: null, q: "Frère et sœur sont de la…", options: ["famille", "météo", "classe", "couleur"], correct: 0 },
      { diff: "medium", avatar: null, q: "Lire et écrire sont des…", options: ["actions", "fruits", "animaux", "couleurs"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot va avec 👂 ?", options: ["oreille", "nez", "main", "pied"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot va avec 🖐️ ?", options: ["main", "pied", "œil", "nez"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot va avec 🌧️ ?", options: ["pluie", "soleil", "étoile", "feuille"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot va avec 🐰 ?", options: ["lapin", "vache", "poule", "chèvre"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot va avec ✂️ ?", options: ["ciseaux", "règle", "livre", "crayon"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour lire, j’utilise un…", options: ["livre", "vélo", "nuage", "lapin"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour écrire, j’utilise un…", options: ["crayon", "chien", "pluie", "orange"], correct: 0 },
    ],
  },
  {
    slug: "context", name: "Context", icon: "📖", color: "#3E9B7C",
    questions: [
      { diff: "easy", avatar: null, q: "Je ____ une pomme.", options: ["mange", "bois", "lis", "dors"], correct: 0 },
      { diff: "easy", avatar: null, q: "Je ____ de l’eau.", options: ["bois", "mange", "écris", "cours"], correct: 0 },
      { diff: "easy", avatar: null, q: "Je ____ un livre.", options: ["lis", "bois", "saute", "mange"], correct: 0 },
      { diff: "easy", avatar: null, q: "J’____ mon nom.", options: ["écris", "mange", "bois", "dors"], correct: 0 },
      { diff: "easy", avatar: null, q: "Je ____ dans la cour.", options: ["cours", "lis", "bois", "dors"], correct: 0 },
      { diff: "easy", avatar: null, q: "La vache est un ____.", options: ["animal", "fruit", "objet", "couleur"], correct: 0 },
      { diff: "easy", avatar: null, q: "La carotte est un ____.", options: ["légume", "animal", "meuble", "véhicule"], correct: 0 },
      { diff: "easy", avatar: null, q: "J’écoute avec mes ____.", options: ["oreilles", "mains", "pieds", "yeux"], correct: 0 },
      { diff: "medium", avatar: null, q: "Je regarde avec mes ____.", options: ["yeux", "oreilles", "pieds", "mains"], correct: 0 },
      { diff: "medium", avatar: null, q: "Je tiens le crayon avec ma ____.", options: ["main", "oreille", "bouche", "jambe"], correct: 0 },
      { diff: "medium", avatar: null, q: "Mon frère est un ____.", options: ["garçon", "fruit", "animal", "objet"], correct: 0 },
      { diff: "medium", avatar: null, q: "Ma sœur est une ____.", options: ["fille", "boisson", "couleur", "école"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quand il pleut, il y a de la ____.", options: ["pluie", "chaise", "pomme", "règle"], correct: 0 },
      { diff: "medium", avatar: null, q: "Le nuage est dans le ____.", options: ["ciel", "sac", "livre", "lait"], correct: 0 },
      { diff: "medium", avatar: null, q: "La feuille est sur l’____.", options: ["arbre", "bus", "livre", "chaise"], correct: 0 },
      { diff: "medium", avatar: null, q: "Nous apprenons dans la ____.", options: ["classe", "voiture", "pluie", "carotte"], correct: 0 },
      { diff: "medium", avatar: null, q: "J’ouvre la ____ pour voir dehors.", options: ["fenêtre", "pomme", "vache", "règle"], correct: 0 },
      { diff: "medium", avatar: null, q: "Les ciseaux servent à ____.", options: ["couper", "boire", "dormir", "manger"], correct: 0 },
      { diff: "hard", avatar: null, q: "La règle sert à mesurer une ____.", options: ["longueur", "boisson", "famille", "couleur"], correct: 0 },
      { diff: "hard", avatar: null, q: "Un bus sert à se ____.", options: ["déplacer", "manger", "lire", "dormir"], correct: 0 },
      { diff: "hard", avatar: null, q: "Cinq vient après ____.", options: ["quatre", "six", "trois", "sept"], correct: 0 },
      { diff: "hard", avatar: null, q: "Sept vient avant ____.", options: ["huit", "six", "cinq", "neuf"], correct: 0 },
      { diff: "hard", avatar: null, q: "« Bonjour » est une ____.", options: ["salutation", "couleur", "boisson", "plante"], correct: 0 },
      { diff: "hard", avatar: null, q: "Je dis « merci » quand quelqu’un m’____.", options: ["aide", "mange", "court", "dort"], correct: 0 },
      { diff: "hard", avatar: null, q: "Le matin, je dis « ____ ».", options: ["bonjour", "au revoir", "merci", "bonne nuit"], correct: 0 },
    ],
  },
]

export function p2LangCategoryBySlug(slug: string): LangCategory | undefined {
  return P2_LANG.find((c) => c.slug === slug)
}
