// AUTO-GENERATED JSS 2 FRENCH LANGUAGE quiz — 150 questions, 6 categories.

import type { LangCategory } from './lang-p1'

export const JSS2_LANG: LangCategory[] = [
  {
    slug: "obj-word", name: "Visual Vocabulary", icon: "🖼️", color: "#3E7CA6",
    questions: [
      { diff: "easy", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["ordinateur", "marché", "école", "amitié"], correct: 3 },
      { diff: "easy", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["ordinateur", "famille", "école", "marché"], correct: 1 },
      { diff: "easy", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["quartier", "école", "ordinateur", "marché"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["marché", "école", "ordinateur", "ville"], correct: 3 },
      { diff: "easy", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["village", "école", "marché", "ordinateur"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["école", "ordinateur", "transport public", "marché"], correct: 2 },
      { diff: "medium", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["ordinateur", "école", "marché", "cyclisme"], correct: 3 },
      { diff: "medium", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["marché", "ordinateur", "piéton", "école"], correct: 2 },
      { diff: "medium", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["ordinateur", "école", "signalisation", "marché"], correct: 2 },
      { diff: "medium", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["école", "courses", "marché", "ordinateur"], correct: 1 },
      { diff: "medium", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["école", "ordinateur", "alimentation saine", "marché"], correct: 2 },
      { diff: "medium", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["école", "ordinateur", "marché", "exercice physique"], correct: 3 },
      { diff: "medium", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["bien-être", "ordinateur", "marché", "école"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["école", "marché", "ordinateur", "santé"], correct: 3 },
      { diff: "medium", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["ordinateur", "école", "marché", "médicament"], correct: 3 },
      { diff: "hard", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["climat", "marché", "école", "ordinateur"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["marché", "ordinateur", "température", "école"], correct: 2 },
      { diff: "hard", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["marché", "école", "biodiversité", "ordinateur"], correct: 2 },
      { diff: "hard", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["école", "gestion des déchets", "marché", "ordinateur"], correct: 1 },
      { diff: "hard", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["école", "marché", "ordinateur", "économie d’eau"], correct: 3 },
      { diff: "hard", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["courriel", "marché", "école", "ordinateur"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["ordinateur", "école", "journal", "marché"], correct: 2 },
      { diff: "hard", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["école", "télévision", "ordinateur", "marché"], correct: 1 },
      { diff: "hard", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["école", "marché", "radio", "ordinateur"], correct: 2 },
      { diff: "hard", avatar: null, q: "Quel mot français correspond le mieux à cette image ?", options: ["Internet", "marché", "ordinateur", "école"], correct: 0 },
    ],
  },
  {
    slug: "grammar", name: "Grammar, Tenses & Agreement", icon: "✍️", color: "#5C9E3A",
    questions: [
      { diff: "easy", avatar: null, q: "Complète : Nous ____ français en classe.", options: ["parle", "parlez", "parlent", "parlons"], correct: 3 },
      { diff: "easy", avatar: null, q: "Complète : Ils ____ leurs devoirs.", options: ["finis", "finissent", "finissons", "finissez"], correct: 1 },
      { diff: "easy", avatar: null, q: "Tu ____ prendre le bus.", options: ["devez", "devons", "dois", "doit"], correct: 2 },
      { diff: "easy", avatar: null, q: "Elle ____ aller au marché.", options: ["veux", "voulons", "voulez", "veut"], correct: 3 },
      { diff: "easy", avatar: null, q: "Vous ____ utiliser Internet.", options: ["pouvons", "peux", "pouvez", "peut"], correct: 2 },
      { diff: "medium", avatar: null, q: "Hier, j’____ au football.", options: ["ai joué", "suis joué", "avais jouer", "joue"], correct: 0 },
      { diff: "medium", avatar: null, q: "Hier, elle ____ au marché.", options: ["va", "est allée", "a allé", "est allé"], correct: 1 },
      { diff: "medium", avatar: null, q: "Nous ____ nos devoirs hier.", options: ["sommes fini", "finissons", "avez fini", "avons fini"], correct: 3 },
      { diff: "medium", avatar: null, q: "Je ____ étudier ce soir.", options: ["allons", "va", "vais", "allez"], correct: 2 },
      { diff: "medium", avatar: null, q: "Ils ____ voyager demain.", options: ["vont", "va", "allons", "allez"], correct: 0 },
      { diff: "medium", avatar: null, q: "Ma sœur est ____ que moi.", options: ["plus jeune", "jeunes", "jeune plus", "la plus jeune que"], correct: 0 },
      { diff: "medium", avatar: null, q: "Ce livre est ____ intéressant que l’autre.", options: ["très que", "beaucoup que", "le", "plus"], correct: 3 },
      { diff: "medium", avatar: null, q: "Amina est ____ élève de la classe.", options: ["plus meilleure", "la meilleure", "le meilleur", "meilleure que"], correct: 1 },
      { diff: "medium", avatar: null, q: "Je vois Marie. Je ____ vois.", options: ["les", "la", "lui", "le"], correct: 1 },
      { diff: "medium", avatar: null, q: "Je parle à Paul. Je ____ parle.", options: ["le", "les", "lui", "la"], correct: 2 },
      { diff: "hard", avatar: null, q: "Il faut ____ les déchets.", options: ["trié", "trier", "trie", "trions"], correct: 1 },
      { diff: "hard", avatar: null, q: "Je n’ai ____ mangé aujourd’hui.", options: ["aucun", "plus de", "personne", "rien"], correct: 3 },
      { diff: "hard", avatar: null, q: "Nous ne voyons ____ dans la salle.", options: ["rien", "jamais pas", "aucunement", "personne"], correct: 3 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["biodiversitéé", "biodivérsité", "biodiversitée", "biodiversité"], correct: 3 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["comunication", "communicattion", "communication", "communicassion"], correct: 2 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["dévelopement", "développement", "developement", "dévellopement"], correct: 1 },
      { diff: "hard", avatar: null, q: "C’est ____ cahier à moi.", options: ["ton", "mes", "mon", "ma"], correct: 2 },
      { diff: "hard", avatar: null, q: "____ ordinateur est nouveau.", options: ["Cette", "Ces", "Cet", "Ce"], correct: 2 },
      { diff: "hard", avatar: null, q: "Les filles sont ____ au stade.", options: ["allées", "allés", "allée", "allé"], correct: 0 },
      { diff: "hard", avatar: null, q: "Si tu es malade, tu ____ consulter un médecin.", options: ["doit", "devons", "devez", "dois"], correct: 3 },
    ],
  },
  {
    slug: "vocab", name: "Vocabulary & Functional French", icon: "💬", color: "#C8912E",
    questions: [
      { diff: "easy", avatar: null, q: "Que veut dire « quartier » ?", options: ["Country", "Village", "Neighbourhood", "Classroom"], correct: 2 },
      { diff: "easy", avatar: null, q: "Que veut dire « piéton » ?", options: ["Cyclist", "Pedestrian", "Driver", "Passenger"], correct: 1 },
      { diff: "easy", avatar: null, q: "Que veut dire « alimentation saine » ?", options: ["Waste disposal", "Healthy eating", "School work", "Fast transport"], correct: 1 },
      { diff: "easy", avatar: null, q: "Que veut dire « bien-être » ?", options: ["Traffic", "Homework", "Well-being", "Pollution"], correct: 2 },
      { diff: "easy", avatar: null, q: "Que veut dire « biodiversité » ?", options: ["Population", "Transport", "Electricity", "Biodiversity"], correct: 3 },
      { diff: "medium", avatar: null, q: "Que veut dire « courriel » ?", options: ["Newspaper", "Email", "Letterbox", "Television"], correct: 1 },
      { diff: "medium", avatar: null, q: "Que veut dire « se dépêcher » ?", options: ["To hurry", "To rest", "To forget", "To borrow"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « emprunter » ?", options: ["To buy", "To borrow", "To throw", "To lend"], correct: 1 },
      { diff: "medium", avatar: null, q: "Que veut dire « prêter » ?", options: ["To borrow", "To sell", "To lose", "To lend"], correct: 3 },
      { diff: "medium", avatar: null, q: "Que veut dire « réussir » ?", options: ["To fail", "To succeed", "To forget", "To refuse"], correct: 1 },
      { diff: "medium", avatar: null, q: "Que veut dire « échouer » ?", options: ["To fail", "To succeed", "To arrive", "To improve"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « se souvenir » ?", options: ["To remember", "To forget", "To wait", "To hurry"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « oublier » ?", options: ["To forget", "To understand", "To remember", "To answer"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « pourtant » ?", options: ["Yet/however", "Because", "Under", "Before"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « en revanche » ?", options: ["Always", "Tomorrow", "Below", "On the other hand"], correct: 3 },
      { diff: "hard", avatar: null, q: "Que veut dire « d’abord » ?", options: ["Finally", "Behind", "Never", "First"], correct: 3 },
      { diff: "hard", avatar: null, q: "Que veut dire « enfin » ?", options: ["First", "Near", "Often", "Finally"], correct: 3 },
      { diff: "hard", avatar: null, q: "Que veut dire « pendant que » ?", options: ["Without", "After", "While", "Because"], correct: 2 },
      { diff: "hard", avatar: null, q: "Que veut dire « dès que » ?", options: ["Under", "Although", "As soon as", "Never"], correct: 2 },
      { diff: "hard", avatar: null, q: "Que veut dire « en bonne santé » ?", options: ["In good health", "At school", "In a hurry", "In danger"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « faire attention » ?", options: ["To arrive", "To sell", "To fall asleep", "To be careful"], correct: 3 },
      { diff: "hard", avatar: null, q: "Que veut dire « protéger la nature » ?", options: ["Protect nature", "Waste water", "Increase pollution", "Cut every tree"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « actualités » ?", options: ["Homework", "Clothing", "News/current affairs", "Weather only"], correct: 2 },
      { diff: "hard", avatar: null, q: "Que veut dire « réseau social » ?", options: ["Social network", "Food market", "Road network", "School timetable"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « moyen de communication » ?", options: ["Sport", "School subject", "Means of communication", "Food group"], correct: 2 },
    ],
  },
  {
    slug: "media", name: "Media, Health & Environment", icon: "📰", color: "#B0568C",
    questions: [
      { diff: "easy", avatar: null, q: "Lequel est un moyen de communication ?", options: ["radio", "quartier", "médicament", "cyclisme"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est une habitude saine ?", options: ["manger seulement des bonbons", "ne jamais boire d’eau", "faire de l’exercice", "dormir très peu"], correct: 2 },
      { diff: "easy", avatar: null, q: "Lequel protège l’environnement ?", options: ["trier les déchets", "gaspiller l’eau", "brûler du plastique", "jeter dans la rue"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est lié à la sécurité routière ?", options: ["courriel", "biodiversité", "signalisation", "alimentation"], correct: 2 },
      { diff: "easy", avatar: null, q: "Lequel exprime une opposition ?", options: ["parce que", "d’abord", "ensuite", "pourtant"], correct: 3 },
      { diff: "medium", avatar: null, q: "Lequel exprime une succession ?", options: ["jamais", "malgré", "ensuite", "pourtant"], correct: 2 },
      { diff: "medium", avatar: null, q: "Lequel est au passé composé ?", options: ["nous mangerons", "nous allons manger", "nous avons mangé", "nous mangeons"], correct: 2 },
      { diff: "medium", avatar: null, q: "Lequel est au futur proche ?", options: ["je vais partir", "je partais", "je suis parti", "je pars"], correct: 0 },
      { diff: "medium", avatar: null, q: "Journal, radio et télévision sont des…", options: ["sports", "médias", "aliments", "métiers"], correct: 1 },
      { diff: "medium", avatar: null, q: "Ville, village et quartier sont des…", options: ["temps verbaux", "professions", "lieux de vie", "aliments"], correct: 2 },
      { diff: "medium", avatar: null, q: "Exercice et alimentation saine favorisent la…", options: ["santé", "circulation", "pollution", "technologie"], correct: 0 },
      { diff: "medium", avatar: null, q: "Recycler, réutiliser et réduire concernent les…", options: ["médias", "sports", "métiers", "déchets"], correct: 3 },
      { diff: "medium", avatar: null, q: "Emprunter et prêter décrivent un…", options: ["repas", "transport", "climat", "échange"], correct: 3 },
      { diff: "medium", avatar: null, q: "Réussir et échouer sont des…", options: ["contraires", "synonymes", "lieux", "médias"], correct: 0 },
      { diff: "medium", avatar: null, q: "Se souvenir et oublier sont des…", options: ["professions", "synonymes", "sports", "contraires"], correct: 3 },
      { diff: "hard", avatar: null, q: "Quel mot va avec 📧 ?", options: ["radio", "journal", "courriel", "télévision"], correct: 2 },
      { diff: "hard", avatar: null, q: "Quel mot va avec 🌿 ?", options: ["signalisation", "quartier", "médicament", "biodiversité"], correct: 3 },
      { diff: "hard", avatar: null, q: "Quel mot va avec 🚶 ?", options: ["cyclisme", "piéton", "transport public", "journal"], correct: 1 },
      { diff: "hard", avatar: null, q: "Pour rester en bonne santé, je dois…", options: ["dormir deux heures", "bien manger et faire de l’exercice", "éviter toute activité", "boire très peu"], correct: 1 },
      { diff: "hard", avatar: null, q: "Pour traverser une route, je dois…", options: ["ignorer les feux", "regarder des deux côtés", "marcher au milieu", "courir sans regarder"], correct: 1 },
      { diff: "hard", avatar: null, q: "Pour réduire les déchets, on peut…", options: ["brûler tous les déchets", "jeter partout", "acheter plus de jetable", "réutiliser des objets"], correct: 3 },
      { diff: "hard", avatar: null, q: "Pour vérifier une information, il vaut mieux…", options: ["ne lire que le titre", "croire toute publication", "partager sans vérifier", "consulter plusieurs sources fiables"], correct: 3 },
      { diff: "hard", avatar: null, q: "Un courriel formel doit être…", options: ["sans objet", "incompréhensible", "clair et poli", "insultant"], correct: 2 },
      { diff: "hard", avatar: null, q: "Un réseau social peut servir à…", options: ["cultiver directement", "communiquer et partager", "soigner une fracture", "mesurer la température"], correct: 1 },
      { diff: "hard", avatar: null, q: "La biodiversité désigne la variété des…", options: ["ordinateurs", "êtres vivants", "routes", "bâtiments"], correct: 1 },
    ],
  },
  {
    slug: "context", name: "Contextual Grammar & Comprehension", icon: "📖", color: "#3E9B7C",
    questions: [
      { diff: "easy", avatar: null, q: "Hier, nous ____ un documentaire.", options: ["regardons", "regardez", "allons regarder", "avons regardé"], correct: 3 },
      { diff: "easy", avatar: null, q: "Amina ____ au marché hier.", options: ["ira proche", "va", "est allée", "a allé"], correct: 2 },
      { diff: "easy", avatar: null, q: "Demain, je ____ visiter ma grand-mère.", options: ["étais", "ai", "vais", "suis"], correct: 2 },
      { diff: "easy", avatar: null, q: "Ce soir, mes amis ____ jouer au basket.", options: ["ont", "sont", "vont", "étaient"], correct: 2 },
      { diff: "easy", avatar: null, q: "Mon frère a 15 ans et moi 13; il est ____.", options: ["aussi jeune", "le plus petit", "moins âgé", "plus âgé"], correct: 3 },
      { diff: "medium", avatar: null, q: "Cette route est ____ dangereuse que l’ancienne.", options: ["la", "beaucoup", "très que", "moins"], correct: 3 },
      { diff: "medium", avatar: null, q: "J’ai vu Fatou et je ____ ai parlé.", options: ["lui", "les", "la", "le"], correct: 0 },
      { diff: "medium", avatar: null, q: "J’ai acheté les livres et je ____ ai lus.", options: ["la", "leur", "les", "lui"], correct: 2 },
      { diff: "medium", avatar: null, q: "Nous faisons de l’exercice ____ rester en forme.", options: ["pour", "pourtant", "derrière", "jamais"], correct: 0 },
      { diff: "medium", avatar: null, q: "Il pleuvait; ____, le match a continué.", options: ["pourtant", "parce que", "d’abord", "donc"], correct: 0 },
      { diff: "medium", avatar: null, q: "____, je me réveille; ensuite, je me prépare.", options: ["Jamais", "D’abord", "Pourtant", "Derrière"], correct: 1 },
      { diff: "medium", avatar: null, q: "Je finis mes devoirs; ____, je regarde la télévision.", options: ["ensuite", "sous", "pourtant", "hier"], correct: 0 },
      { diff: "medium", avatar: null, q: "____ tu arrives, appelle-moi.", options: ["Sous", "Jamais", "Malgré", "Dès que"], correct: 3 },
      { diff: "medium", avatar: null, q: "Je lis ____ ma sœur écoute la radio.", options: ["parce que", "derrière", "pendant que", "sans"], correct: 2 },
      { diff: "medium", avatar: null, q: "Pour réussir, tu dois ____ régulièrement.", options: ["abandonner", "oublier", "éviter", "étudier"], correct: 3 },
      { diff: "hard", avatar: null, q: "Pour éviter les fausses informations, il faut ____ la source.", options: ["ignorer", "cacher", "inventer", "vérifier"], correct: 3 },
      { diff: "hard", avatar: null, q: "Un piéton doit utiliser le passage ____.", options: ["numérique", "solaire", "médical", "piéton"], correct: 3 },
      { diff: "hard", avatar: null, q: "Une alimentation équilibrée contient différents groupes d’____.", options: ["médias", "routes", "aliments", "quartiers"], correct: 2 },
      { diff: "hard", avatar: null, q: "La biodiversité est importante ____ elle soutient les écosystèmes.", options: ["jamais", "derrière", "sous", "parce qu’"], correct: 3 },
      { diff: "hard", avatar: null, q: "Nous devons réduire le plastique à usage ____.", options: ["médical", "rapide", "unique", "scolaire"], correct: 2 },
      { diff: "hard", avatar: null, q: "Si aujourd’hui est mardi, dans trois jours ce sera ____.", options: ["mercredi", "jeudi", "samedi", "vendredi"], correct: 3 },
      { diff: "hard", avatar: null, q: "De 9 h 15 à 10 h 00, il y a ____ minutes.", options: ["30", "75", "60", "45"], correct: 3 },
      { diff: "hard", avatar: null, q: "« Je vais étudier » est au…", options: ["passé composé", "présent", "futur proche", "imparfait"], correct: 2 },
      { diff: "hard", avatar: null, q: "« Nous avons fini » est au…", options: ["infinitif", "passé composé", "présent", "futur proche"], correct: 1 },
      { diff: "hard", avatar: null, q: "Un courriel poli commence par une ____ appropriée.", options: ["insulte", "salutation", "publicité", "rumeur"], correct: 1 },
    ],
  },
  {
    slug: "dialogue", name: "Dialogue & Communication", icon: "🗣️", color: "#E0574C",
    questions: [
      { diff: "easy", avatar: null, q: "— Bonjour, comment vas-tu ? — ____", options: ["Je vais bien, merci.", "À la gare.", "Parce que oui.", "Quinze ans."], correct: 0 },
      { diff: "easy", avatar: null, q: "— Quel âge as-tu ? — ____", options: ["J’ai quatorze ans.", "Je vais bien.", "Je suis à Lagos.", "Il est midi."], correct: 0 },
      { diff: "easy", avatar: null, q: "— Où habites-tu ? — ____", options: ["Je suis élève.", "À huit heures.", "J’ai faim.", "J’habite à Kano."], correct: 3 },
      { diff: "easy", avatar: null, q: "— À quelle heure commence le cours ? — ____", options: ["Au collège.", "Parce que j’étudie.", "Avec mon ami.", "À huit heures."], correct: 3 },
      { diff: "easy", avatar: null, q: "— Pourquoi fais-tu du sport ? — ____", options: ["Deux fois.", "Au stade.", "Avec un ballon.", "Parce que c’est bon pour la santé."], correct: 3 },
      { diff: "medium", avatar: null, q: "— Comment vas-tu à l’école ? — ____", options: ["Je prends le bus.", "Le lundi.", "À sept heures.", "Au collège."], correct: 0 },
      { diff: "medium", avatar: null, q: "— Qu’as-tu fait hier ? — ____", options: ["Étudier.", "J’étudie demain.", "Je vais étudier.", "J’ai étudié."], correct: 3 },
      { diff: "medium", avatar: null, q: "— Que vas-tu faire demain ? — ____", options: ["J’ai révisé hier.", "Révisé.", "Je vais réviser.", "Je révisais."], correct: 2 },
      { diff: "medium", avatar: null, q: "Pour demander poliment un objet, on dit…", options: ["Puis-je l’emprunter, s’il vous plaît ?", "Va-t’en !", "Donne-moi ça !", "Je ne parle pas."], correct: 0 },
      { diff: "medium", avatar: null, q: "Pour remercier quelqu’un, on dit…", options: ["Combien ?", "À gauche.", "Merci beaucoup.", "Jamais."], correct: 2 },
      { diff: "medium", avatar: null, q: "Pour s’excuser, on dit…", options: ["Je suis treize ans.", "Il fait livre.", "Je vais marché.", "Je suis désolé(e)."], correct: 3 },
      { diff: "medium", avatar: null, q: "Pour accepter une invitation, on peut dire…", options: ["Combien coûte ?", "Où est-il ?", "Jamais de la vie.", "Avec plaisir !"], correct: 3 },
      { diff: "medium", avatar: null, q: "Pour refuser poliment, on peut dire…", options: ["Désolé, je ne peux pas.", "Non ! Pars !", "Je suis quinze.", "Donne-moi ça."], correct: 0 },
      { diff: "medium", avatar: null, q: "Pour demander un prix, on dit…", options: ["Qui est-ce ?", "Quel âge as-tu ?", "Combien ça coûte ?", "Où habites-tu ?"], correct: 2 },
      { diff: "medium", avatar: null, q: "Pour demander son chemin, on peut dire…", options: ["Quel âge a la gare ?", "Où se trouve la gare ?", "Combien de santé ?", "Pourquoi la gare mange ?"], correct: 1 },
      { diff: "hard", avatar: null, q: "« Tournez à gauche » donne une…", options: ["profession", "date", "opinion", "direction"], correct: 3 },
      { diff: "hard", avatar: null, q: "« Continuez tout droit » signifie…", options: ["s’arrêter définitivement", "aller sans tourner", "revenir en arrière", "tourner à droite"], correct: 1 },
      { diff: "hard", avatar: null, q: "« À mon avis » sert à introduire une…", options: ["opinion", "profession", "heure", "adresse"], correct: 0 },
      { diff: "hard", avatar: null, q: "« Je suis d’accord » exprime…", options: ["l’accord", "le passé", "le refus", "la direction"], correct: 0 },
      { diff: "hard", avatar: null, q: "« Je ne suis pas d’accord » exprime…", options: ["la salutation", "la gratitude", "l’accord", "le désaccord"], correct: 3 },
      { diff: "hard", avatar: null, q: "Pour conseiller un ami malade, on peut dire…", options: ["Ignore toujours la douleur.", "Tu dois courir sans repos.", "Tu devrais voir un médecin.", "Ne bois jamais d’eau."], correct: 2 },
      { diff: "hard", avatar: null, q: "Pour conseiller une action écologique, on peut dire…", options: ["Tu devrais recycler.", "Tu devrais gaspiller l’eau.", "Tu devrais jeter partout.", "Tu devrais brûler le plastique."], correct: 0 },
      { diff: "hard", avatar: null, q: "Une question commençant par « Où » demande généralement un…", options: ["âge", "lieu", "prix", "motif"], correct: 1 },
      { diff: "hard", avatar: null, q: "Une question commençant par « Pourquoi » demande généralement une…", options: ["adresse", "heure", "quantité", "raison"], correct: 3 },
      { diff: "hard", avatar: null, q: "Une question commençant par « Combien » demande généralement une…", options: ["direction", "quantité", "cause", "personne"], correct: 1 },
    ],
  },
]

export function jss2LangCategoryBySlug(slug: string): LangCategory | undefined {
  return JSS2_LANG.find((c) => c.slug === slug)
}
