// AUTO-GENERATED Primary 4 FRENCH LANGUAGE quiz — 150 questions, 6 categories.
// From Gabe's primary_4_french_language_quiz_150 doc.

import type { LangCategory } from './lang-p1'

export const P4_LANG: LangCategory[] = [
  {
    slug: "obj-word", name: "Picture → Word", icon: "🖼️", color: "#3E7CA6",
    questions: [
      { diff: "easy", avatar: "🥥", q: "Quel est le mot français pour cet objet ?", options: ["noix de coco", "soleil", "serpent", "plage"], correct: 0 },
      { diff: "easy", avatar: "🍋", q: "Quel est le mot français pour cet objet ?", options: ["citron", "livre", "montre", "chaussette"], correct: 0 },
      { diff: "easy", avatar: "🥒", q: "Quel est le mot français pour cet objet ?", options: ["concombre", "citron", "montre", "serpent"], correct: 0 },
      { diff: "easy", avatar: "🍆", q: "Quel est le mot français pour cet objet ?", options: ["aubergine", "noix de coco", "crocodile", "lac"], correct: 0 },
      { diff: "easy", avatar: "🫘", q: "Quel est le mot français pour cet objet ?", options: ["haricot", "assiette", "livre", "chaise"], correct: 0 },
      { diff: "easy", avatar: "🦁", q: "Quel est le mot français pour cet objet ?", options: ["lion", "cuillère", "brosse à dents", "haricot"], correct: 0 },
      { diff: "easy", avatar: "🐒", q: "Quel est le mot français pour cet objet ?", options: ["singe", "clé", "chaussette", "lac"], correct: 0 },
      { diff: "easy", avatar: "🐊", q: "Quel est le mot français pour cet objet ?", options: ["crocodile", "serpent", "haricot", "singe"], correct: 0 },
      { diff: "medium", avatar: "🐍", q: "Quel est le mot français pour cet objet ?", options: ["serpent", "robe", "cuillère", "singe"], correct: 0 },
      { diff: "medium", avatar: "🐢", q: "Quel est le mot français pour cet objet ?", options: ["tortue", "chaussette", "concombre", "brosse à dents"], correct: 0 },
      { diff: "medium", avatar: "🌲", q: "Quel est le mot français pour cet objet ?", options: ["forêt", "livre", "singe", "eau"], correct: 0 },
      { diff: "medium", avatar: "🏞️", q: "Quel est le mot français pour cet objet ?", options: ["lac", "eau", "feu", "serpent"], correct: 0 },
      { diff: "medium", avatar: "🏖️", q: "Quel est le mot français pour cet objet ?", options: ["plage", "casquette", "parapluie", "aubergine"], correct: 0 },
      { diff: "medium", avatar: "🔥", q: "Quel est le mot français pour cet objet ?", options: ["feu", "concombre", "école", "clé"], correct: 0 },
      { diff: "medium", avatar: "🌧️", q: "Quel est le mot français pour cet objet ?", options: ["orage", "savon", "eau", "jardin"], correct: 0 },
      { diff: "medium", avatar: "⌚", q: "Quel est le mot français pour cet objet ?", options: ["montre", "tortue", "orage", "eau"], correct: 0 },
      { diff: "medium", avatar: "☂️", q: "Quel est le mot français pour cet objet ?", options: ["parapluie", "jardin", "brosse à dents", "concombre"], correct: 0 },
      { diff: "medium", avatar: "🧢", q: "Quel est le mot français pour cet objet ?", options: ["casquette", "robe", "forêt", "noix de coco"], correct: 0 },
      { diff: "hard", avatar: "👗", q: "Quel est le mot français pour cet objet ?", options: ["robe", "orage", "noix de coco", "chaussette"], correct: 0 },
      { diff: "hard", avatar: "🧦", q: "Quel est le mot français pour cet objet ?", options: ["chaussette", "brosse à dents", "plage", "chaise"], correct: 0 },
      { diff: "hard", avatar: "🍽️", q: "Quel est le mot français pour cet objet ?", options: ["assiette", "crocodile", "savon", "clé"], correct: 0 },
      { diff: "hard", avatar: "🥄", q: "Quel est le mot français pour cet objet ?", options: ["cuillère", "crocodile", "orage", "aubergine"], correct: 0 },
      { diff: "hard", avatar: "🔑", q: "Quel est le mot français pour cet objet ?", options: ["clé", "école", "aubergine", "eau"], correct: 0 },
      { diff: "hard", avatar: "🪥", q: "Quel est le mot français pour cet objet ?", options: ["brosse à dents", "crocodile", "tortue", "lac"], correct: 0 },
      { diff: "hard", avatar: "🧼", q: "Quel est le mot français pour cet objet ?", options: ["savon", "noix de coco", "robe", "haricot"], correct: 0 },
    ],
  },
  {
    slug: "word-obj", name: "Word → Picture", icon: "🔤", color: "#5C9E3A",
    questions: [
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« noix de coco »** ?", options: ["🥥 Coconut", "🐢 Tortoise", "🍆 Eggplant", "🍋 Lemon"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« citron »** ?", options: ["🍋 Lemon", "🌧️ Storm", "🐢 Tortoise", "🐒 Monkey"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« concombre »** ?", options: ["🥒 Cucumber", "🪥 Toothbrush", "🧢 Cap", "🥄 Spoon"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« aubergine »** ?", options: ["🍆 Eggplant", "🔑 Key", "🐊 Crocodile", "🍋 Lemon"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« haricot »** ?", options: ["🫘 Bean", "🐢 Tortoise", "☂️ Umbrella", "🥒 Cucumber"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« lion »** ?", options: ["🦁 Lion", "🧢 Cap", "🍽️ Plate", "🏞️ Lake"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« singe »** ?", options: ["🐒 Monkey", "👗 Dress", "☂️ Umbrella", "🥒 Cucumber"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel avatar correspond au mot **« crocodile »** ?", options: ["🐊 Crocodile", "🌲 Forest", "☂️ Umbrella", "🔥 Fire"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« serpent »** ?", options: ["🐍 Snake", "🔥 Fire", "🌲 Forest", "👗 Dress"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« tortue »** ?", options: ["🐢 Tortoise", "⌚ Watch", "🥒 Cucumber", "🏞️ Lake"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« forêt »** ?", options: ["🌲 Forest", "🐍 Snake", "🫘 Bean", "🔑 Key"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« lac »** ?", options: ["🏞️ Lake", "🫘 Bean", "🥒 Cucumber", "⌚ Watch"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« plage »** ?", options: ["🏖️ Beach", "🔥 Fire", "🥄 Spoon", "🏞️ Lake"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« feu »** ?", options: ["🔥 Fire", "⌚ Watch", "🥒 Cucumber", "🐍 Snake"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« orage »** ?", options: ["🌧️ Storm", "🧦 Sock", "🫘 Bean", "🐍 Snake"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« montre »** ?", options: ["⌚ Watch", "🧼 Soap", "👗 Dress", "🧢 Cap"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« parapluie »** ?", options: ["☂️ Umbrella", "🏞️ Lake", "🐊 Crocodile", "🍋 Lemon"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel avatar correspond au mot **« casquette »** ?", options: ["🧢 Cap", "🪥 Toothbrush", "🐊 Crocodile", "👗 Dress"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« robe »** ?", options: ["👗 Dress", "⌚ Watch", "🥒 Cucumber", "☂️ Umbrella"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« chaussette »** ?", options: ["🧦 Sock", "🐍 Snake", "🔥 Fire", "🪥 Toothbrush"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« assiette »** ?", options: ["🍽️ Plate", "🫘 Bean", "🌧️ Storm", "🐍 Snake"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« cuillère »** ?", options: ["🥄 Spoon", "🫘 Bean", "🐊 Crocodile", "🧦 Sock"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« clé »** ?", options: ["🔑 Key", "🏞️ Lake", "☂️ Umbrella", "🍆 Eggplant"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« brosse à dents »** ?", options: ["🪥 Toothbrush", "🌲 Forest", "⌚ Watch", "🫘 Bean"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel avatar correspond au mot **« savon »** ?", options: ["🧼 Soap", "🥥 Coconut", "🥒 Cucumber", "🏖️ Beach"], correct: 0 },
    ],
  },
  {
    slug: "spelling", name: "Spelling", icon: "🔤", color: "#C8912E",
    questions: [
      { diff: "easy", avatar: null, q: "Complète : c□tron.", options: ["i", "e", "a", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : concombr□.", options: ["e", "a", "i", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : auberg□ne.", options: ["i", "e", "a", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : har□cot.", options: ["i", "e", "a", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : s□nge.", options: ["i", "e", "a", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : crocod□le.", options: ["i", "e", "a", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : serp□nt.", options: ["e", "a", "i", "o"], correct: 0 },
      { diff: "easy", avatar: null, q: "Complète : tort□e.", options: ["u", "a", "i", "o"], correct: 0 },
      { diff: "medium", avatar: null, q: "Complète : for□t.", options: ["ê", "é", "è", "e"], correct: 0 },
      { diff: "medium", avatar: null, q: "Complète : pl□ge.", options: ["a", "e", "i", "o"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["parapluie", "parapluit", "paraplui", "parapluye"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["casquette", "casquete", "cassquette", "casquète"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["chaussette", "chausete", "chaussète", "chaucette"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["cuillère", "cuillére", "cuillere", "cuillèrre"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["assiette", "asiette", "assiete", "assiètte"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["bibliothèque", "bibliotèque", "bibliothéque", "bibliotheque"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["hôpital", "hopital", "hôpittal", "hôpitel"], correct: 0 },
      { diff: "medium", avatar: null, q: "Choisis le mot bien écrit :", options: ["marché", "marchè", "marche", "marchée"], correct: 0 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["récréation", "recreation", "récrèation", "récréassion"], correct: 0 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["déjeuner", "dejeuner", "déjeûner", "déjeunner"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : él□phant.", options: ["é", "è", "ê", "e"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : pr□férer.", options: ["é", "è", "ê", "e"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : après-m□di.", options: ["i", "e", "a", "o"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : v□ndredi.", options: ["e", "a", "i", "o"], correct: 0 },
      { diff: "hard", avatar: null, q: "Complète : dim□nche.", options: ["a", "e", "i", "o"], correct: 0 },
    ],
  },
  {
    slug: "meaning", name: "Meaning", icon: "💬", color: "#E0574C",
    questions: [
      { diff: "easy", avatar: null, q: "Que veut dire « forêt » ?", options: ["Forest", "Lake", "Beach", "Road"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « lac » ?", options: ["Lake", "Forest", "River", "Mountain"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « plage » ?", options: ["Beach", "School", "Market", "Farm"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « montre » ?", options: ["Watch", "Umbrella", "Cap", "Key"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « parapluie » ?", options: ["Umbrella", "Watch", "Dress", "Sock"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « robe » ?", options: ["Dress", "Shirt", "Trousers", "Cap"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « assiette » ?", options: ["Plate", "Spoon", "Cup", "Knife"], correct: 0 },
      { diff: "easy", avatar: null, q: "Que veut dire « cuillère » ?", options: ["Spoon", "Plate", "Fork", "Cup"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « savon » ?", options: ["Soap", "Toothbrush", "Towel", "Water"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « bibliothèque » ?", options: ["Library", "Hospital", "Market", "School"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « hôpital » ?", options: ["Hospital", "Library", "Market", "Park"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « marché » ?", options: ["Market", "Hospital", "Classroom", "River"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « lundi » ?", options: ["Monday", "Tuesday", "Friday", "Sunday"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « vendredi » ?", options: ["Friday", "Monday", "Saturday", "Wednesday"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « dimanche » ?", options: ["Sunday", "Friday", "Tuesday", "Thursday"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « déjeuner » ?", options: ["To have lunch", "To sleep", "To swim", "To read"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « nager » ?", options: ["To swim", "To run", "To write", "To cook"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que veut dire « acheter » ?", options: ["To buy", "To sell", "To sleep", "To sing"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « vendre » ?", options: ["To sell", "To buy", "To read", "To wash"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « propre » ?", options: ["Clean", "Dirty", "Fast", "Heavy"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « sale » ?", options: ["Dirty", "Clean", "Young", "Short"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « rapide » ?", options: ["Fast", "Slow", "Clean", "Old"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « lent » ?", options: ["Slow", "Fast", "Dirty", "Strong"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « toujours » ?", options: ["Always", "Never", "Sometimes", "Yesterday"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que veut dire « jamais » ?", options: ["Never", "Always", "Often", "Today"], correct: 0 },
    ],
  },
  {
    slug: "matching", name: "Matching", icon: "🔗", color: "#7A7488",
    questions: [
      { diff: "easy", avatar: null, q: "Lequel est un lieu public ?", options: ["hôpital", "savon", "lion", "citron"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un vêtement ?", options: ["robe", "lac", "haricot", "clé"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un ustensile de cuisine ?", options: ["cuillère", "parapluie", "serpent", "montre"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel sert à l’hygiène ?", options: ["savon", "lion", "plage", "robe"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un jour de la semaine ?", options: ["vendredi", "déjeuner", "forêt", "rapide"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est une action ?", options: ["nager", "propre", "lac", "tortue"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un adjectif ?", options: ["rapide", "marché", "acheter", "savon"], correct: 0 },
      { diff: "easy", avatar: null, q: "Lequel est un animal sauvage ?", options: ["lion", "haricot", "robe", "cuillère"], correct: 0 },
      { diff: "medium", avatar: null, q: "Bibliothèque et hôpital sont des…", options: ["lieux", "animaux", "vêtements", "aliments"], correct: 0 },
      { diff: "medium", avatar: null, q: "Robe et casquette sont des…", options: ["vêtements", "lieux", "actions", "animaux"], correct: 0 },
      { diff: "medium", avatar: null, q: "Assiette et cuillère sont dans la…", options: ["cuisine", "forêt", "classe", "rivière"], correct: 0 },
      { diff: "medium", avatar: null, q: "Savon et brosse à dents servent à l’…", options: ["hygiène", "transport", "lecture", "météo"], correct: 0 },
      { diff: "medium", avatar: null, q: "Lundi et dimanche sont des…", options: ["jours", "mois", "saisons", "heures"], correct: 0 },
      { diff: "medium", avatar: null, q: "Acheter et vendre sont des…", options: ["actions", "couleurs", "animaux", "lieux"], correct: 0 },
      { diff: "medium", avatar: null, q: "Propre et sale sont des…", options: ["contraires", "fruits", "jours", "personnes"], correct: 0 },
      { diff: "medium", avatar: null, q: "Rapide et lent sont des…", options: ["contraires", "vêtements", "lieux", "boissons"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel mot va avec ☂️ ?", options: ["parapluie", "montre", "casquette", "savon"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel mot va avec 🍽️ ?", options: ["assiette", "cuillère", "clé", "robe"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot va avec 🐢 ?", options: ["tortue", "lion", "serpent", "singe"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot va avec 🏖️ ?", options: ["plage", "forêt", "lac", "marché"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour emprunter un livre, je vais à la…", options: ["bibliothèque", "plage", "forêt", "cuisine"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quand je suis malade, je vais à l’…", options: ["hôpital", "marché", "lac", "bibliothèque"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour acheter des légumes, je vais au…", options: ["marché", "hôpital", "lac", "lit"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quand il pleut, j’utilise un…", options: ["parapluie", "savon", "livre", "lit"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour connaître l’heure, je regarde ma…", options: ["montre", "robe", "assiette", "clé"], correct: 0 },
    ],
  },
  {
    slug: "context", name: "Context", icon: "📖", color: "#3E9B7C",
    questions: [
      { diff: "easy", avatar: null, q: "Le lundi, je ____ à l’école.", options: ["vais", "mange", "dors", "nage"], correct: 0 },
      { diff: "easy", avatar: null, q: "Nous ____ des livres à la bibliothèque.", options: ["lisons", "buvons", "dormons", "courons"], correct: 0 },
      { diff: "easy", avatar: null, q: "Elle ____ des légumes au marché.", options: ["achète", "nage", "lit", "dort"], correct: 0 },
      { diff: "easy", avatar: null, q: "Le vendeur ____ des fruits.", options: ["vend", "nage", "dort", "écrit"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quand il pleut, je prends mon ____.", options: ["parapluie", "savon", "lit", "lion"], correct: 0 },
      { diff: "easy", avatar: null, q: "Je me lave les mains avec du ____.", options: ["savon", "citron", "livre", "riz"], correct: 0 },
      { diff: "easy", avatar: null, q: "Je me brosse les dents avec une ____.", options: ["brosse à dents", "cuillère", "montre", "robe"], correct: 0 },
      { diff: "easy", avatar: null, q: "Pour manger la soupe, j’utilise une ____.", options: ["cuillère", "clé", "montre", "chaussette"], correct: 0 },
      { diff: "medium", avatar: null, q: "Le lion est un animal ____.", options: ["sauvage", "scolaire", "propre", "lundi"], correct: 0 },
      { diff: "medium", avatar: null, q: "Une tortue est généralement ____.", options: ["lente", "rapide", "sale", "grande"], correct: 0 },
      { diff: "medium", avatar: null, q: "Une voiture est généralement plus ____ qu’une tortue.", options: ["rapide", "lente", "propre", "petite"], correct: 0 },
      { diff: "medium", avatar: null, q: "Après samedi vient ____.", options: ["dimanche", "vendredi", "lundi", "jeudi"], correct: 0 },
      { diff: "medium", avatar: null, q: "Avant mardi vient ____.", options: ["lundi", "mercredi", "vendredi", "dimanche"], correct: 0 },
      { diff: "medium", avatar: null, q: "Je déjeune vers le milieu de la ____.", options: ["journée", "semaine", "année", "nuit"], correct: 0 },
      { diff: "medium", avatar: null, q: "La bibliothèque est un lieu où l’on peut ____.", options: ["lire", "nager", "dormir", "conduire"], correct: 0 },
      { diff: "medium", avatar: null, q: "À l’hôpital, le médecin aide les personnes ____.", options: ["malades", "rapides", "jaunes", "petites"], correct: 0 },
      { diff: "medium", avatar: null, q: "Au marché, on peut ____ des aliments.", options: ["acheter", "nager", "dormir", "voler"], correct: 0 },
      { diff: "medium", avatar: null, q: "Je mets une casquette sur ma ____.", options: ["tête", "main", "jambe", "bouche"], correct: 0 },
      { diff: "hard", avatar: null, q: "Je porte des chaussettes aux ____.", options: ["pieds", "mains", "oreilles", "yeux"], correct: 0 },
      { diff: "hard", avatar: null, q: "L’eau du lac est importante pour les ____.", options: ["êtres vivants", "livres", "montres", "chaises"], correct: 0 },
      { diff: "hard", avatar: null, q: "Il y a ____ jours dans une semaine.", options: ["sept", "cinq", "dix", "douze"], correct: 0 },
      { diff: "hard", avatar: null, q: "Il y a ____ mois dans une année.", options: ["douze", "sept", "dix", "vingt"], correct: 0 },
      { diff: "hard", avatar: null, q: "Si aujourd’hui est lundi, demain est ____.", options: ["mardi", "dimanche", "vendredi", "mercredi"], correct: 0 },
      { diff: "hard", avatar: null, q: "Je dis « s’il vous plaît » pour être ____.", options: ["poli", "sale", "lent", "malade"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour rester propre, je me ____ chaque jour.", options: ["lave", "vends", "nage", "achète"], correct: 0 },
    ],
  },
]

export function p4LangCategoryBySlug(slug: string): LangCategory | undefined {
  return P4_LANG.find((c) => c.slug === slug)
}
