// AUTO-GENERATED JSS 3 FRENCH LANGUAGE quiz — 150 questions, 6 categories.

import type { LangCategory } from './lang-p1'

export const JSS3_LANG: LangCategory[] = [
  {
    slug: "obj-word", name: "Visual Vocabulary", icon: "🖼️", color: "#3E7CA6",
    questions: [
      { diff: "easy", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["mécanicien", "communication", "tri des déchets", "changement climatique"], correct: 3 },
      { diff: "easy", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["informaticien", "réchauffement climatique", "industrie", "technologie numérique"], correct: 1 },
      { diff: "easy", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["reboisement", "agriculture", "chercheur", "sécurité en ligne"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["citoyenneté", "entreprise", "enseignant", "énergie renouvelable"], correct: 3 },
      { diff: "easy", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["conservation de l’eau", "emploi", "coopération", "presse"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["profession médicale", "réseaux sociaux", "tri des déchets", "justice"], correct: 2 },
      { diff: "medium", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["communication", "mécanicien", "service public", "industrie"], correct: 3 },
      { diff: "medium", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["sécurité routière", "technologie numérique", "agriculture", "informaticien"], correct: 2 },
      { diff: "medium", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["sécurité en ligne", "chercheur", "entreprise", "changement climatique"], correct: 2 },
      { diff: "medium", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["enseignant", "emploi", "réchauffement climatique", "citoyenneté"], correct: 1 },
      { diff: "medium", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["presse", "coopération", "profession médicale", "reboisement"], correct: 2 },
      { diff: "medium", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["réseaux sociaux", "justice", "énergie renouvelable", "mécanicien"], correct: 3 },
      { diff: "medium", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["informaticien", "service public", "conservation de l’eau", "communication"], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["technologie numérique", "tri des déchets", "sécurité routière", "chercheur"], correct: 3 },
      { diff: "medium", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["changement climatique", "sécurité en ligne", "industrie", "enseignant"], correct: 3 },
      { diff: "hard", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["presse", "agriculture", "citoyenneté", "réchauffement climatique"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["entreprise", "reboisement", "réseaux sociaux", "coopération"], correct: 2 },
      { diff: "hard", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["emploi", "justice", "communication", "énergie renouvelable"], correct: 2 },
      { diff: "hard", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["service public", "technologie numérique", "profession médicale", "conservation de l’eau"], correct: 1 },
      { diff: "hard", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["sécurité routière", "mécanicien", "tri des déchets", "sécurité en ligne"], correct: 3 },
      { diff: "hard", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["citoyenneté", "informaticien", "changement climatique", "industrie"], correct: 0 },
      { diff: "hard", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["agriculture", "réchauffement climatique", "coopération", "chercheur"], correct: 2 },
      { diff: "hard", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["reboisement", "justice", "entreprise", "enseignant"], correct: 1 },
      { diff: "hard", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["énergie renouvelable", "presse", "service public", "emploi"], correct: 2 },
      { diff: "hard", avatar: null, q: "Quel mot ou groupe de mots français correspond le mieux à cette image ?", options: ["sécurité routière", "réseaux sociaux", "profession médicale", "conservation de l’eau"], correct: 0 },
    ],
  },
  {
    slug: "grammar", name: "Grammar — Tenses & Pronouns", icon: "✍️", color: "#5C9E3A",
    questions: [
      { diff: "easy", avatar: null, q: "Complète : Hier, nous ____ le musée.", options: ["visiterons proche", "visitons", "allons visiter", "avons visité"], correct: 3 },
      { diff: "easy", avatar: null, q: "Complète : Aïcha ____ tôt ce matin.", options: ["a arrivée", "est arrivée", "arrive", "est arriver"], correct: 1 },
      { diff: "easy", avatar: null, q: "Complète : Les garçons ____ au stade hier.", options: ["vont", "sont allé", "sont allés", "ont allé"], correct: 2 },
      { diff: "easy", avatar: null, q: "Complète : Demain, je ____ mes grands-parents.", options: ["visitais", "ai visité", "visite hier", "visiterai"], correct: 3 },
      { diff: "easy", avatar: null, q: "Complète : Nous ____ nos examens la semaine prochaine.", options: ["passer", "passions", "passerons", "avons passé hier"], correct: 2 },
      { diff: "medium", avatar: null, q: "Quand j’étais petit, je ____ souvent au football.", options: ["jouais", "ai joué demain", "joue demain", "jouerai hier"], correct: 0 },
      { diff: "medium", avatar: null, q: "Autrefois, ma famille ____ au village.", options: ["habite demain", "habitait", "habitera hier", "a habiter"], correct: 1 },
      { diff: "medium", avatar: null, q: "Si j’ai le temps, je ____ mes devoirs.", options: ["finissais hier", "fini", "finir", "finirai"], correct: 3 },
      { diff: "medium", avatar: null, q: "Il faut que nous ____ l’environnement.", options: ["protégé", "protégeons de", "protégions", "protégerons que"], correct: 2 },
      { diff: "medium", avatar: null, q: "Je veux ____ mes études.", options: ["continuer", "continue", "continues", "continué"], correct: 0 },
      { diff: "medium", avatar: null, q: "Il ____ travailler davantage pour réussir.", options: ["doit", "devez", "dois", "devons"], correct: 0 },
      { diff: "medium", avatar: null, q: "Nous ____ respecter le règlement.", options: ["doit", "devez", "dois", "devons"], correct: 3 },
      { diff: "medium", avatar: null, q: "Je connais la fille ____ parle au professeur.", options: ["dont", "qui", "où", "que"], correct: 1 },
      { diff: "medium", avatar: null, q: "Voici le livre ____ j’ai acheté.", options: ["où", "que", "dont", "qui"], correct: 1 },
      { diff: "medium", avatar: null, q: "C’est la ville ____ je suis né.", options: ["qui", "dont", "où", "que"], correct: 2 },
      { diff: "hard", avatar: null, q: "Le garçon ____ père est médecin est mon ami.", options: ["que", "dont", "où", "qui"], correct: 1 },
      { diff: "hard", avatar: null, q: "Je donne les cahiers aux élèves. Je ____ donne les cahiers.", options: ["lui", "la", "les", "leur"], correct: 3 },
      { diff: "hard", avatar: null, q: "J’achète les fruits. Je ____ achète.", options: ["leur", "lui", "en", "les"], correct: 3 },
      { diff: "hard", avatar: null, q: "Tu veux du pain ? Oui, j’____ veux.", options: ["lui", "y", "le", "en"], correct: 3 },
      { diff: "hard", avatar: null, q: "Tu vas à la bibliothèque ? Oui, j’____ vais.", options: ["en", "leur", "y", "la"], correct: 2 },
      { diff: "hard", avatar: null, q: "Choisis la forme correcte : Elles se sont ____ tôt.", options: ["levés", "levées", "levé", "lever"], correct: 1 },
      { diff: "hard", avatar: null, q: "Choisis la forme correcte : Marie est ____ que sa sœur.", options: ["la plus grand", "grande plus", "plus grande", "plus grand"], correct: 2 },
      { diff: "hard", avatar: null, q: "C’est ____ film que j’ai vu cette année.", options: ["plus meilleur", "le mieux film", "le meilleur", "meilleur que"], correct: 2 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["responsabilité", "résponsabilité", "responsabilitté", "responsabilitée"], correct: 0 },
      { diff: "hard", avatar: null, q: "Choisis le mot bien écrit :", options: ["developpement durable", "dévelopement durable", "développement durabble", "développement durable"], correct: 3 },
    ],
  },
  {
    slug: "vocab", name: "Vocabulary & Functional French", icon: "💬", color: "#C8912E",
    questions: [
      { diff: "easy", avatar: null, q: "Que signifie « changement climatique » ?", options: ["Public transport", "Road safety", "Climate change", "School timetable"], correct: 2 },
      { diff: "easy", avatar: null, q: "Que signifie « développement durable » ?", options: ["School examination", "Sustainable development", "Rapid shopping", "Private transport"], correct: 1 },
      { diff: "easy", avatar: null, q: "Que signifie « reboisement » ?", options: ["Construction", "Reforestation", "Irrigation", "Deforestation"], correct: 1 },
      { diff: "easy", avatar: null, q: "Que signifie « gaspillage » ?", options: ["Justice", "Employment", "Waste/wastage", "Saving"], correct: 2 },
      { diff: "easy", avatar: null, q: "Que signifie « citoyenneté » ?", options: ["Weather", "Technology", "Agriculture", "Citizenship"], correct: 3 },
      { diff: "medium", avatar: null, q: "Que signifie « droits » ?", options: ["Duties only", "Rights", "Directions", "Prices"], correct: 1 },
      { diff: "medium", avatar: null, q: "Que signifie « devoirs » dans le contexte civique ?", options: ["Duties/responsibilities", "Homework only", "Holidays", "Salaries"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que signifie « emploi » ?", options: ["Journey", "Employment/job", "News", "Pollution"], correct: 1 },
      { diff: "medium", avatar: null, q: "Que signifie « chômage » ?", options: ["Employment", "Health", "Education", "Unemployment"], correct: 3 },
      { diff: "medium", avatar: null, q: "Que signifie « entretien d’embauche » ?", options: ["School lesson", "Job interview", "Football match", "Medical operation"], correct: 1 },
      { diff: "medium", avatar: null, q: "Que signifie « compétences » ?", options: ["Skills", "Buildings", "Meals", "Vehicles"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que signifie « candidature » ?", options: ["Application/candidacy", "Pollution", "Agriculture", "Weather"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que signifie « actualités » ?", options: ["News/current affairs", "Homework", "Clothes", "Food"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que signifie « source fiable » ?", options: ["Reliable source", "False rumour", "Advertisement only", "Unknown password"], correct: 0 },
      { diff: "medium", avatar: null, q: "Que signifie « vie privée » ?", options: ["Public road", "Employment", "Weather", "Privacy/private life"], correct: 3 },
      { diff: "hard", avatar: null, q: "Que signifie « mot de passe » ?", options: ["Username only", "Telephone call", "Newspaper", "Password"], correct: 3 },
      { diff: "hard", avatar: null, q: "Que signifie « se renseigner » ?", options: ["To get lost", "To resign", "To waste", "To get information"], correct: 3 },
      { diff: "hard", avatar: null, q: "Que signifie « postuler » ?", options: ["To travel", "To harvest", "To apply for a position", "To pollute"], correct: 2 },
      { diff: "hard", avatar: null, q: "Que signifie « économiser » ?", options: ["To borrow", "To waste", "To save/conserve", "To destroy"], correct: 2 },
      { diff: "hard", avatar: null, q: "Que signifie « sensibiliser » ?", options: ["To raise awareness", "To pollute", "To hide information", "To forget"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que signifie « malgré » ?", options: ["Under", "Before", "Because", "Despite"], correct: 3 },
      { diff: "hard", avatar: null, q: "Que signifie « tandis que » ?", options: ["Whereas/while", "Therefore", "Never", "Below"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que signifie « grâce à » ?", options: ["Despite", "Without", "Thanks to/because of a positive cause", "Behind"], correct: 2 },
      { diff: "hard", avatar: null, q: "Que signifie « à cause de » ?", options: ["Because of", "Before", "In order to", "Next to"], correct: 0 },
      { diff: "hard", avatar: null, q: "Que signifie « en conclusion » ?", options: ["Under", "At first", "In conclusion", "Yesterday"], correct: 2 },
    ],
  },
  {
    slug: "reading", name: "Reading, Reasoning & Functions", icon: "📖", color: "#B0568C",
    questions: [
      { diff: "easy", avatar: null, q: "« Mariam recycle ses bouteilles pour réduire les déchets. » Pourquoi recycle-t-elle ?", options: ["Pour réduire les déchets", "Pour manquer l’école", "Pour acheter une voiture", "Pour augmenter la pollution"], correct: 0 },
      { diff: "easy", avatar: null, q: "« Le bus est en retard à cause de la pluie. » Quelle est la cause du retard ?", options: ["L’école", "Le billet", "La pluie", "Le chauffeur uniquement"], correct: 2 },
      { diff: "easy", avatar: null, q: "« Grâce à Internet, les élèves trouvent rapidement des informations. » Quel est l’avantage mentionné ?", options: ["Trouver rapidement des informations", "Créer des déchets", "Fermer l’école", "Éviter toute étude"], correct: 0 },
      { diff: "easy", avatar: null, q: "« Malgré la chaleur, ils ont continué à travailler. » Ont-ils arrêté ?", options: ["On ne sait pas", "Oui", "Non", "Seulement le matin"], correct: 2 },
      { diff: "easy", avatar: null, q: "« Fatou veut devenir médecin; elle étudie donc les sciences. » Pourquoi étudie-t-elle les sciences ?", options: ["Pour devenir chauffeur", "Pour éviter l’école", "Pour vendre des vêtements", "Pour préparer son projet professionnel"], correct: 3 },
      { diff: "medium", avatar: null, q: "« Le village manque d’eau potable. » Quel problème est présenté ?", options: ["La télévision", "Le transport", "Le manque d’eau potable", "Le chômage seulement"], correct: 2 },
      { diff: "medium", avatar: null, q: "« Les jeunes ont planté cent arbres. » Quelle action ont-ils menée ?", options: ["Un voyage", "Une grève", "Un reboisement", "Une pollution"], correct: 2 },
      { diff: "medium", avatar: null, q: "« Le journaliste vérifie ses sources avant de publier. » Que fait-il avant de publier ?", options: ["Il vérifie ses sources", "Il achète une voiture", "Il invente une histoire", "Il efface Internet"], correct: 0 },
      { diff: "medium", avatar: null, q: "« Amina utilise un mot de passe difficile. » Quel comportement adopte-t-elle ?", options: ["Elle ferme l’école", "Elle protège son compte", "Elle pollue", "Elle partage son compte"], correct: 1 },
      { diff: "medium", avatar: null, q: "« Les élèves utilisent moins de plastique. » Quel résultat est probable ?", options: ["Plus de pollution plastique", "Moins d’éducation", "Moins de déchets plastiques", "Plus de gaspillage"], correct: 2 },
      { diff: "medium", avatar: null, q: "Quel énoncé exprime une opinion ?", options: ["À mon avis, le vélo est pratique.", "Le cours commence à huit heures.", "L’eau bout à 100 °C au niveau de la mer.", "Le livre est sur la table."], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel énoncé exprime une cause ?", options: ["Le livre est rouge.", "Je vais au marché demain.", "Elle habite ici.", "Le match est annulé à cause de la pluie."], correct: 3 },
      { diff: "medium", avatar: null, q: "Quel énoncé exprime un but ?", options: ["Il pleut.", "Je suis grand.", "J’ai étudié hier.", "J’étudie pour réussir l’examen."], correct: 3 },
      { diff: "medium", avatar: null, q: "Quel énoncé exprime une opposition ?", options: ["Il est fatigué, mais il continue.", "Il mange parce qu’il a faim.", "Il part donc il ferme la porte.", "Il vient demain."], correct: 0 },
      { diff: "medium", avatar: null, q: "Quel énoncé exprime une conséquence ?", options: ["Malgré la pluie, il sort.", "Il travaille pour réussir.", "Avant de partir, il mange.", "Il a beaucoup travaillé, donc il a réussi."], correct: 3 },
      { diff: "hard", avatar: null, q: "Une source fiable doit généralement être…", options: ["toujours virale", "anonyme et impossible à vérifier", "vérifiable et crédible", "basée uniquement sur une rumeur"], correct: 2 },
      { diff: "hard", avatar: null, q: "Avant de partager une actualité en ligne, il faut…", options: ["la partager immédiatement", "modifier le titre", "ignorer la source", "vérifier l’information"], correct: 3 },
      { diff: "hard", avatar: null, q: "Un citoyen responsable doit…", options: ["détruire les biens publics", "respecter les droits des autres", "ignorer les règles", "répandre de fausses informations"], correct: 1 },
      { diff: "hard", avatar: null, q: "Pour réduire la consommation d’énergie, on peut…", options: ["ouvrir le réfrigérateur longtemps", "éteindre les appareils inutilisés", "laisser toutes les lampes allumées", "gaspiller l’électricité"], correct: 1 },
      { diff: "hard", avatar: null, q: "Pour protéger son compte en ligne, il vaut mieux…", options: ["utiliser toujours 1234", "utiliser un mot de passe fort", "partager ses codes", "publier son mot de passe"], correct: 1 },
      { diff: "hard", avatar: null, q: "Un CV sert principalement à…", options: ["faire une recette", "mesurer la température", "acheter un billet", "présenter sa formation et ses compétences"], correct: 3 },
      { diff: "hard", avatar: null, q: "Lors d’un entretien, il est préférable de…", options: ["refuser toute question", "insulter l’employeur", "arriver sans préparation", "répondre clairement et poliment"], correct: 3 },
      { diff: "hard", avatar: null, q: "« D’abord…, ensuite…, enfin… » sert à…", options: ["indiquer un prix", "former un pluriel", "organiser une séquence", "exprimer seulement une couleur"], correct: 2 },
      { diff: "hard", avatar: null, q: "« Plus… que » sert à exprimer…", options: ["une négation", "une comparaison", "une profession", "une salutation"], correct: 1 },
      { diff: "hard", avatar: null, q: "« Parce que » introduit généralement…", options: ["un prix", "une cause ou une explication", "un lieu", "une personne"], correct: 1 },
    ],
  },
  {
    slug: "dialogue", name: "Dialogue, Opinion & Communication", icon: "🗣️", color: "#3E9B7C",
    questions: [
      { diff: "easy", avatar: null, q: "— Quel métier veux-tu faire ? — ____", options: ["J’ai quinze ans.", "Au marché.", "À huit heures.", "Je veux devenir ingénieur."], correct: 3 },
      { diff: "easy", avatar: null, q: "— Pourquoi veux-tu apprendre le français ? — ____", options: ["Demain matin.", "Trois fois.", "Parce que je veux communiquer avec plus de personnes.", "À la bibliothèque."], correct: 2 },
      { diff: "easy", avatar: null, q: "— Qu’as-tu fait pendant les vacances ? — ____", options: ["À la famille.", "Je rends visite demain hier.", "J’ai rendu visite à ma famille.", "Je vais rendre visite demain."], correct: 2 },
      { diff: "easy", avatar: null, q: "— Que feras-tu demain ? — ____", options: ["J’ai révisé hier.", "Je révisais autrefois.", "Je réviserai mes leçons.", "Réviser hier."], correct: 2 },
      { diff: "easy", avatar: null, q: "— Où aimerais-tu travailler ? — ____", options: ["Parce qu’il pleut.", "À neuf heures.", "J’ai seize ans.", "J’aimerais travailler dans un hôpital."], correct: 3 },
      { diff: "medium", avatar: null, q: "Pour demander l’avis de quelqu’un :", options: ["Quel âge as-tu ?", "Où est la gare ?", "Combien coûte-t-il ?", "Qu’en penses-tu ?"], correct: 3 },
      { diff: "medium", avatar: null, q: "Pour donner son opinion :", options: ["À mon avis, c’est une bonne idée.", "J’ai un cahier.", "Il est trois heures.", "Je m’appelle Musa."], correct: 0 },
      { diff: "medium", avatar: null, q: "Pour être d’accord :", options: ["Où allez-vous ?", "Il pleut hier.", "Je suis tout à fait d’accord.", "Je ne comprends jamais."], correct: 2 },
      { diff: "medium", avatar: null, q: "Pour exprimer un désaccord poli :", options: ["Je comprends, mais je ne partage pas cet avis.", "C’est faux, tais-toi !", "Donne-moi ça.", "Je pars hier."], correct: 0 },
      { diff: "medium", avatar: null, q: "Pour proposer une solution :", options: ["Nous pourrions recycler davantage.", "Nous avons recyclé demain.", "Où est recycler ?", "Recycler est bleu."], correct: 0 },
      { diff: "medium", avatar: null, q: "Pour demander de l’aide poliment :", options: ["Pourquoi tu es ?", "Pourriez-vous m’aider, s’il vous plaît ?", "Aide-moi maintenant !", "Combien aide ?"], correct: 1 },
      { diff: "medium", avatar: null, q: "Pour demander une permission :", options: ["Est-ce que je peux entrer ?", "Entre demain hier.", "Je suis entré hier.", "Pourquoi entrer coûte ?"], correct: 0 },
      { diff: "medium", avatar: null, q: "Pour conseiller :", options: ["Tu étudies hier demain.", "Je suis étude.", "Étudier est une ville.", "Tu devrais étudier davantage."], correct: 3 },
      { diff: "medium", avatar: null, q: "Pour exprimer une obligation :", options: ["Il peut-être les règles.", "Les règles sont hier.", "Il faut respecter les règles.", "Je règle demain."], correct: 2 },
      { diff: "medium", avatar: null, q: "Pour exprimer une possibilité :", options: ["Le solaire est hier.", "On doit toujours impossible.", "Je suis solaire.", "On peut utiliser l’énergie solaire."], correct: 3 },
      { diff: "hard", avatar: null, q: "— Depuis combien de temps apprends-tu le français ? — ____", options: ["Trois livres.", "Parce que trois.", "À trois heures.", "Depuis trois ans."], correct: 3 },
      { diff: "hard", avatar: null, q: "— À quelle fréquence lis-tu en français ? — ____", options: ["Parce que je lis.", "À la bibliothèque rouge.", "Avec mon professeur hier.", "Deux fois par semaine."], correct: 3 },
      { diff: "hard", avatar: null, q: "— Quel est ton point de vue sur le recyclage ? — ____", options: ["Au marché.", "À cinq heures.", "Je pense que c’est important.", "J’ai quatorze ans."], correct: 2 },
      { diff: "hard", avatar: null, q: "— Comment peut-on économiser l’eau ? — ____", options: ["On peut polluer la rivière.", "On peut laisser couler l’eau.", "On peut gaspiller davantage.", "On peut fermer le robinet."], correct: 3 },
      { diff: "hard", avatar: null, q: "— Que faut-il faire avant de partager une information ? — ____", options: ["Il faut inventer un titre.", "Il faut tout partager.", "Il faut vérifier la source.", "Il faut ignorer l’auteur."], correct: 2 },
      { diff: "hard", avatar: null, q: "— Excusez-moi, où se trouve la gare ? — ____", options: ["J’ai quinze ans.", "Elle coûte dix euros.", "Parce que je voyage.", "Continuez tout droit puis tournez à gauche."], correct: 3 },
      { diff: "hard", avatar: null, q: "— Pourriez-vous répéter, s’il vous plaît ? — Cette phrase exprime…", options: ["une insulte", "une profession", "une comparaison", "une demande polie"], correct: 3 },
      { diff: "hard", avatar: null, q: "— Félicitations pour ta réussite ! — ____", options: ["Jamais.", "À droite.", "Merci beaucoup !", "Il pleut."], correct: 2 },
      { diff: "hard", avatar: null, q: "— Je suis désolé pour le retard. — ____", options: ["Au revoir hier.", "Ce n’est pas grave.", "Je suis quinze.", "Combien coûte ?"], correct: 1 },
      { diff: "hard", avatar: null, q: "— Bonne chance pour l’examen ! — ____", options: ["À la gare.", "Merci, c’est gentil.", "Il est midi.", "Parce que non."], correct: 1 },
    ],
  },
  {
    slug: "integrated", name: "Integrated Grammar & Civic Literacy", icon: "🏛️", color: "#E0574C",
    questions: [
      { diff: "easy", avatar: null, q: "Si nous plantons plus d’arbres, nous ____ l’environnement.", options: ["protégerons", "protégions hier", "protéger", "avons protéger"], correct: 0 },
      { diff: "easy", avatar: null, q: "Quand j’étais en Primary 6, je ____ moins bien français.", options: ["parlais", "parle demain", "parlerai hier", "ai parler"], correct: 0 },
      { diff: "easy", avatar: null, q: "Hier, les élèves ____ une campagne de nettoyage.", options: ["vont organiser hier", "organisé", "organisent demain", "ont organisé"], correct: 3 },
      { diff: "easy", avatar: null, q: "L’année prochaine, nous ____ au lycée.", options: ["entrions hier", "entrer", "sommes entré demain", "entrerons"], correct: 3 },
      { diff: "easy", avatar: null, q: "Je cherche un métier ____ correspond à mes compétences.", options: ["où", "que", "dont", "qui"], correct: 3 },
      { diff: "medium", avatar: null, q: "Le projet ____ nous avons présenté concerne l’eau.", options: ["que", "dont", "qui", "où"], correct: 0 },
      { diff: "medium", avatar: null, q: "Voici l’école ____ ma mère travaille.", options: ["dont", "que", "qui", "où"], correct: 3 },
      { diff: "medium", avatar: null, q: "C’est un sujet ____ nous parlons souvent.", options: ["où", "qui", "dont", "que"], correct: 2 },
      { diff: "medium", avatar: null, q: "J’ai beaucoup de devoirs; je dois ____ finir ce soir.", options: ["les", "lui", "leur", "y"], correct: 0 },
      { diff: "medium", avatar: null, q: "Tu vas au laboratoire ? Oui, j’____ vais maintenant.", options: ["leur", "en", "y", "les"], correct: 2 },
      { diff: "medium", avatar: null, q: "Tu veux des informations ? Oui, j’____ veux davantage.", options: ["y", "la", "lui", "en"], correct: 3 },
      { diff: "medium", avatar: null, q: "Nous protégeons la nature ____ les générations futures.", options: ["sous", "tandis que", "malgré", "pour"], correct: 3 },
      { diff: "medium", avatar: null, q: "____ la pluie, la campagne de nettoyage a continué.", options: ["Malgré", "Parce que", "Sous", "Grâce à"], correct: 0 },
      { diff: "medium", avatar: null, q: "Le projet a réussi ____ la coopération des élèves.", options: ["sans", "à cause de", "grâce à", "malgré"], correct: 2 },
      { diff: "medium", avatar: null, q: "La route est fermée ____ un accident.", options: ["grâce à", "à cause d’", "malgré", "pour"], correct: 1 },
      { diff: "hard", avatar: null, q: "Internet est utile; ____, il faut l’utiliser avec prudence.", options: ["hier", "sous", "donc toujours", "cependant"], correct: 3 },
      { diff: "hard", avatar: null, q: "La pollution augmente; ____ nous devons agir.", options: ["où", "donc", "malgré", "jamais"], correct: 1 },
      { diff: "hard", avatar: null, q: "Il étudie beaucoup ____ il veut réussir.", options: ["parce qu’", "tandis", "où", "malgré"], correct: 0 },
      { diff: "hard", avatar: null, q: "Amina préfère la science, ____ son frère préfère les arts.", options: ["tandis que", "grâce à", "parce que", "donc"], correct: 0 },
      { diff: "hard", avatar: null, q: "Pour postuler à certains emplois, il faut préparer un ____.", options: ["menu", "billet", "thermomètre", "CV"], correct: 3 },
      { diff: "hard", avatar: null, q: "Une personne qui cherche un emploi peut consulter des offres d’____.", options: ["école", "eau", "emploi", "énergie"], correct: 2 },
      { diff: "hard", avatar: null, q: "Le développement durable cherche à répondre aux besoins actuels sans compromettre ceux des générations ____.", options: ["futures", "passées uniquement", "absentes", "scolaires"], correct: 0 },
      { diff: "hard", avatar: null, q: "Une information virale n’est pas nécessairement ____.", options: ["française", "vraie", "longue", "ancienne"], correct: 1 },
      { diff: "hard", avatar: null, q: "Si un inconnu demande ton mot de passe en ligne, tu dois ____ de le donner.", options: ["accepter", "partager", "publier", "refuser"], correct: 3 },
      { diff: "hard", avatar: null, q: "Pour améliorer son français, un élève peut lire, écouter, parler et ____ régulièrement.", options: ["éviter", "écrire", "abandonner", "oublier"], correct: 1 },
    ],
  },
]

export function jss3LangCategoryBySlug(slug: string): LangCategory | undefined {
  return JSS3_LANG.find((c) => c.slug === slug)
}
