// AUTO-GENERATED Primary 2 quiz bank — 250 questions, 5 categories.
// Do not edit by hand; regenerate from the source markdown.

import type { QuizCategory } from './quiz-p1'

export const P2_QUIZ: QuizCategory[] = [
  {
    slug: "food", name: "Food & Nutrition", icon: "🍎",
    color: "#E0574C", badge: "Food Explorer", badgeIcon: "🍎",
    questions: [
      { n: 1, diff: "easy", q: "Which food is a fruit?", options: ["Mango", "Rice", "Fish", "Egg"], correct: 0 },
      { n: 2, diff: "easy", q: "Which food is a vegetable?", options: ["Carrot", "Bread", "Milk", "Meat"], correct: 0 },
      { n: 3, diff: "easy", q: "Which food comes from a chicken?", options: ["Egg", "Yam", "Orange", "Beans"], correct: 0 },
      { n: 4, diff: "easy", q: "Which food comes from a plant?", options: ["Beans", "Fish", "Egg", "Milk"], correct: 0 },
      { n: 5, diff: "easy", q: "Which drink is best when you are thirsty?", options: ["Clean water", "Paint", "Kerosene", "Ink"], correct: 0 },
      { n: 6, diff: "easy", q: "Which food is made from maize?", options: ["Pap", "Soap", "Glass", "Paper"], correct: 0 },
      { n: 7, diff: "easy", q: "Which food can help build the body?", options: ["Beans", "Sweet", "Sugar", "Soft drink"], correct: 0 },
      { n: 8, diff: "easy", q: "Which food gives the body energy?", options: ["Rice", "Stone", "Plastic", "Chalk"], correct: 0 },
      { n: 9, diff: "easy", q: "Which food comes from a cow?", options: ["Milk", "Yam", "Maize", "Orange"], correct: 0 },
      { n: 10, diff: "easy", q: "Which one is a root crop?", options: ["Yam", "Mango", "Fish", "Egg"], correct: 0 },
      { n: 11, diff: "easy", q: "Which food contains a seed?", options: ["Orange", "Milk", "Fish", "Bread"], correct: 0 },
      { n: 12, diff: "easy", q: "Which one is a grain?", options: ["Rice", "Egg", "Meat", "Milk"], correct: 0 },
      { n: 13, diff: "easy", q: "Which is a healthy snack?", options: ["Banana", "Many sweets", "Soft drink", "Sugar cube"], correct: 0 },
      { n: 14, diff: "easy", q: "Which food is often eaten with soup?", options: ["Yam", "Paper", "Soap", "Pencil"], correct: 0 },
      { n: 15, diff: "easy", q: "Which one is a leafy vegetable?", options: ["Spinach", "Bread", "Egg", "Fish"], correct: 0 },
      { n: 16, diff: "easy", q: "Which food can come from a school garden?", options: ["Tomato", "Plastic", "Glass", "Metal"], correct: 0 },
      { n: 17, diff: "easy", q: "What should you do before eating?", options: ["Wash your hands", "Play in mud", "Touch waste", "Dirty the plate"], correct: 0 },
      { n: 18, diff: "easy", q: "Which food should be washed before eating?", options: ["Fruit", "Book", "Shoe", "Pencil"], correct: 0 },
      { n: 19, diff: "easy", q: "Where should cooked food be kept?", options: ["Covered and clean", "On the floor", "Near rubbish", "In dirty water"], correct: 0 },
      { n: 20, diff: "easy", q: "Which one is food?", options: ["Plantain", "Chair", "Broom", "Bottle"], correct: 0 },
      { n: 21, diff: "medium", q: "Why do we eat food?", options: ["To grow, stay healthy and get energy", "To make rain", "To make books", "To create litter"], correct: 0 },
      { n: 22, diff: "medium", q: "Which meal contains both plant and animal food?", options: ["Rice and fish", "Stone and sand", "Paper and pencil", "Soap and water"], correct: 0 },
      { n: 23, diff: "medium", q: "Why should fruits be washed before eating?", options: ["To remove dirt and germs", "To make them toys", "To change their colour", "To make them harder"], correct: 0 },
      { n: 24, diff: "medium", q: "Which action keeps food safe?", options: ["Covering it", "Leaving it open", "Putting it on the floor", "Touching it with dirty hands"], correct: 0 },
      { n: 25, diff: "medium", q: "Which pair contains body-building foods?", options: ["Beans and egg", "Sugar and sweets", "Water and salt", "Orange and mango"], correct: 0 },
      { n: 26, diff: "medium", q: "Which pair mainly gives energy?", options: ["Rice and yam", "Fish and egg", "Orange and spinach", "Milk and fish"], correct: 0 },
      { n: 27, diff: "medium", q: "Which pair is rich in protective foods?", options: ["Orange and spinach", "Rice and yam", "Fish and egg", "Bread and sugar"], correct: 0 },
      { n: 28, diff: "medium", q: "What may happen when flies land on uncovered food?", options: ["The food may become contaminated", "The food becomes a book", "The food turns into water", "The food becomes sweeter"], correct: 0 },
      { n: 29, diff: "medium", q: "Why is breakfast important?", options: ["It gives energy to start the day", "It makes us sleepy all day", "It replaces water", "It stops growth"], correct: 0 },
      { n: 30, diff: "medium", q: "Which is a good food-hygiene habit?", options: ["Use a clean plate", "Use a dirty spoon", "Eat with muddy hands", "Leave food near waste"], correct: 0 },
      { n: 31, diff: "medium", q: "What should you do if food smells rotten?", options: ["Avoid it and tell an adult", "Eat it quickly", "Hide it", "Give it to a friend"], correct: 0 },
      { n: 32, diff: "medium", q: "Which activity helps produce food?", options: ["Farming", "Burning plastic", "Breaking glass", "Scattering litter"], correct: 0 },
      { n: 33, diff: "medium", q: "Which pair comes mainly from plants?", options: ["Rice and beans", "Fish and egg", "Milk and meat", "Chicken and fish"], correct: 0 },
      { n: 34, diff: "medium", q: "Which meal is healthier for lunch?", options: ["Rice, beans and vegetables", "Only sweets", "Only soft drink", "Only sugar"], correct: 0 },
      { n: 35, diff: "medium", q: "Why do we grow vegetables in a garden?", options: ["For food and learning", "To make litter", "To waste water", "To destroy soil"], correct: 0 },
      { n: 36, diff: "medium", q: "Which tool can be used to carry harvested vegetables?", options: ["Basket", "Television", "Pillow", "Clock"], correct: 0 },
      { n: 37, diff: "medium", q: "Which choice helps reduce food waste?", options: ["Take only what you can eat", "Throw good food away", "Leave food uncovered", "Waste lunch"], correct: 0 },
      { n: 38, diff: "medium", q: "Which food has protein that helps growth?", options: ["Egg", "Sugar", "Soft drink", "Candy"], correct: 0 },
      { n: 39, diff: "medium", q: "Which food is usually cooked before eating?", options: ["Beans", "Banana", "Orange", "Mango"], correct: 0 },
      { n: 40, diff: "medium", q: "Which subject can help pupils count harvested fruits?", options: ["Mathematics", "Music only", "Drama only", "Handwriting only"], correct: 0 },
      { n: 41, diff: "hard", q: "Which meal best combines energy, body-building and protective foods?", options: ["Rice, beans and vegetables", "Sugar and sweets", "Soft drink and candy", "Salt and water"], correct: 0 },
      { n: 42, diff: "hard", q: "Why is eating different healthy foods important?", options: ["Different foods provide different nutrients", "All foods do exactly the same job", "It stops us needing water", "It prevents plants from growing"], correct: 0 },
      { n: 43, diff: "hard", q: "A pupil eats only sweets every day. What is the better advice?", options: ["Eat a variety of healthy foods", "Eat more sweets only", "Stop drinking water", "Avoid fruits and vegetables"], correct: 0 },
      { n: 44, diff: "hard", q: "Which sequence begins with food from a plant?", options: ["Maize → chicken → child", "Child → maize → chicken", "Fish → plastic → maize", "Stone → goat → child"], correct: 0 },
      { n: 45, diff: "hard", q: "Why should a food garden be kept free from plastic litter?", options: ["Cleaner soil supports healthier plant growth", "Plastic becomes plant food", "Plastic makes rain", "Glass improves roots"], correct: 0 },
      { n: 46, diff: "hard", q: "If clean food falls into dirty water, what should a pupil do?", options: ["Do not eat it; tell an adult", "Eat it immediately", "Give it to another pupil", "Put it back on the plate"], correct: 0 },
      { n: 47, diff: "hard", q: "Which action connects food and water wisely?", options: ["Water crops carefully without wasting water", "Flood paths daily", "Leave taps running", "Pour dirty water on food"], correct: 0 },
      { n: 48, diff: "hard", q: "A farmer plants maize and waters it regularly. What is most likely to happen?", options: ["The maize can grow well", "The maize becomes plastic", "The maize turns into fish", "The maize becomes a stone"], correct: 0 },
      { n: 49, diff: "hard", q: "Which choice best shows responsible food use?", options: ["Eat enough and save leftovers safely", "Take too much and waste it", "Leave food uncovered", "Throw fresh food away"], correct: 0 },
      { n: 50, diff: "hard", q: "How can a class use science and mathematics in a garden?", options: ["Observe plant growth and count harvests", "Sing only", "Draw only", "Play only"], correct: 0 },
    ]
  },
  {
    slug: "energy", name: "Energy & Water", icon: "💧",
    color: "#3E7CA6", badge: "Energy & Water Hero", badgeIcon: "💧",
    questions: [
      { n: 1, diff: "easy", q: "What do we drink when thirsty?", options: ["Clean water", "Sand", "Smoke", "Oil"], correct: 0 },
      { n: 2, diff: "easy", q: "Which gives natural light in the daytime?", options: ["Sun", "Chair", "Shoe", "Spoon"], correct: 0 },
      { n: 3, diff: "easy", q: "Which appliance uses electricity?", options: ["Fan", "Stone", "Leaf", "Cup"], correct: 0 },
      { n: 4, diff: "easy", q: "Which item can hold water?", options: ["Bucket", "Net", "Paper sheet", "Broom"], correct: 0 },
      { n: 5, diff: "easy", q: "Where does rain come from?", options: ["Clouds", "Shoes", "Books", "Roads"], correct: 0 },
      { n: 6, diff: "easy", q: "Which water is safest to drink?", options: ["Clean water", "Gutter water", "Muddy puddle", "Soapy water"], correct: 0 },
      { n: 7, diff: "easy", q: "What does the sun provide?", options: ["Light and heat", "Plastic", "Bread", "Shoes"], correct: 0 },
      { n: 8, diff: "easy", q: "Which appliance keeps food cold?", options: ["Refrigerator", "Broom", "Plate", "Basket"], correct: 0 },
      { n: 9, diff: "easy", q: "Which action saves water?", options: ["Close the tap", "Leave tap running", "Spill water", "Play with the tap"], correct: 0 },
      { n: 10, diff: "easy", q: "Which action saves electricity?", options: ["Switch off unused lights", "Leave lights on", "Open taps", "Scatter litter"], correct: 0 },
      { n: 11, diff: "easy", q: "What do plants need to grow?", options: ["Water", "Plastic", "Smoke", "Glass"], correct: 0 },
      { n: 12, diff: "easy", q: "Which is a source of water?", options: ["Rain", "Dust", "Smoke", "Plastic"], correct: 0 },
      { n: 13, diff: "easy", q: "Which appliance moves air?", options: ["Fan", "Plate", "Book", "Cup"], correct: 0 },
      { n: 14, diff: "easy", q: "Which is a renewable source of energy?", options: ["Sun", "Diesel", "Petrol", "Kerosene"], correct: 0 },
      { n: 15, diff: "easy", q: "Which water can be used for washing hands?", options: ["Clean water", "Paint", "Kerosene", "Ink"], correct: 0 },
      { n: 16, diff: "easy", q: "Which fuel is used for cooking in some homes?", options: ["Gas", "Sand", "Paper clip", "Chalk"], correct: 0 },
      { n: 17, diff: "easy", q: "What makes a bulb shine?", options: ["Electricity", "Soil", "Leaf", "Food"], correct: 0 },
      { n: 18, diff: "easy", q: "What should you do after using a tap?", options: ["Close it", "Break it", "Leave it open", "Flood the floor"], correct: 0 },
      { n: 19, diff: "easy", q: "Which is a body of water?", options: ["River", "Cup", "Spoon", "Bottle cap"], correct: 0 },
      { n: 20, diff: "easy", q: "Which thing needs water?", options: ["A growing plant", "A stone", "A plastic chair", "A metal spoon"], correct: 0 },
      { n: 21, diff: "medium", q: "Why should we save water?", options: ["It is useful and should not be wasted", "Water is litter", "Water is a toy", "Water is always dirty"], correct: 0 },
      { n: 22, diff: "medium", q: "Which activity uses water?", options: ["Bathing", "Reading", "Counting", "Drawing with pencil"], correct: 0 },
      { n: 23, diff: "medium", q: "Which is a clean source of energy?", options: ["Sunlight", "Burning rubbish", "Smoke", "Dirty oil"], correct: 0 },
      { n: 24, diff: "medium", q: "Why switch off a fan when leaving a room?", options: ["To save electricity", "To waste electricity", "To make rain", "To grow litter"], correct: 0 },
      { n: 25, diff: "medium", q: "Which action can pollute water?", options: ["Throwing waste into it", "Covering a clean container", "Closing a tap", "Using a clean cup"], correct: 0 },
      { n: 26, diff: "medium", q: "What do solar panels use?", options: ["Sunlight", "Mud", "Plastic bags", "Food"], correct: 0 },
      { n: 27, diff: "medium", q: "Why should drinking water be covered?", options: ["To keep dirt out", "To make it salty", "To collect litter", "To waste it"], correct: 0 },
      { n: 28, diff: "medium", q: "Which is a careful way to water plants?", options: ["Water near the roots", "Flood the whole yard", "Leave hose running", "Pour oil"], correct: 0 },
      { n: 29, diff: "medium", q: "Which pair both use electricity?", options: ["Fan and television", "Stone and leaf", "Cup and plate", "Book and pencil"], correct: 0 },
      { n: 30, diff: "medium", q: "Why is clean water important?", options: ["It supports good health", "It makes litter", "It breaks books", "It creates smoke"], correct: 0 },
      { n: 31, diff: "medium", q: "Which action protects a stream?", options: ["Keep rubbish out", "Throw plastic in", "Pour oil in", "Wash waste into it"], correct: 0 },
      { n: 32, diff: "medium", q: "A bulb is on in an empty room. What should you do?", options: ["Switch it off safely", "Leave it on all day", "Break it", "Pour water on it"], correct: 0 },
      { n: 33, diff: "medium", q: "What happens when rain falls on crops?", options: ["They receive water", "They become plastic", "Soil becomes glass", "The sun disappears"], correct: 0 },
      { n: 34, diff: "medium", q: "Which can collect rainwater?", options: ["Clean tank", "Open shoe", "Broom", "Pencil"], correct: 0 },
      { n: 35, diff: "medium", q: "Which is a safe electricity rule?", options: ["Keep wet hands away from sockets", "Touch sockets with wet hands", "Put metal in sockets", "Pour water on wires"], correct: 0 },
      { n: 36, diff: "medium", q: "What can wind do?", options: ["Move leaves", "Turn water to plastic", "Make stones eat", "Grow shoes"], correct: 0 },
      { n: 37, diff: "medium", q: "Why should a leaking tap be repaired?", options: ["To stop wasting water", "To make more leaks", "To waste more water", "To dirty the floor"], correct: 0 },
      { n: 38, diff: "medium", q: "Why do farmers water crops?", options: ["Crops need water to grow", "To make smoke", "To make plastic", "To wash the sky"], correct: 0 },
      { n: 39, diff: "medium", q: "Which habit saves water while washing hands?", options: ["Turn off tap while soaping", "Keep tap running", "Play with hose", "Pour water away"], correct: 0 },
      { n: 40, diff: "medium", q: "Which subject can help measure cups of water?", options: ["Mathematics", "Dance only", "Singing only", "Storytelling only"], correct: 0 },
      { n: 41, diff: "hard", q: "Which sequence shows solar energy use?", options: ["Sun → solar panel → electricity", "Bulb → sun → rain", "Water → plastic → sun", "Soil → fan → cloud"], correct: 0 },
      { n: 42, diff: "hard", q: "A tap leaks all day. What is the main problem?", options: ["Useful water is wasted", "More food is produced", "Electricity is stored", "Air becomes solid"], correct: 0 },
      { n: 43, diff: "hard", q: "Why should water sources be kept clean?", options: ["People and animals may depend on them", "Waste makes water healthier", "Oil makes water safer", "Plastic improves water"], correct: 0 },
      { n: 44, diff: "hard", q: "Which action connects gardening and water conservation?", options: ["Water crops at their roots", "Flood paths daily", "Leave hose running", "Wash soil away"], correct: 0 },
      { n: 45, diff: "hard", q: "A school wants to lower electricity use. Which plan is best?", options: ["Turn off unused lights and fans", "Keep all appliances on", "Add lights to empty rooms", "Run fans outdoors"], correct: 0 },
      { n: 46, diff: "hard", q: "Which statement about the sun is correct?", options: ["It is a natural source of light and heat", "It is made by a bulb", "It is a water tap", "It is a plant root"], correct: 0 },
      { n: 47, diff: "hard", q: "Why are exposed electrical wires dangerous?", options: ["They can cause electric shock", "They make food grow", "They clean water", "They are safe toys"], correct: 0 },
      { n: 48, diff: "hard", q: "Which two resources are important for crop growth?", options: ["Sunlight and water", "Plastic and smoke", "Glass and paint", "Ink and rubber"], correct: 0 },
      { n: 49, diff: "hard", q: "If rainwater is stored for watering crops, what is being conserved?", options: ["Water", "Smoke", "Plastic", "Noise"], correct: 0 },
      { n: 50, diff: "hard", q: "Which action saves both water and energy at home?", options: ["Use only what is needed and switch appliances off", "Leave taps and lights on", "Run fans in empty rooms", "Waste stored water"], correct: 0 },
    ]
  },
  {
    slug: "environment", name: "Environment", icon: "🌱",
    color: "#5C9E3A", badge: "Green Guardian", badgeIcon: "🌱",
    questions: [
      { n: 1, diff: "easy", q: "What do we call everything around us?", options: ["Environment", "Only food", "Only books", "Only toys"], correct: 0 },
      { n: 2, diff: "easy", q: "Which is a living thing?", options: ["Tree", "Stone", "Bottle", "Chair"], correct: 0 },
      { n: 3, diff: "easy", q: "Which is non-living?", options: ["Rock", "Goat", "Grass", "Bird"], correct: 0 },
      { n: 4, diff: "easy", q: "Where should litter go?", options: ["Bin", "Road", "River", "Garden bed"], correct: 0 },
      { n: 5, diff: "easy", q: "Which animal can fly?", options: ["Bird", "Goat", "Fish", "Dog"], correct: 0 },
      { n: 6, diff: "easy", q: "Which plant part is usually green?", options: ["Leaf", "Root", "Seed coat", "Dry stick"], correct: 0 },
      { n: 7, diff: "easy", q: "Which place should pupils keep clean?", options: ["Classroom", "Only cupboard", "Only bag", "Nowhere"], correct: 0 },
      { n: 8, diff: "easy", q: "Which grows in soil?", options: ["Plant", "Plastic bottle", "Metal spoon", "Glass cup"], correct: 0 },
      { n: 9, diff: "easy", q: "Which animal lives in water?", options: ["Fish", "Goat", "Chicken", "Cat"], correct: 0 },
      { n: 10, diff: "easy", q: "What can be planted to make a place greener?", options: ["Tree", "Plastic", "Glass", "Tin"], correct: 0 },
      { n: 11, diff: "easy", q: "Which item is natural?", options: ["Soil", "Plastic bag", "Metal can", "Glass bottle"], correct: 0 },
      { n: 12, diff: "easy", q: "Which item is made by people?", options: ["Chair", "Tree", "River", "Cloud"], correct: 0 },
      { n: 13, diff: "easy", q: "What do people breathe?", options: ["Air", "Soil", "Plastic", "Juice"], correct: 0 },
      { n: 14, diff: "easy", q: "Which tool helps sweep a classroom?", options: ["Broom", "Litter", "Mud", "Smoke"], correct: 0 },
      { n: 15, diff: "easy", q: "Which can pollute the ground?", options: ["Litter", "Flower", "Clean soil", "Tree"], correct: 0 },
      { n: 16, diff: "easy", q: "Which animal may live on a farm?", options: ["Goat", "Shark", "Whale", "Dolphin"], correct: 0 },
      { n: 17, diff: "easy", q: "Which should be protected?", options: ["Plants and animals", "Only litter", "Smoke", "Dirty water"], correct: 0 },
      { n: 18, diff: "easy", q: "What colour are many healthy leaves?", options: ["Green", "Silver", "Black only", "Purple only"], correct: 0 },
      { n: 19, diff: "easy", q: "Which can provide shade?", options: ["Tree", "Spoon", "Pencil", "Cup"], correct: 0 },
      { n: 20, diff: "easy", q: "How should we treat a school garden?", options: ["Care for it", "Destroy it", "Fill it with litter", "Step on plants"], correct: 0 },
      { n: 21, diff: "medium", q: "Why should we use a waste bin?", options: ["To keep the area clean", "To spread litter", "To dirty water", "To harm plants"], correct: 0 },
      { n: 22, diff: "medium", q: "Which action protects animals?", options: ["Keep habitats clean", "Destroy nests", "Throw waste in ponds", "Chase animals for fun"], correct: 0 },
      { n: 23, diff: "medium", q: "What can happen when litter blocks drains?", options: ["Water may not flow well", "Trees become books", "Sun stops shining", "Fish grow on roads"], correct: 0 },
      { n: 24, diff: "medium", q: "Which is a good environmental habit?", options: ["Pick up litter safely", "Throw wrappers down", "Burn plastic near class", "Pour oil on soil"], correct: 0 },
      { n: 25, diff: "medium", q: "Why are trees useful?", options: ["They provide shade and habitat", "They make plastic", "They create only litter", "They stop all rain"], correct: 0 },
      { n: 26, diff: "medium", q: "Which pair contains living things?", options: ["Grass and bird", "Rock and chair", "Cup and plate", "Book and pencil"], correct: 0 },
      { n: 27, diff: "medium", q: "Which pair contains non-living things?", options: ["Stone and bottle", "Tree and goat", "Bird and grass", "Fish and flower"], correct: 0 },
      { n: 28, diff: "medium", q: "Which action can harm soil?", options: ["Dumping waste on it", "Planting a seed", "Adding compost", "Keeping it clean"], correct: 0 },
      { n: 29, diff: "medium", q: "What is a habitat?", options: ["A place where a living thing lives", "A type of pencil", "A food plate", "A school bell"], correct: 0 },
      { n: 30, diff: "medium", q: "Which habitat suits a fish?", options: ["Water", "Dry cupboard", "School desk", "Roof"], correct: 0 },
      { n: 31, diff: "medium", q: "Why should young plants not be stepped on?", options: ["They can be damaged", "They become stronger", "They make plastic", "They stop needing water"], correct: 0 },
      { n: 32, diff: "medium", q: "Which action improves a school compound?", options: ["Plant flowers", "Scatter waste", "Break branches", "Block drains"], correct: 0 },
      { n: 33, diff: "medium", q: "Which item can often be reused?", options: ["Clean bottle", "Smoke", "Sunlight", "Noise"], correct: 0 },
      { n: 34, diff: "medium", q: "What can suitable dry leaves become?", options: ["Compost", "Plastic", "Glass", "Electricity"], correct: 0 },
      { n: 35, diff: "medium", q: "Which action helps keep air cleaner?", options: ["Avoid burning rubbish", "Burn plastic", "Burn tyres", "Make more smoke"], correct: 0 },
      { n: 36, diff: "medium", q: "Why should drains be kept clear?", options: ["So water can flow", "So litter can grow", "So fish can fly", "So roads become rivers"], correct: 0 },
      { n: 37, diff: "medium", q: "Which activity helps pupils study nature?", options: ["Observe plants and insects", "Throw stones at birds", "Break leaves", "Dump waste"], correct: 0 },
      { n: 38, diff: "medium", q: "What can a tree provide for birds?", options: ["Habitat", "Plastic", "Paint", "Metal"], correct: 0 },
      { n: 39, diff: "medium", q: "Which is better for garden soil?", options: ["Compost", "Broken glass", "Plastic litter", "Dirty oil"], correct: 0 },
      { n: 40, diff: "medium", q: "Why do we clean our surroundings?", options: ["For health and a better environment", "To make more waste", "To block paths", "To dirty water"], correct: 0 },
      { n: 41, diff: "hard", q: "Which action protects both land and water?", options: ["Put waste in bins, not drains", "Throw waste in streams", "Leave litter on soil", "Pour oil into gutters"], correct: 0 },
      { n: 42, diff: "hard", q: "A butterfly visits a flower. What does this show?", options: ["Living things interacting", "Only non-living things", "Electricity use", "Water pollution"], correct: 0 },
      { n: 43, diff: "hard", q: "What may happen if many trees are removed?", options: ["Animals lose habitat and shade decreases", "Plastic production increases naturally", "Metal grows faster", "Rain stops forever"], correct: 0 },
      { n: 44, diff: "hard", q: "Which school plan best improves the environment?", options: ["Bins, clean-up and tree planting", "More litter and smoke", "Blocked drains", "Burning plastic"], correct: 0 },
      { n: 45, diff: "hard", q: "Why is soil important?", options: ["It supports plant growth", "It powers televisions", "It makes plastic bags", "It is a type of rain"], correct: 0 },
      { n: 46, diff: "hard", q: "Which example shows reuse?", options: ["Using a clean container again", "Throwing it away immediately", "Burning it", "Putting it in a river"], correct: 0 },
      { n: 47, diff: "hard", q: "Why should plastic not be thrown into rivers?", options: ["It can pollute water and harm living things", "It makes water sweeter", "It feeds every fish", "It turns into rain"], correct: 0 },
      { n: 48, diff: "hard", q: "Which observation is part of Basic Science?", options: ["A seed grows into a plant", "A chair is a sentence", "A song is a number", "A pencil is rain"], correct: 0 },
      { n: 49, diff: "hard", q: "Which action shows good citizenship at school?", options: ["Keeping shared spaces clean", "Scattering wrappers", "Breaking plants", "Blocking walkways"], correct: 0 },
      { n: 50, diff: "hard", q: "Which choice connects health and environment?", options: ["Clean surroundings reduce exposure to dirt and waste", "More litter improves health", "Dirty water is always safe", "Smoke makes air cleaner"], correct: 0 },
    ]
  },
  {
    slug: "climate", name: "Climate Literacy", icon: "🌧️",
    color: "#C8912E", badge: "Climate Champion", badgeIcon: "🌧️",
    questions: [
      { n: 1, diff: "easy", q: "What is the weather like when rain falls?", options: ["Rainy", "Dry only", "Snowy always", "Windless always"], correct: 0 },
      { n: 2, diff: "easy", q: "What do we see in the sky on a sunny day?", options: ["Sun", "Fish", "Chair", "Spoon"], correct: 0 },
      { n: 3, diff: "easy", q: "Which can move leaves?", options: ["Wind", "Stone", "Book", "Plate"], correct: 0 },
      { n: 4, diff: "easy", q: "Which comes from clouds?", options: ["Rain", "Sand", "Plastic", "Smoke"], correct: 0 },
      { n: 5, diff: "easy", q: "What can we use on a rainy day?", options: ["Umbrella", "Pillow", "Plate", "Broom"], correct: 0 },
      { n: 6, diff: "easy", q: "Which clothing is suitable for a hot day?", options: ["Light clothing", "Heavy blanket", "Winter coat", "Thick wool"], correct: 0 },
      { n: 7, diff: "easy", q: "Which word describes a day with much sun?", options: ["Sunny", "Rainy", "Flooded", "Stormy only"], correct: 0 },
      { n: 8, diff: "easy", q: "What do we call moving air?", options: ["Wind", "Soil", "Food", "Rock"], correct: 0 },
      { n: 9, diff: "easy", q: "What can cover the sky?", options: ["Clouds", "Shoes", "Tables", "Bottles"], correct: 0 },
      { n: 10, diff: "easy", q: "Which weather may make us feel cold?", options: ["Cool weather", "Hot sun", "Warm room", "Cooking fire"], correct: 0 },
      { n: 11, diff: "easy", q: "How does rain help plants?", options: ["It provides water", "It makes plastic", "It turns them to stone", "It removes soil forever"], correct: 0 },
      { n: 12, diff: "easy", q: "Which weather helps wet clothes dry faster?", options: ["Sunny weather", "Heavy rain", "Flood", "Storm rain"], correct: 0 },
      { n: 13, diff: "easy", q: "What can protect the head from strong sun?", options: ["Hat", "Plate", "Spoon", "Book"], correct: 0 },
      { n: 14, diff: "easy", q: "What is water falling from clouds called?", options: ["Rain", "Wind", "Soil", "Heat"], correct: 0 },
      { n: 15, diff: "easy", q: "Which weather may make puddles?", options: ["Rainy weather", "Dry sunny weather", "No weather", "Only wind"], correct: 0 },
      { n: 16, diff: "easy", q: "Which tool measures temperature?", options: ["Thermometer", "Broom", "Cup", "Basket"], correct: 0 },
      { n: 17, diff: "easy", q: "Which season has more rain in many parts of Nigeria?", options: ["Rainy season", "Dry season", "Snow season", "Ice season"], correct: 0 },
      { n: 18, diff: "easy", q: "Which season is usually drier in Nigeria?", options: ["Dry season", "Rainy season", "Snow season", "Ice season"], correct: 0 },
      { n: 19, diff: "easy", q: "Which weather should make pupils seek safe shelter?", options: ["Thunderstorm", "Gentle sunshine", "Light breeze", "Clear sky"], correct: 0 },
      { n: 20, diff: "easy", q: "What should children do during dangerous weather?", options: ["Follow adult safety instructions", "Run into floodwater", "Touch fallen wires", "Stand under unsafe objects"], correct: 0 },
      { n: 21, diff: "medium", q: "What is weather?", options: ["The condition of the air outside at a given time", "A kind of food", "A school subject only", "A type of soil"], correct: 0 },
      { n: 22, diff: "medium", q: "Which is a weather observation?", options: ["The day is cloudy", "The desk is brown", "The book is new", "The bag is heavy"], correct: 0 },
      { n: 23, diff: "medium", q: "Why do farmers watch rainfall?", options: ["Crops need suitable water", "Rain makes plastic", "Rain powers pencils", "Rain stops all growth"], correct: 0 },
      { n: 24, diff: "medium", q: "Which weather can increase thirst?", options: ["Hot weather", "Cool rainy weather", "Cloudy weather only", "Nighttime only"], correct: 0 },
      { n: 25, diff: "medium", q: "What should pupils do in very hot sunshine?", options: ["Drink water and use shade", "Avoid water", "Wear heavy blankets", "Play on hot metal"], correct: 0 },
      { n: 26, diff: "medium", q: "What can happen after very heavy rain?", options: ["Flooding", "Snow in every Nigerian town", "Sun disappears forever", "Trees become metal"], correct: 0 },
      { n: 27, diff: "medium", q: "Why should pupils avoid floodwater?", options: ["It can be unsafe", "It is always clean", "It is a playground", "It is drinking water"], correct: 0 },
      { n: 28, diff: "medium", q: "How can pupils learn about weather?", options: ["Observe sky, rain and wind", "Throw litter", "Break tools", "Guess without observing"], correct: 0 },
      { n: 29, diff: "medium", q: "What does a thermometer measure?", options: ["Temperature", "Rainfall amount only", "Wind direction only", "Soil colour"], correct: 0 },
      { n: 30, diff: "medium", q: "Which sign may show rain is coming?", options: ["Dark clouds", "A clean plate", "A closed book", "A dry pencil"], correct: 0 },
      { n: 31, diff: "medium", q: "How can trees help on a hot day?", options: ["Provide shade", "Make plastic", "Stop all wind", "Turn heat into food"], correct: 0 },
      { n: 32, diff: "medium", q: "What is safer during lightning?", options: ["Stay in a safe building", "Stand in an open field", "Touch metal poles", "Play in floodwater"], correct: 0 },
      { n: 33, diff: "medium", q: "Why is rainfall important to gardens?", options: ["It supplies water", "It supplies plastic", "It supplies glass", "It supplies pencils"], correct: 0 },
      { n: 34, diff: "medium", q: "How can pupils record daily weather?", options: ["Use a simple weather chart", "Throw observations away", "Break the chart", "Never look outside"], correct: 0 },
      { n: 35, diff: "medium", q: "What may happen on a windy day?", options: ["Leaves may move", "Rocks may eat", "Water becomes glass", "Books grow"], correct: 0 },
      { n: 36, diff: "medium", q: "What is climate?", options: ["The usual weather pattern of a place over many years", "Weather for one minute", "A type of food", "A school bag"], correct: 0 },
      { n: 37, diff: "medium", q: "Which statement is about weather?", options: ["It is raining this morning", "This place is usually wet for many years", "A region is often hot and dry", "A place has a long rainy season"], correct: 0 },
      { n: 38, diff: "medium", q: "Which can reduce heat around a schoolyard?", options: ["Trees and shade", "Bare hot ground", "Burning rubbish", "More smoke"], correct: 0 },
      { n: 39, diff: "medium", q: "Why is water important during dry periods?", options: ["Rainfall may be low", "Water becomes litter", "It should be wasted", "It must be dirtied"], correct: 0 },
      { n: 40, diff: "medium", q: "How can pupils prepare for heavy rain?", options: ["Keep drains clear", "Block drains", "Throw plastic in gutters", "Leave rubbish in waterways"], correct: 0 },
      { n: 41, diff: "hard", q: "Which statement best compares weather and climate?", options: ["Weather is short-term; climate is the usual pattern over many years", "They are exactly the same", "Climate changes every minute", "Weather only means rain"], correct: 0 },
      { n: 42, diff: "hard", q: "A week is extremely hot. Which action is safest?", options: ["Use shade, drink water and follow safety advice", "Avoid water", "Burn rubbish", "Play on hot metal"], correct: 0 },
      { n: 43, diff: "hard", q: "How can blocked drains worsen heavy rain?", options: ["Water may collect and cause flooding", "They make rain stop", "They cool the sun", "They remove clouds"], correct: 0 },
      { n: 44, diff: "hard", q: "Which school activity best supports climate learning?", options: ["Keep a daily weather chart", "Ignore weather", "Burn leaves for smoke", "Waste water"], correct: 0 },
      { n: 45, diff: "hard", q: "How do trees help people during hot weather?", options: ["They provide cooling shade", "They make petrol", "They stop every storm", "They create plastic"], correct: 0 },
      { n: 46, diff: "hard", q: "Which is an adaptation to hot weather?", options: ["Using shade and drinking enough water", "Leaving taps running", "Burning plastic", "Removing all trees"], correct: 0 },
      { n: 47, diff: "hard", q: "Which action reduces unnecessary energy use?", options: ["Switch off unused lights", "Leave lights on all day", "Run empty-room fans", "Open refrigerator doors"], correct: 0 },
      { n: 48, diff: "hard", q: "A garden receives little rainfall. What is a sensible response?", options: ["Water carefully and avoid waste", "Flood the road", "Remove all plants immediately", "Leave taps open"], correct: 0 },
      { n: 49, diff: "hard", q: "Why do we learn about climate and weather?", options: ["To make safer and wiser choices", "To control the sun", "To stop all rain", "To create clouds by hand"], correct: 0 },
      { n: 50, diff: "hard", q: "Which subjects can be combined in a weather-chart activity?", options: ["Basic Science and Mathematics", "Only singing", "Only handwriting", "Only drama"], correct: 0 },
    ]
  },
  {
    slug: "sustainability", name: "Sustainability", icon: "♻️",
    color: "#7A7488", badge: "Sustainability Star", badgeIcon: "♻️",
    questions: [
      { n: 1, diff: "easy", q: "What should we do with water?", options: ["Use it wisely", "Waste it", "Dirty it", "Spill it"], correct: 0 },
      { n: 2, diff: "easy", q: "What should we do with unused lights?", options: ["Switch them off", "Leave them on", "Break them", "Wet them"], correct: 0 },
      { n: 3, diff: "easy", q: "Which item can be used again?", options: ["Reusable bottle", "Smoke", "Rain cloud", "Sunbeam"], correct: 0 },
      { n: 4, diff: "easy", q: "Which action keeps school clean?", options: ["Use a bin", "Drop litter", "Block drains", "Scatter paper"], correct: 0 },
      { n: 5, diff: "easy", q: "Which action is good for plants?", options: ["Care for them", "Throw litter on them", "Pour oil on them", "Break them"], correct: 0 },
      { n: 6, diff: "easy", q: "What can we plant for the future?", options: ["Trees", "Plastic bags", "Glass", "Metal cans"], correct: 0 },
      { n: 7, diff: "easy", q: "Which action saves paper?", options: ["Use both sides when suitable", "Tear clean sheets for fun", "Throw new paper away", "Wet all books"], correct: 0 },
      { n: 8, diff: "easy", q: "Which action reduces waste?", options: ["Reuse suitable items", "Throw everything away", "Scatter wrappers", "Burn plastic"], correct: 0 },
      { n: 9, diff: "easy", q: "Which helps keep school clean?", options: ["Litter bin", "Open dump by class", "Blocked gutter", "Plastic on grass"], correct: 0 },
      { n: 10, diff: "easy", q: "Who should care for shared school spaces?", options: ["Everyone", "Nobody", "Only visitors", "Only babies"], correct: 0 },
      { n: 11, diff: "easy", q: "Which resource should not be wasted?", options: ["Water", "Litter", "Smoke", "Dirt"], correct: 0 },
      { n: 12, diff: "easy", q: "Which habit protects a garden?", options: ["Water plants carefully", "Step on seedlings", "Throw plastic on soil", "Break stems"], correct: 0 },
      { n: 13, diff: "easy", q: "Which action saves food?", options: ["Take what you can eat", "Throw good food away", "Leave food to spoil", "Waste lunch"], correct: 0 },
      { n: 14, diff: "easy", q: "What should pupils do about a leaking tap?", options: ["Tell an adult", "Ignore it", "Open it wider", "Play with it"], correct: 0 },
      { n: 15, diff: "easy", q: "Which can make compost?", options: ["Suitable plant scraps", "Broken glass", "Batteries", "Plastic bags"], correct: 0 },
      { n: 16, diff: "easy", q: "Which school item can be reused?", options: ["Water bottle", "Smoke", "Dust", "Sunlight"], correct: 0 },
      { n: 17, diff: "easy", q: "Which action is kind to nature?", options: ["Protect a young tree", "Break branches", "Chase animals for fun", "Dump waste"], correct: 0 },
      { n: 18, diff: "easy", q: "Which action helps future pupils?", options: ["Care for resources today", "Waste everything today", "Pollute water", "Destroy plants"], correct: 0 },
      { n: 19, diff: "easy", q: "What is sustainability?", options: ["Using resources wisely now and for the future", "Littering", "Wasting", "Polluting"], correct: 0 },
      { n: 20, diff: "easy", q: "Which choice is responsible?", options: ["Close the tap", "Leave water running", "Drop wrappers", "Waste food"], correct: 0 },
      { n: 21, diff: "medium", q: "Why do we reuse suitable items?", options: ["To reduce waste", "To make more litter", "To dirty water", "To waste resources"], correct: 0 },
      { n: 22, diff: "medium", q: "Which lunch habit is more sustainable?", options: ["Use a reusable container", "Use many items once and litter them", "Waste food", "Throw bottles on the ground"], correct: 0 },
      { n: 23, diff: "medium", q: "Which school project supports sustainability?", options: ["Garden and recycling activity", "Litter competition", "Plastic burning", "Water wasting"], correct: 0 },
      { n: 24, diff: "medium", q: "Why should trees be cared for?", options: ["They are useful now and in the future", "They are litter", "They waste all water", "They make smoke"], correct: 0 },
      { n: 25, diff: "medium", q: "Which choice saves energy?", options: ["Use daylight when suitable", "Turn on every bulb in daytime", "Leave fans in empty rooms", "Open fridge for fun"], correct: 0 },
      { n: 26, diff: "medium", q: "Which choice saves water while brushing teeth?", options: ["Close tap while brushing", "Keep tap running", "Spill water", "Play with water"], correct: 0 },
      { n: 27, diff: "medium", q: "Which action reduces food waste?", options: ["Store food properly with adult help", "Leave food uncovered", "Throw fresh food away", "Take too much"], correct: 0 },
      { n: 28, diff: "medium", q: "What is one benefit of a school garden?", options: ["Learning how food grows", "Creating plastic waste", "Blocking drains", "Wasting soil"], correct: 0 },
      { n: 29, diff: "medium", q: "Which action shows wise use of resources?", options: ["Use only what you need", "Take more than you need", "Waste supplies", "Break shared tools"], correct: 0 },
      { n: 30, diff: "medium", q: "Why should school tools be cared for?", options: ["They can last longer", "They become food", "They make rain", "They create litter"], correct: 0 },
      { n: 31, diff: "medium", q: "Which action supports a cleaner future?", options: ["Reduce litter", "Increase litter", "Pollute streams", "Burn plastic"], correct: 0 },
      { n: 32, diff: "medium", q: "What can pupils do with a clean reusable container?", options: ["Use it again", "Throw it in a river", "Burn it", "Break it"], correct: 0 },
      { n: 33, diff: "medium", q: "Which habit connects health and sustainability?", options: ["Use clean water without wasting it", "Drink dirty water", "Leave taps open", "Throw waste in water"], correct: 0 },
      { n: 34, diff: "medium", q: "Why should we avoid wasting paper?", options: ["Resources are used to make it", "Paper is water", "Paper grows on desks", "Paper makes electricity"], correct: 0 },
      { n: 35, diff: "medium", q: "Which action protects future water supplies?", options: ["Keep water sources clean", "Throw waste into streams", "Pour oil into drains", "Leave rubbish near wells"], correct: 0 },
      { n: 36, diff: "medium", q: "Which is a responsible garden choice?", options: ["Compost suitable plant waste", "Add plastic litter", "Pour paint on soil", "Break seedlings"], correct: 0 },
      { n: 37, diff: "medium", q: "What does 'reduce' mean?", options: ["Use less when possible", "Use more and waste it", "Throw more away", "Scatter more litter"], correct: 0 },
      { n: 38, diff: "medium", q: "What does 'reuse' mean?", options: ["Use an item again safely", "Burn it", "Throw it away immediately", "Put it in a drain"], correct: 0 },
      { n: 39, diff: "medium", q: "Which action shows care for community property?", options: ["Use and return shared tools carefully", "Break tools", "Hide tools", "Leave tools in rain"], correct: 0 },
      { n: 40, diff: "medium", q: "Which class activity teaches sustainability?", options: ["Sorting reusable and non-reusable items", "Scattering waste", "Leaving taps open", "Breaking plants"], correct: 0 },
      { n: 41, diff: "hard", q: "Which plan saves food, water and energy together?", options: ["Take enough food, close taps and switch off unused lights", "Waste lunch, run taps and leave lights on", "Burn waste and flood paths", "Break bulbs and spill water"], correct: 0 },
      { n: 42, diff: "hard", q: "A class has used paper with blank backs. What is the best choice?", options: ["Reuse the blank sides for practice", "Throw them away at once", "Put them in a drain", "Burn them in class"], correct: 0 },
      { n: 43, diff: "hard", q: "Which action shows care for future pupils?", options: ["Protect school trees, water and equipment", "Destroy equipment", "Waste water", "Cut young plants"], correct: 0 },
      { n: 44, diff: "hard", q: "Why is a reusable bottle useful?", options: ["It can reduce repeated waste", "It always creates more litter", "It must be thrown away daily", "It wastes more by definition"], correct: 0 },
      { n: 45, diff: "hard", q: "Which project combines food and sustainability?", options: ["Grow vegetables and compost suitable scraps", "Throw vegetables away", "Cover soil with litter", "Waste harvested food"], correct: 0 },
      { n: 46, diff: "hard", q: "Which project combines water and sustainability?", options: ["Collect suitable rainwater for garden use", "Leave taps leaking", "Throw rubbish in gutters", "Waste clean water"], correct: 0 },
      { n: 47, diff: "hard", q: "Which project combines energy and sustainability?", options: ["Use sunlight and switch off unused electricity", "Keep lights on all day", "Burn rubbish for fun", "Run empty-room fans"], correct: 0 },
      { n: 48, diff: "hard", q: "Why is caring for shared resources a civic duty?", options: ["It helps everyone use them now and later", "It makes resources disappear faster", "It encourages waste", "It blocks learning"], correct: 0 },
      { n: 49, diff: "hard", q: "Which statement best describes sustainability?", options: ["Meeting needs while caring for resources for the future", "Using everything as fast as possible", "Throwing all used items away", "Ignoring plants and water"], correct: 0 },
      { n: 50, diff: "hard", q: "Which subjects can combine in a school-garden counting activity?", options: ["Basic Science, Mathematics and Social Studies", "Only music", "Only handwriting", "Only dance"], correct: 0 },
    ]
  },
]

export function p2CategoryBySlug(slug: string): QuizCategory | undefined {
  return P2_QUIZ.find((c) => c.slug === slug)
}
