// AUTO-GENERATED Primary 1 quiz bank — 250 questions, 5 categories.
// Do not edit by hand; regenerate from the source markdown.

export type QuizQuestion = { n: number; diff: 'easy'|'medium'|'hard'; q: string; options: string[]; correct: number }
export type QuizCategory = { slug: string; name: string; icon: string; color: string; badge: string; badgeIcon: string; questions: QuizQuestion[] }

export const P1_QUIZ: QuizCategory[] = [
  {
    slug: "food", name: "Food & Nutrition", icon: "\ud83c\udf4e",
    color: "#E0574C", badge: "Food Explorer", badgeIcon: "\ud83c\udf4e",
    questions: [
      { n: 1, diff: "easy", q: "Which food is a fruit?", options: ["Rice", "Mango", "Fish", "Egg"], correct: 1 },
      { n: 2, diff: "easy", q: "Which food is a vegetable?", options: ["Carrot", "Bread", "Milk", "Meat"], correct: 0 },
      { n: 3, diff: "easy", q: "Which food comes from a chicken?", options: ["Egg", "Yam", "Orange", "Beans"], correct: 0 },
      { n: 4, diff: "easy", q: "Which food comes from a plant?", options: ["Beans", "Fish", "Egg", "Milk"], correct: 0 },
      { n: 5, diff: "easy", q: "Which one is a healthy drink?", options: ["Clean water", "Ink", "Kerosene", "Paint"], correct: 0 },
      { n: 6, diff: "easy", q: "Which food is usually eaten after cooking?", options: ["Rice", "Stone", "Paper", "Soap"], correct: 0 },
      { n: 7, diff: "easy", q: "Which food can give us energy?", options: ["Yam", "Sand", "Plastic", "Chalk"], correct: 0 },
      { n: 8, diff: "easy", q: "Which one is a common Nigerian grain?", options: ["Rice", "Glass", "Cotton", "Rubber"], correct: 0 },
      { n: 9, diff: "easy", q: "Which food can help the body grow?", options: ["Egg", "Sweet wrapper", "Stone", "Paper"], correct: 0 },
      { n: 10, diff: "easy", q: "Which one should we wash before eating?", options: ["Fruit", "Book", "Pencil", "Shoe"], correct: 0 },
      { n: 11, diff: "easy", q: "What should you do before eating?", options: ["Wash hands", "Play in mud", "Touch waste", "Dirty the plate"], correct: 0 },
      { n: 12, diff: "easy", q: "Which food is a root crop?", options: ["Yam", "Mango", "Fish", "Milk"], correct: 0 },
      { n: 13, diff: "easy", q: "Which one is a legume?", options: ["Beans", "Orange", "Chicken", "Bread"], correct: 0 },
      { n: 14, diff: "easy", q: "Which food comes from a cow?", options: ["Milk", "Rice", "Yam", "Maize"], correct: 0 },
      { n: 15, diff: "easy", q: "Which is good for breakfast?", options: ["Pap", "Sand", "Soap", "Paper"], correct: 0 },
      { n: 16, diff: "easy", q: "Which part of a plant can we eat?", options: ["Leaf", "Plastic", "Nail", "Glass"], correct: 0 },
      { n: 17, diff: "easy", q: "Which food is yellow when ripe?", options: ["Banana", "Spinach", "Charcoal", "Salt"], correct: 0 },
      { n: 18, diff: "easy", q: "Which food is often made from maize?", options: ["Pap", "Soap", "Paint", "Glass"], correct: 0 },
      { n: 19, diff: "easy", q: "Where can vegetables grow?", options: ["Garden", "Cupboard", "Television", "School bag"], correct: 0 },
      { n: 20, diff: "easy", q: "Which one is food?", options: ["Tomato", "Pencil", "Spoon", "Stone"], correct: 0 },
      { n: 21, diff: "medium", q: "Why do we eat food?", options: ["To grow and get energy", "To make clothes", "To make rain", "To dirty plates"], correct: 0 },
      { n: 22, diff: "medium", q: "Which meal has both plant and animal food?", options: ["Rice and fish", "Stone and sand", "Paper and pencil", "Soap and water"], correct: 0 },
      { n: 23, diff: "medium", q: "Which is the safest fruit to eat?", options: ["Washed orange", "Dirty mango", "Rotten banana", "Fruit from the floor"], correct: 0 },
      { n: 24, diff: "medium", q: "Which action keeps food clean?", options: ["Covering it", "Leaving it open", "Putting it on the floor", "Touching it with dirty hands"], correct: 0 },
      { n: 25, diff: "medium", q: "Which food group includes orange and mango?", options: ["Fruits", "Meat", "Grains", "Oils"], correct: 0 },
      { n: 26, diff: "medium", q: "A child needs strong bones. Which food can help?", options: ["Milk", "Sweet", "Soft drink", "Sugar"], correct: 0 },
      { n: 27, diff: "medium", q: "Which is a better snack?", options: ["Banana", "Dirty paper", "Many sweets", "Raw soap"], correct: 0 },
      { n: 28, diff: "medium", q: "What can happen to uncovered food?", options: ["Flies may land on it", "It becomes a book", "It turns to water", "It grows wheels"], correct: 0 },
      { n: 29, diff: "medium", q: "Which is a good food-hygiene habit?", options: ["Use a clean plate", "Use a dirty spoon", "Eat with muddy hands", "Leave food near waste"], correct: 0 },
      { n: 30, diff: "medium", q: "Which food is harvested from a farm?", options: ["Maize", "Plastic", "Metal", "Glass"], correct: 0 },
      { n: 31, diff: "medium", q: "Which meal can give energy for play?", options: ["Yam and beans", "Soap and water", "Paper and ink", "Sand and stones"], correct: 0 },
      { n: 32, diff: "medium", q: "Why should fruits be washed?", options: ["To remove dirt", "To make them toys", "To change their colour", "To make them harder"], correct: 0 },
      { n: 33, diff: "medium", q: "Which is an example of a balanced food choice for a child?", options: ["Rice, beans and vegetables", "Only sweets", "Only soft drink", "Only sugar"], correct: 0 },
      { n: 34, diff: "medium", q: "What should you do with rotten food?", options: ["Tell an adult and avoid it", "Eat it quickly", "Hide it", "Give it to a friend"], correct: 0 },
      { n: 35, diff: "medium", q: "Which farm activity gives us food?", options: ["Planting crops", "Breaking glass", "Burning plastic", "Throwing litter"], correct: 0 },
      { n: 36, diff: "medium", q: "Which food contains a seed?", options: ["Orange", "Milk", "Fish", "Egg"], correct: 0 },
      { n: 37, diff: "medium", q: "Which pair comes mainly from plants?", options: ["Rice and beans", "Fish and egg", "Milk and meat", "Chicken and fish"], correct: 0 },
      { n: 38, diff: "medium", q: "Which is a reason to grow a school garden?", options: ["To learn and grow food", "To make more litter", "To waste water", "To destroy soil"], correct: 0 },
      { n: 39, diff: "medium", q: "Which tool can help carry harvested vegetables?", options: ["Basket", "Television", "Pillow", "Clock"], correct: 0 },
      { n: 40, diff: "medium", q: "If you are hungry at school, which choice is healthier?", options: ["Fruit", "Many sweets", "Soft drink only", "Ice candy only"], correct: 0 },
      { n: 41, diff: "hard", q: "Which choice shows a food chain beginning with a plant?", options: ["Maize → chicken → child", "Child → maize → chicken", "Chicken → stone → child", "Fish → plastic → maize"], correct: 0 },
      { n: 42, diff: "hard", q: "A garden has tomato, carrot and lettuce. What do they all provide?", options: ["Food from plants", "Electricity", "Plastic", "Fuel"], correct: 0 },
      { n: 43, diff: "hard", q: "Why is eating different kinds of healthy food useful?", options: ["The body gets different nutrients", "Food becomes toys", "We never need water", "It stops plants growing"], correct: 0 },
      { n: 44, diff: "hard", q: "Which action reduces food waste?", options: ["Take only what you can eat", "Throw good food away", "Leave food uncovered", "Step on vegetables"], correct: 0 },
      { n: 45, diff: "hard", q: "A farmer plants maize seeds. What is most likely to happen with water and care?", options: ["They can grow into maize plants", "They become stones", "They become fish", "They become plastic"], correct: 0 },
      { n: 46, diff: "hard", q: "Which choice best links food and water?", options: ["Plants need water to grow", "Food makes water dirty", "Plants never need water", "Only plates need water"], correct: 0 },
      { n: 47, diff: "hard", q: "Why should a garden soil be kept free from litter?", options: ["Plants can grow in a cleaner place", "Litter feeds every plant", "Plastic becomes rain", "Glass makes soil soft"], correct: 0 },
      { n: 48, diff: "hard", q: "Which lunch best combines energy, body-building and protective foods?", options: ["Rice, beans and vegetables", "Sugar only", "Sweets and soft drink", "Salt only"], correct: 0 },
      { n: 49, diff: "hard", q: "If clean food falls into dirty water, what should a child do?", options: ["Do not eat it; tell an adult", "Eat it at once", "Give it to another child", "Put it back on the plate"], correct: 0 },
      { n: 50, diff: "hard", q: "Which classroom subject can use counting to study harvested tomatoes?", options: ["Mathematics", "Music only", "Handwriting only", "Drama only"], correct: 0 },
    ],
  },
  {
    slug: "energy", name: "Energy & Water", icon: "\ud83d\udca7",
    color: "#3E7CA6", badge: "Energy & Water Hero", badgeIcon: "\ud83d\udca7",
    questions: [
      { n: 51, diff: "easy", q: "What do we drink when we are thirsty?", options: ["Clean water", "Sand", "Smoke", "Oil"], correct: 0 },
      { n: 52, diff: "easy", q: "Which gives us light in the daytime?", options: ["Sun", "Chair", "Shoe", "Spoon"], correct: 0 },
      { n: 53, diff: "easy", q: "Which one uses electricity?", options: ["Fan", "Stone", "Leaf", "Cup"], correct: 0 },
      { n: 54, diff: "easy", q: "Which one can hold water?", options: ["Bucket", "Net", "Paper sheet", "Broom"], correct: 0 },
      { n: 55, diff: "easy", q: "Where does rain come from?", options: ["Clouds", "Shoes", "Books", "Roads"], correct: 0 },
      { n: 56, diff: "easy", q: "Which water is safest to drink?", options: ["Clean water", "Dirty puddle water", "Gutter water", "Soapy water"], correct: 0 },
      { n: 57, diff: "easy", q: "What can the sun give us?", options: ["Light and heat", "Plastic", "Bread", "Shoes"], correct: 0 },
      { n: 58, diff: "easy", q: "Which appliance can keep food cold?", options: ["Refrigerator", "Broom", "Plate", "Basket"], correct: 0 },
      { n: 59, diff: "easy", q: "Which action saves water?", options: ["Close the tap", "Leave the tap running", "Spill water", "Play with the tap"], correct: 0 },
      { n: 60, diff: "easy", q: "Which action saves electricity?", options: ["Switch off unused light", "Leave every light on", "Open the tap", "Throw litter"], correct: 0 },
      { n: 61, diff: "easy", q: "What do plants need to grow?", options: ["Water", "Plastic", "Smoke", "Glass"], correct: 0 },
      { n: 62, diff: "easy", q: "Which is a source of water?", options: ["Rain", "Dust", "Smoke", "Plastic"], correct: 0 },
      { n: 63, diff: "easy", q: "Which can move air in a room?", options: ["Fan", "Plate", "Book", "Cup"], correct: 0 },
      { n: 64, diff: "easy", q: "Which energy source is seen in the sky?", options: ["Sun", "Battery", "Generator", "Bulb"], correct: 0 },
      { n: 65, diff: "easy", q: "What should you use to wash your hands?", options: ["Clean water", "Kerosene", "Paint", "Ink"], correct: 0 },
      { n: 66, diff: "easy", q: "Which is used for cooking in some homes?", options: ["Gas", "Sand", "Paper clip", "Chalk"], correct: 0 },
      { n: 67, diff: "easy", q: "Which can make a bulb shine?", options: ["Electricity", "Soil", "Leaf", "Food"], correct: 0 },
      { n: 68, diff: "easy", q: "What should you do after using a tap?", options: ["Close it", "Break it", "Leave it open", "Fill the floor"], correct: 0 },
      { n: 69, diff: "easy", q: "Which water body is large?", options: ["River", "Cup", "Spoon", "Bottle cap"], correct: 0 },
      { n: 70, diff: "easy", q: "Which one needs water?", options: ["A growing plant", "A stone", "A plastic chair", "A metal spoon"], correct: 0 },
      { n: 71, diff: "medium", q: "Why should we save water?", options: ["Water is useful and should not be wasted", "Water is litter", "Water is a toy", "Water is always dirty"], correct: 0 },
      { n: 72, diff: "medium", q: "Which activity needs water?", options: ["Bathing", "Reading a dry book", "Drawing with pencil", "Counting"], correct: 0 },
      { n: 73, diff: "medium", q: "Which is a clean-energy source?", options: ["Sunlight", "Burning rubbish", "Smoke", "Dirty oil spill"], correct: 0 },
      { n: 74, diff: "medium", q: "Why do we switch off a fan when leaving a room?", options: ["To save electricity", "To waste electricity", "To make water", "To grow litter"], correct: 0 },
      { n: 75, diff: "medium", q: "Which action can make water dirty?", options: ["Throwing waste into it", "Covering a clean container", "Closing a tap", "Using a clean cup"], correct: 0 },
      { n: 76, diff: "medium", q: "What can solar panels use to make electricity?", options: ["Sunlight", "Mud", "Plastic bags", "Food"], correct: 0 },
      { n: 77, diff: "medium", q: "Which water should be kept covered?", options: ["Drinking water", "Paint water", "Gutter water", "Muddy puddle"], correct: 0 },
      { n: 78, diff: "medium", q: "Which is a good way to water a small plant?", options: ["Use only the water it needs", "Flood the whole yard", "Leave tap running", "Pour dirty oil"], correct: 0 },
      { n: 79, diff: "medium", q: "Which pair both need energy to work?", options: ["Fan and television", "Stone and leaf", "Cup and plate", "Book and pencil"], correct: 0 },
      { n: 80, diff: "medium", q: "Why is clean water important?", options: ["It supports health", "It makes litter", "It breaks books", "It creates smoke"], correct: 0 },
      { n: 81, diff: "medium", q: "Which action protects a stream?", options: ["Keep rubbish out", "Throw plastic in", "Pour dirty oil in", "Wash waste into it"], correct: 0 },
      { n: 82, diff: "medium", q: "A bulb is on in an empty room. What should you do?", options: ["Switch it off safely", "Leave it on all day", "Break it", "Pour water on it"], correct: 0 },
      { n: 83, diff: "medium", q: "What happens when rain falls on a garden?", options: ["Soil and plants get water", "The sun disappears forever", "Plants become plastic", "Soil becomes glass"], correct: 0 },
      { n: 84, diff: "medium", q: "Which item can collect rainwater?", options: ["Clean tank", "Open shoe", "Broom", "Pencil"], correct: 0 },
      { n: 85, diff: "medium", q: "Which is a safe rule near electricity?", options: ["Keep wet hands away from sockets", "Touch sockets with wet hands", "Put metal in sockets", "Pour water on wires"], correct: 0 },
      { n: 86, diff: "medium", q: "What can wind do?", options: ["Move leaves", "Turn water into plastic", "Make stones eat", "Grow shoes"], correct: 0 },
      { n: 87, diff: "medium", q: "Which is renewable energy?", options: ["Solar energy", "Petrol", "Diesel", "Kerosene"], correct: 0 },
      { n: 88, diff: "medium", q: "Which habit saves both water and money?", options: ["Fix a leaking tap", "Ignore leaks", "Leave taps open", "Spill stored water"], correct: 0 },
      { n: 89, diff: "medium", q: "Why do farmers water crops?", options: ["Crops need water to grow", "To make plastic", "To make smoke", "To wash the sky"], correct: 0 },
      { n: 90, diff: "medium", q: "Which choice uses less water?", options: ["Turn tap off while soaping hands", "Keep tap running while soaping", "Play with hose", "Pour clean water away"], correct: 0 },
      { n: 91, diff: "hard", q: "Which sequence shows a simple use of solar energy?", options: ["Sun → solar panel → electricity", "Bulb → sun → rain", "Water → plastic → sun", "Soil → fan → cloud"], correct: 0 },
      { n: 92, diff: "hard", q: "A tap leaks all day. What is the main problem?", options: ["Useful water is wasted", "More food is made", "Electricity is stored", "The air becomes solid"], correct: 0 },
      { n: 93, diff: "hard", q: "Why should water containers be covered?", options: ["To help keep dirt out", "To collect litter", "To make water salty", "To waste water"], correct: 0 },
      { n: 94, diff: "hard", q: "Which action links water conservation and gardening?", options: ["Water plants carefully near their roots", "Flood paths every day", "Wash soil away", "Leave hose running"], correct: 0 },
      { n: 95, diff: "hard", q: "A school wants lower electricity use. Which plan is best?", options: ["Turn off unused lights and fans", "Keep all appliances on", "Add more lights in empty rooms", "Run fans outdoors"], correct: 0 },
      { n: 96, diff: "hard", q: "Which statement is true about the sun?", options: ["It is a natural source of light and heat", "It is made by a bulb", "It is a water tap", "It is a plant root"], correct: 0 },
      { n: 97, diff: "hard", q: "Why should children not play near exposed wires?", options: ["They can be dangerous", "They make food grow", "They clean water", "They are toys"], correct: 0 },
      { n: 98, diff: "hard", q: "Which two resources are both important for growing crops?", options: ["Sunlight and water", "Plastic and smoke", "Glass and paint", "Ink and rubber"], correct: 0 },
      { n: 99, diff: "hard", q: "If rainwater is collected for a garden, what resource is being reused?", options: ["Water", "Plastic", "Smoke", "Electricity"], correct: 0 },
      { n: 100, diff: "hard", q: "Which school subject can help pupils count cups of water used?", options: ["Mathematics", "Dance only", "Singing only", "Storytelling only"], correct: 0 },
    ],
  },
  {
    slug: "environment", name: "Environment", icon: "\ud83c\udf31",
    color: "#5C9E3A", badge: "Green Guardian", badgeIcon: "\ud83c\udf31",
    questions: [
      { n: 101, diff: "easy", q: "What is around us?", options: ["Environment", "Only food", "Only books", "Only toys"], correct: 0 },
      { n: 102, diff: "easy", q: "Which one is a living thing?", options: ["Tree", "Stone", "Bottle", "Chair"], correct: 0 },
      { n: 103, diff: "easy", q: "Which one is non-living?", options: ["Rock", "Goat", "Grass", "Bird"], correct: 0 },
      { n: 104, diff: "easy", q: "Where should litter go?", options: ["Bin", "Road", "River", "Garden bed"], correct: 0 },
      { n: 105, diff: "easy", q: "Which animal can fly?", options: ["Bird", "Goat", "Fish", "Dog"], correct: 0 },
      { n: 106, diff: "easy", q: "Which plant part is usually green?", options: ["Leaf", "Root", "Seed coat", "Dry stick"], correct: 0 },
      { n: 107, diff: "easy", q: "Which place should be kept clean?", options: ["Classroom", "Only cupboard", "Only bag", "Nowhere"], correct: 0 },
      { n: 108, diff: "easy", q: "Which one grows in soil?", options: ["Plant", "Plastic bottle", "Metal spoon", "Glass cup"], correct: 0 },
      { n: 109, diff: "easy", q: "Which animal lives in water?", options: ["Fish", "Goat", "Chicken", "Cat"], correct: 0 },
      { n: 110, diff: "easy", q: "What can we plant to make a place greener?", options: ["Tree", "Plastic", "Glass", "Tin"], correct: 0 },
      { n: 111, diff: "easy", q: "Which is natural?", options: ["Soil", "Plastic bag", "Metal can", "Glass bottle"], correct: 0 },
      { n: 112, diff: "easy", q: "Which is made by people?", options: ["Chair", "Tree", "River", "Cloud"], correct: 0 },
      { n: 113, diff: "easy", q: "What do we breathe?", options: ["Air", "Soil", "Plastic", "Juice"], correct: 0 },
      { n: 114, diff: "easy", q: "Which helps keep a classroom clean?", options: ["Broom", "Litter", "Mud", "Smoke"], correct: 0 },
      { n: 115, diff: "easy", q: "Which one can pollute the ground?", options: ["Litter", "Flower", "Clean soil", "Tree"], correct: 0 },
      { n: 116, diff: "easy", q: "Which animal may live on a farm?", options: ["Goat", "Shark", "Whale", "Dolphin"], correct: 0 },
      { n: 117, diff: "easy", q: "Which should we protect?", options: ["Plants and animals", "Only litter", "Smoke", "Dirty water"], correct: 0 },
      { n: 118, diff: "easy", q: "What colour are many healthy leaves?", options: ["Green", "Silver", "Black only", "Purple only"], correct: 0 },
      { n: 119, diff: "easy", q: "Which can provide shade?", options: ["Tree", "Spoon", "Pencil", "Cup"], correct: 0 },
      { n: 120, diff: "easy", q: "What should we do with a school garden?", options: ["Care for it", "Destroy it", "Fill it with litter", "Step on plants"], correct: 0 },
      { n: 121, diff: "medium", q: "Why should we use a waste bin?", options: ["To keep the area clean", "To spread litter", "To dirty water", "To harm plants"], correct: 0 },
      { n: 122, diff: "medium", q: "Which action protects animals?", options: ["Keep their habitat clean", "Destroy nests", "Throw waste in ponds", "Chase them for fun"], correct: 0 },
      { n: 123, diff: "medium", q: "What may happen when litter blocks a drain?", options: ["Water may not flow well", "Trees become books", "Sun stops shining", "Fish grow on roads"], correct: 0 },
      { n: 124, diff: "medium", q: "Which is a good environmental habit?", options: ["Pick up litter safely", "Throw wrappers down", "Burn plastic near class", "Pour oil on soil"], correct: 0 },
      { n: 125, diff: "medium", q: "Why are trees useful?", options: ["They provide shade and habitat", "They make plastic", "They create litter only", "They stop all rain"], correct: 0 },
      { n: 126, diff: "medium", q: "Which pair contains living things?", options: ["Grass and bird", "Rock and chair", "Cup and plate", "Book and pencil"], correct: 0 },
      { n: 127, diff: "medium", q: "Which pair contains non-living things?", options: ["Stone and bottle", "Tree and goat", "Bird and grass", "Fish and flower"], correct: 0 },
      { n: 128, diff: "medium", q: "Which action can harm soil?", options: ["Dumping waste on it", "Planting a seed", "Adding compost", "Keeping it clean"], correct: 0 },
      { n: 129, diff: "medium", q: "What is a habitat?", options: ["A place where a living thing lives", "A type of pencil", "A food plate", "A school bell"], correct: 0 },
      { n: 130, diff: "medium", q: "Which habitat suits a fish?", options: ["Water", "Dry cupboard", "School desk", "Roof"], correct: 0 },
      { n: 131, diff: "medium", q: "Why should we avoid stepping on young plants?", options: ["They can be damaged", "They become stronger shoes", "They make plastic", "They stop needing water"], correct: 0 },
      { n: 132, diff: "medium", q: "Which action helps a school compound?", options: ["Plant flowers", "Scatter waste", "Break branches", "Block drains"], correct: 0 },
      { n: 133, diff: "medium", q: "Which can be reused?", options: ["Clean bottle", "Smoke", "Sunlight", "Noise"], correct: 0 },
      { n: 134, diff: "medium", q: "What should happen to dry leaves in a garden when appropriate?", options: ["They can be composted", "Put in drinking water", "Put in sockets", "Throw into class"], correct: 0 },
      { n: 135, diff: "medium", q: "Which action keeps air cleaner?", options: ["Avoid burning rubbish", "Burn plastic", "Make more smoke", "Burn tyres"], correct: 0 },
      { n: 136, diff: "medium", q: "Why should drains be kept clear?", options: ["So water can flow", "So litter can grow", "So fish can fly", "So roads become rivers"], correct: 0 },
      { n: 137, diff: "medium", q: "Which activity helps us observe nature?", options: ["Looking at plants and insects", "Throwing stones at birds", "Breaking leaves", "Dumping waste"], correct: 0 },
      { n: 138, diff: "medium", q: "What can a tree be home to?", options: ["Birds and insects", "Televisions", "Cars", "Shoes"], correct: 0 },
      { n: 139, diff: "medium", q: "Which is better for a garden?", options: ["Compost from suitable plant waste", "Broken glass", "Plastic litter", "Dirty oil"], correct: 0 },
      { n: 140, diff: "medium", q: "Why do we clean our surroundings?", options: ["For health and a better environment", "To make more waste", "To block paths", "To dirty water"], correct: 0 },
      { n: 141, diff: "hard", q: "Which action shows care for both land and water?", options: ["Put waste in bins, not drains", "Throw waste into a stream", "Leave litter on soil", "Pour oil into gutters"], correct: 0 },
      { n: 142, diff: "hard", q: "A butterfly visits a flower. What part of the environment is shown?", options: ["Living things interacting", "Only non-living things", "Electricity use", "Water pollution"], correct: 0 },
      { n: 143, diff: "hard", q: "If many trees are removed, which benefit may be reduced?", options: ["Shade and animal habitat", "Plastic production", "Metal production", "Road signs"], correct: 0 },
      { n: 144, diff: "hard", q: "Which school plan best improves the environment?", options: ["Bins, clean-up and tree planting", "More litter and smoke", "Blocked drains", "Burning plastics"], correct: 0 },
      { n: 145, diff: "hard", q: "Why is soil important in a garden?", options: ["It supports plant growth", "It powers televisions", "It makes plastic bags", "It is a type of rain"], correct: 0 },
      { n: 146, diff: "hard", q: "Which example shows reuse?", options: ["Using a clean container again", "Throwing it away at once", "Burning it", "Putting it in a river"], correct: 0 },
      { n: 147, diff: "hard", q: "What is the best reason not to throw plastic in a river?", options: ["It can pollute the water and harm life", "It makes water sweeter", "It feeds every fish", "It turns into rain"], correct: 0 },
      { n: 148, diff: "hard", q: "Which observation belongs in Basic Science?", options: ["A seed grows into a plant", "A chair is a sentence", "A song is a number", "A pencil is rain"], correct: 0 },
      { n: 149, diff: "hard", q: "Which action shows civic responsibility at school?", options: ["Keeping shared spaces clean", "Scattering wrappers", "Breaking plants", "Blocking walkways"], correct: 0 },
      { n: 150, diff: "hard", q: "Which choice connects health and environment?", options: ["Clean surroundings reduce contact with dirt and waste", "More litter improves health", "Dirty water is always safe", "Smoke makes air cleaner"], correct: 0 },
    ],
  },
  {
    slug: "climate", name: "Climate Literacy", icon: "\ud83c\udf26\ufe0f",
    color: "#C8912E", badge: "Climate Champion", badgeIcon: "\ud83c\udf26\ufe0f",
    questions: [
      { n: 151, diff: "easy", q: "What is the weather like when rain is falling?", options: ["Rainy", "Dry only", "Snowy always", "Windless always"], correct: 0 },
      { n: 152, diff: "easy", q: "What do we see in the sky on a sunny day?", options: ["Sun", "Fish", "Chair", "Spoon"], correct: 0 },
      { n: 153, diff: "easy", q: "Which can move leaves?", options: ["Wind", "Stone", "Book", "Plate"], correct: 0 },
      { n: 154, diff: "easy", q: "Which comes from clouds?", options: ["Rain", "Sand", "Plastic", "Smoke"], correct: 0 },
      { n: 155, diff: "easy", q: "What can we use on a rainy day?", options: ["Umbrella", "Pillow", "Plate", "Broom"], correct: 0 },
      { n: 156, diff: "easy", q: "What can we wear when the day is hot?", options: ["Light clothing", "Heavy blanket", "Rain boot only", "Winter coat"], correct: 0 },
      { n: 157, diff: "easy", q: "Which word describes a day with much sun?", options: ["Sunny", "Rainy", "Cloudy only", "Flooded"], correct: 0 },
      { n: 158, diff: "easy", q: "Which word describes moving air?", options: ["Wind", "Soil", "Food", "Rock"], correct: 0 },
      { n: 159, diff: "easy", q: "Which can cover the sky?", options: ["Clouds", "Shoes", "Tables", "Bottles"], correct: 0 },
      { n: 160, diff: "easy", q: "Which weather can make us feel cold?", options: ["Cool weather", "Hot sun", "Warm room", "Cooking fire"], correct: 0 },
      { n: 161, diff: "easy", q: "What can rain help plants do?", options: ["Grow", "Become plastic", "Turn to stone", "Stop needing soil"], correct: 0 },
      { n: 162, diff: "easy", q: "Which weather may dry wet clothes faster?", options: ["Sunny weather", "Heavy rain", "Flood", "Storm rain"], correct: 0 },
      { n: 163, diff: "easy", q: "Which item helps protect us from strong sun?", options: ["Hat", "Plate", "Spoon", "Book"], correct: 0 },
      { n: 164, diff: "easy", q: "What do we call water falling from clouds?", options: ["Rain", "Wind", "Soil", "Heat"], correct: 0 },
      { n: 165, diff: "easy", q: "Which weather may make puddles?", options: ["Rainy weather", "Dry sunny weather", "No weather", "Only wind"], correct: 0 },
      { n: 166, diff: "easy", q: "Which can tell us how hot or cold it is?", options: ["Thermometer", "Broom", "Cup", "Basket"], correct: 0 },
      { n: 167, diff: "easy", q: "Which season has rainfall in many parts of Nigeria?", options: ["Rainy season", "Dry season only", "Snow season", "Ice season"], correct: 0 },
      { n: 168, diff: "easy", q: "Which season is often drier in Nigeria?", options: ["Dry season", "Rainy season", "Snow season", "Ice season"], correct: 0 },
      { n: 169, diff: "easy", q: "Which weather should make us seek safe shelter?", options: ["Thunderstorm", "Gentle sunshine", "Light breeze", "Clear sky"], correct: 0 },
      { n: 170, diff: "easy", q: "What should children do during dangerous weather?", options: ["Follow adult safety instructions", "Run into floodwater", "Touch fallen wires", "Stand under unsafe objects"], correct: 0 },
      { n: 171, diff: "medium", q: "What is weather?", options: ["The condition of the air outside at a time", "A kind of food", "A school subject only", "A type of soil"], correct: 0 },
      { n: 172, diff: "medium", q: "Which is a weather observation?", options: ["The day is cloudy", "The desk is brown", "The book is new", "The bag is heavy"], correct: 0 },
      { n: 173, diff: "medium", q: "Why do farmers watch rainfall?", options: ["Crops need suitable water", "Rain makes plastic", "Rain powers pencils", "Rain stops all growth"], correct: 0 },
      { n: 174, diff: "medium", q: "Which weather can increase the need for drinking water?", options: ["Hot weather", "Cool rainy weather", "Cloudy weather only", "Nighttime only"], correct: 0 },
      { n: 175, diff: "medium", q: "What should you do in very hot sunshine?", options: ["Drink water and stay safely shaded when needed", "Avoid water", "Wear many heavy blankets", "Play on hot metal"], correct: 0 },
      { n: 176, diff: "medium", q: "Which event can happen after very heavy rain?", options: ["Flooding", "Snow in every Nigerian town", "Sun disappears forever", "Trees become metal"], correct: 0 },
      { n: 177, diff: "medium", q: "Why should children avoid floodwater?", options: ["It can be unsafe", "It is always clean", "It is a playground", "It is drinking water"], correct: 0 },
      { n: 178, diff: "medium", q: "Which action helps us learn about weather?", options: ["Observe sky, rain and wind", "Throw litter", "Break a thermometer", "Close every window forever"], correct: 0 },
      { n: 179, diff: "medium", q: "Which tool measures temperature?", options: ["Thermometer", "Ruler", "Basket", "Spoon"], correct: 0 },
      { n: 180, diff: "medium", q: "Which sign may show rain is coming?", options: ["Dark rain clouds", "A clean plate", "A closed book", "A dry pencil"], correct: 0 },
      { n: 181, diff: "medium", q: "How can trees help on a hot day?", options: ["Provide shade", "Make more plastic", "Stop all wind", "Turn heat into food"], correct: 0 },
      { n: 182, diff: "medium", q: "Which activity is safer during lightning?", options: ["Stay in a safe building", "Stand in an open field", "Touch metal poles", "Play in floodwater"], correct: 0 },
      { n: 183, diff: "medium", q: "Why is rainfall important to a garden?", options: ["It supplies water", "It supplies plastic", "It supplies glass", "It supplies pencils"], correct: 0 },
      { n: 184, diff: "medium", q: "Which is a simple way to record weather?", options: ["Draw a sun or rain symbol on a chart", "Throw away observations", "Break the chart", "Guess without looking"], correct: 0 },
      { n: 185, diff: "medium", q: "If the weather is windy, what may you observe?", options: ["Leaves moving", "Rocks eating", "Water becoming glass", "Books growing"], correct: 0 },
      { n: 186, diff: "medium", q: "What is climate in simple terms?", options: ["Usual weather pattern of a place over a long time", "Weather for one minute only", "A type of food", "A school bag"], correct: 0 },
      { n: 187, diff: "medium", q: "Which is about weather, not climate?", options: ["It is raining this morning", "This place is usually wet for many years", "A region is often hot and dry", "A place has a long rainy season"], correct: 0 },
      { n: 188, diff: "medium", q: "Which can help reduce heat around a schoolyard?", options: ["Trees and shade", "Bare hot ground only", "Burning rubbish", "More smoke"], correct: 0 },
      { n: 189, diff: "medium", q: "Why should we keep water during dry periods?", options: ["Water may be less available", "To make litter", "To waste it later", "To dirty it"], correct: 0 },
      { n: 190, diff: "medium", q: "Which action helps prepare for rain?", options: ["Keep drains clear", "Block drains with waste", "Throw plastic in gutters", "Leave rubbish in waterways"], correct: 0 },
      { n: 191, diff: "hard", q: "Which statement best shows the difference between weather and climate?", options: ["Weather is short-term; climate is the usual pattern over many", "Weather and climate are exactly the same", "Climate changes every minute", "Weather only means rain"], correct: 0 },
      { n: 192, diff: "hard", q: "A week has many very hot days. What should pupils do?", options: ["Use shade, drink water and follow safety advice", "Avoid drinking water", "Burn rubbish", "Play on hot surfaces"], correct: 0 },
      { n: 193, diff: "hard", q: "How can blocked drains make heavy rain worse?", options: ["Water may collect and cause flooding", "They make rain stop", "They cool the sun", "They make clouds disappear"], correct: 0 },
      { n: 194, diff: "hard", q: "Which school action supports climate learning?", options: ["Keep a simple daily weather chart", "Ignore weather", "Burn leaves for smoke", "Waste water"], correct: 0 },
      { n: 195, diff: "hard", q: "Why can planting trees help people on hot days?", options: ["Trees can provide cooling shade", "Trees make petrol", "Trees stop every storm", "Trees create plastic"], correct: 0 },
      { n: 196, diff: "hard", q: "Which example is an adaptation to hot weather?", options: ["Using shade and drinking enough water", "Leaving taps running", "Burning plastic", "Removing all trees"], correct: 0 },
      { n: 197, diff: "hard", q: "Which example helps reduce unnecessary energy use?", options: ["Switching off unused lights", "Leaving lights on all day", "Running empty-room fans", "Opening refrigerator doors"], correct: 0 },
      { n: 198, diff: "hard", q: "A school garden gets little rain. What is a sensible response?", options: ["Water carefully and avoid waste", "Flood the road", "Remove all plants at once", "Leave taps open"], correct: 0 },
      { n: 199, diff: "hard", q: "Why do we learn about climate and weather?", options: ["To make safer and wiser choices", "To control the sun", "To stop all rain", "To create clouds by hand"], correct: 0 },
      { n: 200, diff: "hard", q: "Which subjects can combine in a weather chart activity?", options: ["Basic Science and Mathematics", "Only singing", "Only handwriting", "Only drama"], correct: 0 },
    ],
  },
  {
    slug: "sustainability", name: "Sustainability", icon: "\u267b\ufe0f",
    color: "#7A7488", badge: "Sustainability Star", badgeIcon: "\u267b\ufe0f",
    questions: [
      { n: 201, diff: "easy", q: "What should we do with water?", options: ["Use it wisely", "Waste it", "Dirty it", "Spill it"], correct: 0 },
      { n: 202, diff: "easy", q: "What should we do with unused lights?", options: ["Switch them off", "Leave them on", "Break them", "Wet them"], correct: 0 },
      { n: 203, diff: "easy", q: "Which item can be used again?", options: ["Reusable bottle", "Smoke", "Rain cloud", "Sunbeam"], correct: 0 },
      { n: 204, diff: "easy", q: "Which action keeps school clean?", options: ["Use a bin", "Drop litter", "Block drains", "Scatter paper"], correct: 0 },
      { n: 205, diff: "easy", q: "Which is good for plants?", options: ["Care", "Litter", "Oil spill", "Broken glass"], correct: 0 },
      { n: 206, diff: "easy", q: "What can we plant for the future?", options: ["Trees", "Plastic bags", "Glass", "Metal cans"], correct: 0 },
      { n: 207, diff: "easy", q: "Which action saves paper?", options: ["Use both sides when suitable", "Tear clean sheets for fun", "Throw new paper away", "Wet all books"], correct: 0 },
      { n: 208, diff: "easy", q: "Which action reduces waste?", options: ["Reuse suitable items", "Throw everything away", "Scatter wrappers", "Burn plastic"], correct: 0 },
      { n: 209, diff: "easy", q: "Which is better for a clean school?", options: ["Litter bin", "Open dump by class", "Blocked gutter", "Plastic on grass"], correct: 0 },
      { n: 210, diff: "easy", q: "Who should care for shared school spaces?", options: ["Everyone", "Nobody", "Only visitors", "Only babies"], correct: 0 },
      { n: 211, diff: "easy", q: "Which resource should not be wasted?", options: ["Water", "Litter", "Smoke", "Dirt"], correct: 0 },
      { n: 212, diff: "easy", q: "Which habit protects a garden?", options: ["Water plants carefully", "Step on seedlings", "Throw plastic on soil", "Break stems"], correct: 0 },
      { n: 213, diff: "easy", q: "Which action saves food?", options: ["Take what you can eat", "Throw good food away", "Leave food to spoil", "Waste lunch"], correct: 0 },
      { n: 214, diff: "easy", q: "What should we do with a leaking tap?", options: ["Tell an adult", "Ignore it", "Open it wider", "Play with it"], correct: 0 },
      { n: 215, diff: "easy", q: "Which can make useful compost?", options: ["Suitable plant scraps", "Broken glass", "Batteries", "Plastic bags"], correct: 0 },
      { n: 216, diff: "easy", q: "Which is a reusable school item?", options: ["Water bottle", "Smoke", "Dust", "Sunlight"], correct: 0 },
      { n: 217, diff: "easy", q: "Which action is kind to nature?", options: ["Protect a young tree", "Break branches", "Chase animals for fun", "Dump waste"], correct: 0 },
      { n: 218, diff: "easy", q: "Which action helps tomorrow?", options: ["Care for resources today", "Waste everything today", "Pollute water", "Destroy plants"], correct: 0 },
      { n: 219, diff: "easy", q: "Which word means using things carefully for the future?", options: ["Sustainability", "Littering", "Wasting", "Polluting"], correct: 0 },
      { n: 220, diff: "easy", q: "Which choice is responsible?", options: ["Close the tap", "Leave water running", "Drop wrappers", "Waste food"], correct: 0 },
      { n: 221, diff: "medium", q: "Why do we reuse suitable items?", options: ["To reduce waste", "To make more litter", "To dirty water", "To waste resources"], correct: 0 },
      { n: 222, diff: "medium", q: "Which action is sustainable at lunch?", options: ["Use a reusable container", "Use many items once and litter them", "Waste food", "Throw bottle on ground"], correct: 0 },
      { n: 223, diff: "medium", q: "Which school project supports sustainability?", options: ["Garden and recycling activity", "Litter competition", "Plastic burning", "Water wasting"], correct: 0 },
      { n: 224, diff: "medium", q: "Why should we care for trees?", options: ["They are useful now and in the future", "They are litter", "They waste all water", "They make smoke"], correct: 0 },
      { n: 225, diff: "medium", q: "Which choice saves energy?", options: ["Use daylight when suitable", "Turn on every bulb in daytime", "Leave fans in empty rooms", "Open fridge for fun"], correct: 0 },
      { n: 226, diff: "medium", q: "Which choice saves water while brushing teeth?", options: ["Close tap while brushing", "Keep tap running", "Spill water", "Play with water"], correct: 0 },
      { n: 227, diff: "medium", q: "Which action can reduce food waste?", options: ["Store food properly with adult help", "Leave food uncovered", "Throw fresh food away", "Take too much"], correct: 0 },
      { n: 228, diff: "medium", q: "What is one benefit of a school garden?", options: ["Learning how food grows", "Creating plastic waste", "Blocking drains", "Wasting soil"], correct: 0 },
      { n: 229, diff: "medium", q: "Which action shows sharing resources wisely?", options: ["Use only what you need", "Take more than you need", "Waste supplies", "Break shared tools"], correct: 0 },
      { n: 230, diff: "medium", q: "Why should school tools be cared for?", options: ["They can last longer", "They become food", "They make rain", "They create litter"], correct: 0 },
      { n: 231, diff: "medium", q: "Which action supports a cleaner future?", options: ["Reduce litter", "Increase litter", "Pollute streams", "Burn plastic"], correct: 0 },
      { n: 232, diff: "medium", q: "What can pupils do with a clean reusable container?", options: ["Use it again", "Throw it in a river", "Burn it", "Break it"], correct: 0 },
      { n: 233, diff: "medium", q: "Which habit links health and sustainability?", options: ["Use clean water without wasting it", "Drink dirty water", "Leave taps open", "Throw waste in water"], correct: 0 },
      { n: 234, diff: "medium", q: "Why should we avoid wasting paper?", options: ["Paper and resources are used to make it", "Paper is water", "Paper grows on desks", "Paper makes electricity"], correct: 0 },
      { n: 235, diff: "medium", q: "Which action helps protect future water supplies?", options: ["Keep water sources clean", "Throw waste into streams", "Pour oil into drains", "Leave rubbish by wells"], correct: 0 },
      { n: 236, diff: "medium", q: "Which is a responsible garden choice?", options: ["Compost suitable plant waste", "Add plastic litter", "Pour paint on soil", "Break seedlings"], correct: 0 },
      { n: 237, diff: "medium", q: "What does 'reduce' mean in waste care?", options: ["Use less when possible", "Use more and waste it", "Throw more away", "Scatter more litter"], correct: 0 },
      { n: 238, diff: "medium", q: "What does 'reuse' mean?", options: ["Use an item again safely", "Burn it", "Throw it away immediately", "Put it in a drain"], correct: 0 },
      { n: 239, diff: "medium", q: "Which choice shows care for community property?", options: ["Use and return shared tools carefully", "Break tools", "Hide tools", "Leave tools in rain"], correct: 0 },
      { n: 240, diff: "medium", q: "Which class activity can teach sustainability?", options: ["Sorting reusable and non-reusable items", "Scattering waste", "Leaving taps open", "Breaking plants"], correct: 0 },
      { n: 241, diff: "hard", q: "Which plan saves food, water and energy together?", options: ["Take enough food, close taps, switch off unused lights", "Waste lunch, run taps, leave lights on", "Burn waste and flood paths", "Break bulbs and spill water"], correct: 0 },
      { n: 242, diff: "hard", q: "A class has many used clean paper sheets with blank backs. What is best?", options: ["Reuse the blank sides for practice", "Throw them away at once", "Put them in a drain", "Burn them in class"], correct: 0 },
      { n: 243, diff: "hard", q: "Which action best shows thinking about future pupils?", options: ["Care for school trees, water and equipment", "Destroy equipment", "Waste water", "Cut young plants"], correct: 0 },
      { n: 244, diff: "hard", q: "Why is a reusable bottle often better than many single-use bottles?", options: ["It can reduce repeated waste", "It makes more litter", "It must be thrown away daily", "It wastes more by definition"], correct: 0 },
      { n: 245, diff: "hard", q: "Which project joins food and sustainability?", options: ["Grow vegetables and compost suitable plant scraps", "Throw vegetables away", "Cover soil with plastic litter", "Waste harvested food"], correct: 0 },
      { n: 246, diff: "hard", q: "Which project joins water and sustainability?", options: ["Collect suitable rainwater for garden use", "Leave taps leaking", "Throw rubbish in gutters", "Waste clean water"], correct: 0 },
      { n: 247, diff: "hard", q: "Which project joins energy and sustainability?", options: ["Use sunlight and switch off unused electricity", "Keep lights on all day", "Burn rubbish for fun", "Run empty-room fans"], correct: 0 },
      { n: 248, diff: "hard", q: "Why is caring for shared resources a civic duty?", options: ["It helps everyone use them now and later", "It makes resources disappear faster", "It encourages waste", "It blocks learning"], correct: 0 },
      { n: 249, diff: "hard", q: "Which statement best describes sustainability for Primary 1?", options: ["Meeting needs while caring for resources for the future", "Using everything as fast as possible", "Throwing all used items away", "Ignoring plants and water"], correct: 0 },
      { n: 250, diff: "hard", q: "Which subjects can a school-garden counting activity connect?", options: ["Basic Science, Mathematics and Social responsibility", "Only music", "Only handwriting", "Only dance"], correct: 0 },
    ],
  },
]

export function categoryBySlug(slug: string): QuizCategory | undefined {
  return P1_QUIZ.find(c => c.slug === slug)
}