// AUTO-GENERATED Primary 4 quiz bank — 250 questions, 5 categories.
// Do not edit by hand; regenerate from the source markdown.

import type { QuizCategory } from './quiz-p1'

export const P4_QUIZ: QuizCategory[] = [
  {
    slug: "food", name: "Food & Nutrition", icon: "🍎",
    color: "#E0574C", badge: "Food Explorer", badgeIcon: "🍎",
    questions: [
      { n: 1, diff: "easy", q: "Which nutrient is mainly used for body growth and repair?", options: ["Protein", "Sugar", "Water only", "Salt"], correct: 0 },
      { n: 2, diff: "easy", q: "Which food is rich in carbohydrates?", options: ["Rice", "Fish", "Egg", "Spinach"], correct: 0 },
      { n: 3, diff: "easy", q: "Which food is a good source of protein?", options: ["Beans", "Sugar", "Orange", "Cassava"], correct: 0 },
      { n: 4, diff: "easy", q: "Which food is a protective food?", options: ["Carrot", "Yam", "Rice", "Bread"], correct: 0 },
      { n: 5, diff: "easy", q: "Which mineral is important for strong bones and teeth?", options: ["Calcium", "Plastic", "Smoke", "Starch"], correct: 0 },
      { n: 6, diff: "easy", q: "Which food is a source of calcium?", options: ["Milk", "Sugar", "Garri", "Oil"], correct: 0 },
      { n: 7, diff: "easy", q: "Which vitamin is commonly associated with citrus fruits?", options: ["Vitamin C", "Vitamin D only", "Starch", "Protein"], correct: 0 },
      { n: 8, diff: "easy", q: "Which food is a legume?", options: ["Beans", "Mango", "Fish", "Rice"], correct: 0 },
      { n: 9, diff: "easy", q: "Which is a root or tuber crop?", options: ["Cassava", "Maize", "Orange", "Fish"], correct: 0 },
      { n: 10, diff: "easy", q: "Which food comes from an animal?", options: ["Fish", "Maize", "Beans", "Yam"], correct: 0 },
      { n: 11, diff: "easy", q: "Which food comes from a plant?", options: ["Groundnut", "Egg", "Milk", "Meat"], correct: 0 },
      { n: 12, diff: "easy", q: "What should be done before handling food?", options: ["Wash hands", "Touch rubbish", "Play in mud", "Use dirty utensils"], correct: 0 },
      { n: 13, diff: "easy", q: "Which practice protects cooked food?", options: ["Keep it covered", "Leave it near flies", "Put it on a dirty floor", "Mix it with waste"], correct: 0 },
      { n: 14, diff: "easy", q: "Which drink is best for hydration?", options: ["Clean water", "Paint", "Kerosene", "Ink"], correct: 0 },
      { n: 15, diff: "easy", q: "Which is a healthy snack?", options: ["Fruit and groundnuts", "Candy only", "Soft drink only", "Sugar cubes"], correct: 0 },
      { n: 16, diff: "easy", q: "Which food group mainly provides energy?", options: ["Carbohydrates", "Vitamins", "Minerals", "Water"], correct: 0 },
      { n: 17, diff: "easy", q: "Which food can be grown in a school garden?", options: ["Lettuce", "Plastic", "Glass", "Metal"], correct: 0 },
      { n: 18, diff: "easy", q: "What is food hygiene?", options: ["Keeping food and food-handling practices clean", "Throwing food away", "Eating only sweets", "Cooking without washing"], correct: 0 },
      { n: 19, diff: "easy", q: "Which is an example of food waste?", options: ["Throwing edible rice away", "Eating a suitable portion", "Storing leftovers safely", "Sharing extra food safely"], correct: 0 },
      { n: 20, diff: "easy", q: "Which farm activity begins crop production?", options: ["Planting", "Packaging", "Selling", "Cooking"], correct: 0 },
      { n: 21, diff: "medium", q: "Why does the body need carbohydrates?", options: ["They are an important source of energy", "They build plastic", "They create rainfall", "They replace water"], correct: 0 },
      { n: 22, diff: "medium", q: "Why are vitamins and minerals important?", options: ["They support healthy body functions", "They are only fuels", "They replace sleep", "They make food sweeter"], correct: 0 },
      { n: 23, diff: "medium", q: "Which meal is most balanced?", options: ["Rice, beans, fish and vegetables", "Sweets and soft drink", "Sugar and salt", "Bread only"], correct: 0 },
      { n: 24, diff: "medium", q: "Why should raw fruits and vegetables be washed?", options: ["To remove dirt and reduce contamination", "To remove all nutrients", "To make them plastic", "To make them heavier"], correct: 0 },
      { n: 25, diff: "medium", q: "What can cause food contamination?", options: ["Dirty hands and utensils", "Clean covered containers", "Safe water", "Proper storage"], correct: 0 },
      { n: 26, diff: "medium", q: "Which pair contains mainly protein-rich foods?", options: ["Egg and beans", "Rice and yam", "Orange and carrot", "Sugar and sweets"], correct: 0 },
      { n: 27, diff: "medium", q: "Which pair contains mainly carbohydrate-rich foods?", options: ["Rice and cassava", "Fish and egg", "Milk and beans", "Orange and spinach"], correct: 0 },
      { n: 28, diff: "medium", q: "Which pair provides protective nutrients?", options: ["Carrot and orange", "Rice and yam", "Fish and egg", "Bread and cassava"], correct: 0 },
      { n: 29, diff: "medium", q: "Why is dietary variety important?", options: ["Different foods supply different nutrients", "One food supplies every nutrient in ideal amounts", "It removes the need for water", "It stops digestion"], correct: 0 },
      { n: 30, diff: "medium", q: "Which action reduces household food waste?", options: ["Plan portions and store leftovers safely", "Cook far more than needed", "Throw edible food away", "Leave food uncovered"], correct: 0 },
      { n: 31, diff: "medium", q: "Why is clean water necessary when preparing food?", options: ["It helps maintain food safety and hygiene", "It turns food into plastic", "It replaces nutrients", "It makes all foods raw"], correct: 0 },
      { n: 32, diff: "medium", q: "What is composting useful food scraps and plant waste an example of?", options: ["Resource recovery", "Water pollution", "Food contamination", "Energy waste"], correct: 0 },
      { n: 33, diff: "medium", q: "Why do crops need fertile soil?", options: ["It supplies nutrients and supports growth", "It makes plastic", "It removes sunlight", "It replaces water completely"], correct: 0 },
      { n: 34, diff: "medium", q: "Why do farmers control weeds?", options: ["Weeds compete with crops for resources", "Weeds always increase harvest", "Weeds make electricity", "Weeds replace crops"], correct: 0 },
      { n: 35, diff: "medium", q: "Which activity can improve food security at school?", options: ["Growing a learning garden", "Wasting harvested vegetables", "Polluting soil", "Leaving crops unwatered"], correct: 0 },
      { n: 36, diff: "medium", q: "What does food preservation help do?", options: ["Keep food usable for longer", "Make all food unsafe", "Remove every nutrient", "Create litter"], correct: 0 },
      { n: 37, diff: "medium", q: "Which method can preserve some foods?", options: ["Drying", "Adding dirty water", "Leaving food exposed", "Putting it beside waste"], correct: 0 },
      { n: 38, diff: "medium", q: "Why should pupils understand food labels with adult guidance?", options: ["Labels can provide useful information about food", "Labels make food grow", "Labels replace hygiene", "Labels turn food into medicine"], correct: 0 },
      { n: 39, diff: "medium", q: "Which subject can help calculate the number of harvested vegetables?", options: ["Mathematics", "Music only", "Drama only", "Handwriting only"], correct: 0 },
      { n: 40, diff: "medium", q: "How can a school garden support learning?", options: ["Pupils can observe plant growth and food production", "It removes the need for classroom learning", "It encourages waste", "It prevents science activities"], correct: 0 },
      { n: 41, diff: "hard", q: "A meal contains yam, beans and spinach. What main roles do they represent?", options: ["Energy, body-building and protective functions", "Only energy", "Only body-building", "Only water"], correct: 0 },
      { n: 42, diff: "hard", q: "A family cooks 12 portions and eats 9. How many portions remain?", options: ["3", "21", "9", "4"], correct: 0 },
      { n: 43, diff: "hard", q: "Why can reducing food waste also conserve water?", options: ["Water is used to grow and prepare food", "Food production never uses water", "Waste creates clean water", "Only packaging uses water"], correct: 0 },
      { n: 44, diff: "hard", q: "Which action best connects nutrition, agriculture and sustainability?", options: ["Grow diverse foods and use harvests responsibly", "Grow one crop and waste most of it", "Pollute garden soil", "Use more water than crops need"], correct: 0 },
      { n: 45, diff: "hard", q: "What is the best explanation of a balanced diet?", options: ["It provides appropriate amounts of different nutrients from varied foods", "It contains only carbohydrates", "It contains only protein", "It means eating the largest amount possible"], correct: 0 },
      { n: 46, diff: "hard", q: "Why can poor food hygiene affect health?", options: ["Contaminated food may carry harmful microorganisms", "Dirty food always contains more nutrients", "Flies improve food safety", "Uncovered food becomes sterile"], correct: 0 },
      { n: 47, diff: "hard", q: "A class harvests 24 tomatoes and shares them equally among 6 groups. How many does each group receive?", options: ["4", "6", "18", "30"], correct: 0 },
      { n: 48, diff: "hard", q: "Which sequence correctly represents a simple food supply chain?", options: ["Farm → transport → market → consumer", "Consumer → market → seed → farm", "Market → consumer → soil → seed", "Kitchen → farm → rain → market"], correct: 0 },
      { n: 49, diff: "hard", q: "Why can compost improve a school food garden?", options: ["It returns organic matter and nutrients to soil", "It replaces sunlight", "It makes plants need no water", "It turns soil into plastic"], correct: 0 },
      { n: 50, diff: "hard", q: "Which investigation best combines food science and mathematics?", options: ["Compare plant growth, measure harvests and record results", "Sing about vegetables only", "Draw one fruit only", "Memorize food names only"], correct: 0 },
    ]
  },
  {
    slug: "energy", name: "Energy & Water", icon: "💧",
    color: "#3E7CA6", badge: "Energy & Water Hero", badgeIcon: "💧",
    questions: [
      { n: 1, diff: "easy", q: "Which is a renewable energy source?", options: ["Solar energy", "Petrol", "Diesel", "Coal"], correct: 0 },
      { n: 2, diff: "easy", q: "Which device converts sunlight into electricity?", options: ["Solar panel", "Water bucket", "Broom", "Spoon"], correct: 0 },
      { n: 3, diff: "easy", q: "Which appliance uses electrical energy?", options: ["Refrigerator", "Stone", "Leaf", "Basket"], correct: 0 },
      { n: 4, diff: "easy", q: "Which is a natural source of water?", options: ["Rain", "Smoke", "Plastic", "Dust"], correct: 0 },
      { n: 5, diff: "easy", q: "Which water is suitable for drinking?", options: ["Safe clean water", "Gutter water", "Oily water", "Muddy puddle"], correct: 0 },
      { n: 6, diff: "easy", q: "Which action conserves water?", options: ["Repair leaking taps", "Leave taps running", "Spill stored water", "Wash roads unnecessarily"], correct: 0 },
      { n: 7, diff: "easy", q: "Which action conserves electricity?", options: ["Switch off unused appliances", "Leave every appliance on", "Run fans in empty rooms", "Open refrigerators repeatedly"], correct: 0 },
      { n: 8, diff: "easy", q: "What can store collected rainwater?", options: ["Tank", "Net", "Broom", "Pencil"], correct: 0 },
      { n: 9, diff: "easy", q: "Which energy source moves wind turbines?", options: ["Wind", "Soil", "Food", "Plastic"], correct: 0 },
      { n: 10, diff: "easy", q: "Which energy source can move water turbines?", options: ["Flowing water", "Dry sand", "Plastic", "Smoke"], correct: 0 },
      { n: 11, diff: "easy", q: "What is evaporation?", options: ["Liquid water changing into water vapour", "Water turning into soil", "Rain becoming plastic", "Clouds becoming metal"], correct: 0 },
      { n: 12, diff: "easy", q: "What is condensation?", options: ["Water vapour cooling into liquid droplets", "Soil becoming water", "Plastic becoming rain", "Sunlight becoming food"], correct: 0 },
      { n: 13, diff: "easy", q: "Which process brings water from clouds to the ground?", options: ["Precipitation", "Evaporation", "Melting plastic", "Combustion"], correct: 0 },
      { n: 14, diff: "easy", q: "What provides energy for much of the water cycle?", options: ["Sun", "Moon only", "Soil", "Plastic"], correct: 0 },
      { n: 15, diff: "easy", q: "Which activity requires water?", options: ["Irrigation", "Reading", "Counting", "Drawing"], correct: 0 },
      { n: 16, diff: "easy", q: "Which activity can require electricity?", options: ["Pumping water", "Sweeping with a broom", "Reading a paper book", "Planting by hand"], correct: 0 },
      { n: 17, diff: "easy", q: "What should be done with drinking water containers?", options: ["Keep them clean and covered", "Leave them open near waste", "Put dirty hands inside", "Mix clean and dirty water"], correct: 0 },
      { n: 18, diff: "easy", q: "Which is a fossil fuel?", options: ["Petrol", "Sunlight", "Wind", "Flowing water"], correct: 0 },
      { n: 19, diff: "easy", q: "Which is an energy-saving light source when used efficiently?", options: ["LED bulb", "Open fire", "Candle only", "Broken bulb"], correct: 0 },
      { n: 20, diff: "easy", q: "What should pupils do around electrical sockets?", options: ["Follow safety rules", "Insert metal objects", "Touch with wet hands", "Pour water on them"], correct: 0 },
      { n: 21, diff: "medium", q: "Why is solar energy renewable?", options: ["Sunlight is naturally replenished", "It must be mined", "It is made from petrol", "It exists only in batteries"], correct: 0 },
      { n: 22, diff: "medium", q: "Why is water conservation important?", options: ["Usable freshwater is valuable and can be limited", "Water cannot be wasted", "All water is immediately drinkable", "Water has no role in food production"], correct: 0 },
      { n: 23, diff: "medium", q: "Which action can pollute groundwater?", options: ["Improper disposal of harmful chemicals", "Using a clean bin", "Planting trees appropriately", "Repairing a leak"], correct: 0 },
      { n: 24, diff: "medium", q: "How does the sun help drive the water cycle?", options: ["It supplies heat for evaporation", "It creates plastic", "It stops clouds", "It removes all water"], correct: 0 },
      { n: 25, diff: "medium", q: "What happens after water vapour cools in the atmosphere?", options: ["It can condense into droplets", "It becomes soil", "It becomes fuel", "It disappears permanently"], correct: 0 },
      { n: 26, diff: "medium", q: "Why can rainwater harvesting be useful?", options: ["It stores water for suitable later uses", "It increases water waste", "It creates smoke", "It makes rainfall stop"], correct: 0 },
      { n: 27, diff: "medium", q: "Which action uses water more efficiently in a garden?", options: ["Water near plant roots when needed", "Flood walkways", "Leave hoses running", "Water plastic surfaces"], correct: 0 },
      { n: 28, diff: "medium", q: "What is hydropower?", options: ["Energy obtained from moving water", "Energy from plastic", "Energy from soil only", "Energy from food"], correct: 0 },
      { n: 29, diff: "medium", q: "Which pair contains renewable energy sources?", options: ["Solar and wind", "Petrol and diesel", "Coal and petrol", "Kerosene and diesel"], correct: 0 },
      { n: 30, diff: "medium", q: "Which pair contains non-renewable fuels?", options: ["Petrol and diesel", "Sun and wind", "Water and sun", "Wind and flowing water"], correct: 0 },
      { n: 31, diff: "medium", q: "Why should electrical appliances be kept away from unsafe water contact?", options: ["Water can increase electrical hazards", "Water makes all appliances safer", "Electricity turns water into food", "Water stops every current"], correct: 0 },
      { n: 32, diff: "medium", q: "How can energy be used in water supply systems?", options: ["To pump and treat water", "To turn water into plastic", "To stop rainfall", "To make rivers disappear"], correct: 0 },
      { n: 33, diff: "medium", q: "Which school action can reduce both water and energy waste?", options: ["Report leaks and switch off unused devices", "Leave taps and fans on", "Waste water while lights stay on", "Run pumps unnecessarily"], correct: 0 },
      { n: 34, diff: "medium", q: "Why do plants need water?", options: ["For growth and important life processes", "To make plastic", "To replace sunlight completely", "To stop nutrient uptake"], correct: 0 },
      { n: 35, diff: "medium", q: "Which water-cycle process forms clouds?", options: ["Condensation", "Combustion", "Filtration", "Freezing soil"], correct: 0 },
      { n: 36, diff: "medium", q: "Which process returns water to the atmosphere from wet surfaces?", options: ["Evaporation", "Precipitation", "Collection only", "Runoff only"], correct: 0 },
      { n: 37, diff: "medium", q: "What is runoff?", options: ["Water flowing over land after rain", "Water turning into vapour", "Clouds forming", "Water freezing in a cup"], correct: 0 },
      { n: 38, diff: "medium", q: "Why should streams be protected from waste?", options: ["They are habitats and water resources", "Waste improves water quality", "Plastic feeds aquatic animals", "Oil cleans water"], correct: 0 },
      { n: 39, diff: "medium", q: "Which subject can help pupils calculate litres of water saved?", options: ["Mathematics", "Drama only", "Music only", "Handwriting only"], correct: 0 },
      { n: 40, diff: "medium", q: "Which investigation demonstrates energy conservation?", options: ["Compare electricity use with lights on and off", "Leave all appliances on", "Waste electricity without measuring", "Break bulbs"], correct: 0 },
      { n: 41, diff: "hard", q: "Which sequence correctly represents part of the water cycle?", options: ["Evaporation → condensation → precipitation → collection", "Precipitation → plastic → smoke → evaporation", "Condensation → soil → electricity → rain", "Collection → fuel → plastic → cloud"], correct: 0 },
      { n: 42, diff: "hard", q: "A tank contains 40 litres and 15 litres are used. How many litres remain?", options: ["25 litres", "55 litres", "15 litres", "35 litres"], correct: 0 },
      { n: 43, diff: "hard", q: "A school replaces wasteful lighting practices with efficient use. What is the main sustainability benefit?", options: ["Less electricity is needed for the same useful service", "More water is polluted", "More fuel must always be burned", "Lights must stay on longer"], correct: 0 },
      { n: 44, diff: "hard", q: "How are water and energy connected in a pumped irrigation system?", options: ["Energy moves water to crops", "Water eliminates the need for energy", "Energy turns soil into water", "Irrigation needs no resources"], correct: 0 },
      { n: 45, diff: "hard", q: "Why can reducing hot-water waste save two resources?", options: ["It can save both water and the energy used to heat it", "It saves only plastic", "Heating water requires no energy", "Water has no connection to energy"], correct: 0 },
      { n: 46, diff: "hard", q: "A class collects 60 litres of rainwater and uses 45 litres on a garden. How much remains?", options: ["15 litres", "105 litres", "45 litres", "25 litres"], correct: 0 },
      { n: 47, diff: "hard", q: "Which plan best improves school water security?", options: ["Prevent leaks, store suitable rainwater and protect water quality", "Leave taps running and pollute drains", "Depend on one leaking source", "Waste stored water"], correct: 0 },
      { n: 48, diff: "hard", q: "Why are renewable energy systems useful for sustainability?", options: ["They can provide energy from naturally replenished sources", "They always require fossil fuels as their source", "They create unlimited energy without equipment", "They remove the need for conservation"], correct: 0 },
      { n: 49, diff: "hard", q: "Which investigation combines science, mathematics and water conservation?", options: ["Measure daily water use, identify leaks and calculate savings", "Sing about taps only", "Draw one bucket only", "Guess water use without measuring"], correct: 0 },
      { n: 50, diff: "hard", q: "Which statement best describes the food-energy-water connection?", options: ["Food production often depends on both water and energy", "Food production needs neither water nor energy", "Water and energy never interact", "Only packaged food uses resources"], correct: 0 },
    ]
  },
  {
    slug: "environment", name: "Environment", icon: "🌱",
    color: "#5C9E3A", badge: "Green Guardian", badgeIcon: "🌱",
    questions: [
      { n: 1, diff: "easy", q: "What is an ecosystem?", options: ["Living things and their environment interacting", "Only animals", "Only plants", "Only rocks"], correct: 0 },
      { n: 2, diff: "easy", q: "Which is a producer in an ecosystem?", options: ["Grass", "Goat", "Lion", "Human"], correct: 0 },
      { n: 3, diff: "easy", q: "Which is a consumer?", options: ["Goat", "Maize plant", "Grass", "Tree"], correct: 0 },
      { n: 4, diff: "easy", q: "Which organism helps decompose dead matter?", options: ["Fungus", "Stone", "Plastic bottle", "Metal can"], correct: 0 },
      { n: 5, diff: "easy", q: "What is a habitat?", options: ["The place where an organism lives", "A food group", "A school subject", "A type of energy"], correct: 0 },
      { n: 6, diff: "easy", q: "Which habitat suits a frog?", options: ["Wetland or pond edge", "Dry cupboard", "Metal box", "Hot stove"], correct: 0 },
      { n: 7, diff: "easy", q: "Which is biodegradable?", options: ["Banana peel", "Plastic bottle", "Glass cup", "Metal can"], correct: 0 },
      { n: 8, diff: "easy", q: "Which is non-biodegradable?", options: ["Plastic bag", "Dry leaf", "Fruit peel", "Vegetable scrap"], correct: 0 },
      { n: 9, diff: "easy", q: "Which action reduces litter?", options: ["Use proper bins", "Drop wrappers", "Throw waste in drains", "Scatter bottles"], correct: 0 },
      { n: 10, diff: "easy", q: "Which can cause air pollution?", options: ["Smoke", "Tree shade", "Clean breeze", "Rainwater"], correct: 0 },
      { n: 11, diff: "easy", q: "Which can cause water pollution?", options: ["Oil spill", "Clean rain", "Sunlight", "Fresh air"], correct: 0 },
      { n: 12, diff: "easy", q: "Which can cause soil pollution?", options: ["Improper waste dumping", "Composting", "Planting trees", "Mulching"], correct: 0 },
      { n: 13, diff: "easy", q: "Which plant part holds soil and can reduce erosion?", options: ["Roots", "Flowers", "Fruits", "Seeds"], correct: 0 },
      { n: 14, diff: "easy", q: "What is erosion?", options: ["Removal of soil by agents such as water or wind", "Making compost", "Planting crops", "Sorting waste"], correct: 0 },
      { n: 15, diff: "easy", q: "Which action can reduce erosion?", options: ["Keep soil covered with vegetation", "Remove all plants", "Leave soil bare", "Pour oil on soil"], correct: 0 },
      { n: 16, diff: "easy", q: "What is biodiversity?", options: ["Variety of living things", "Only large animals", "Only trees", "Only insects"], correct: 0 },
      { n: 17, diff: "easy", q: "Which action supports biodiversity?", options: ["Protect habitats", "Destroy nests", "Pollute ponds", "Remove all plants"], correct: 0 },
      { n: 18, diff: "easy", q: "Which animal can help pollinate flowers?", options: ["Bee", "Goat", "Cat", "Fish"], correct: 0 },
      { n: 19, diff: "easy", q: "What should happen to hazardous-looking waste?", options: ["Tell an adult and avoid touching it", "Play with it", "Put it in drinking water", "Hide it in soil"], correct: 0 },
      { n: 20, diff: "easy", q: "Which shared space should be kept clean?", options: ["School compound", "Only one desk", "Only a cupboard", "No shared space"], correct: 0 },
      { n: 21, diff: "medium", q: "What is a food chain?", options: ["A sequence showing who eats whom", "A chain used on a gate", "A list of school subjects", "A type of rainfall"], correct: 0 },
      { n: 22, diff: "medium", q: "Which food chain is correctly ordered?", options: ["Grass → grasshopper → bird", "Bird → grass → grasshopper", "Grasshopper → bird → grass", "Stone → grass → bird"], correct: 0 },
      { n: 23, diff: "medium", q: "Why are decomposers important?", options: ["They help break down dead organic matter", "They make plastic", "They stop all plant growth", "They remove sunlight"], correct: 0 },
      { n: 24, diff: "medium", q: "How do plant roots help soil?", options: ["They can hold soil together", "They turn soil into glass", "They create plastic", "They remove every nutrient"], correct: 0 },
      { n: 25, diff: "medium", q: "What can happen when vegetation is removed from bare slopes?", options: ["Soil erosion may increase", "Soil becomes stronger automatically", "Rain stops", "Plastic disappears"], correct: 0 },
      { n: 26, diff: "medium", q: "Why should wetlands be protected?", options: ["They provide habitats and important ecosystem functions", "They are useless land", "They should always be filled with waste", "They stop all biodiversity"], correct: 0 },
      { n: 27, diff: "medium", q: "Which action helps reduce water pollution?", options: ["Dispose of waste properly", "Pour oil into drains", "Dump rubbish in streams", "Wash chemicals into rivers"], correct: 0 },
      { n: 28, diff: "medium", q: "Why is burning plastic harmful?", options: ["It can release harmful air pollutants", "It cleans the air", "It creates oxygen only", "It improves soil"], correct: 0 },
      { n: 29, diff: "medium", q: "What is conservation?", options: ["Protection and wise use of natural resources", "Rapid resource waste", "Pollution of habitats", "Removal of all organisms"], correct: 0 },
      { n: 30, diff: "medium", q: "Why is biodiversity valuable?", options: ["Different organisms contribute to ecosystem functions", "Only one species is needed everywhere", "Biodiversity creates plastic", "More species always cause pollution"], correct: 0 },
      { n: 31, diff: "medium", q: "Which is an example of reuse?", options: ["Use a safe container again", "Throw it away after one use", "Burn it", "Put it in a river"], correct: 0 },
      { n: 32, diff: "medium", q: "Which is an example of recycling?", options: ["Processing used material into new products", "Throwing all waste in one drain", "Burning everything", "Leaving bottles on roads"], correct: 0 },
      { n: 33, diff: "medium", q: "How can composting reduce waste?", options: ["Organic scraps become useful soil material", "Organic scraps become plastic", "Waste is placed in rivers", "All waste becomes metal"], correct: 0 },
      { n: 34, diff: "medium", q: "Why should school drains remain clear?", options: ["To allow water to flow and reduce flooding risk", "To store plastic", "To stop rainfall", "To collect litter"], correct: 0 },
      { n: 35, diff: "medium", q: "What is an invasive action that harms habitats?", options: ["Dumping waste into a pond", "Protecting vegetation", "Using bins", "Planting suitable species"], correct: 0 },
      { n: 36, diff: "medium", q: "Which environmental factor do plants need?", options: ["Sunlight", "Plastic", "Smoke", "Glass"], correct: 0 },
      { n: 37, diff: "medium", q: "What can happen when a water habitat is polluted?", options: ["Aquatic organisms may be harmed", "All fish become healthier", "Water becomes safe automatically", "Pollution increases oxygen by definition"], correct: 0 },
      { n: 38, diff: "medium", q: "Which activity helps study biodiversity?", options: ["Count and identify different organisms observed", "Destroy organisms before counting", "Guess without observing", "Remove all plants first"], correct: 0 },
      { n: 39, diff: "medium", q: "Which subject helps pupils create a bar chart of waste types?", options: ["Mathematics", "Music only", "Drama only", "Handwriting only"], correct: 0 },
      { n: 40, diff: "medium", q: "Why is environmental care a civic responsibility?", options: ["Shared environments affect everyone", "Only scientists use the environment", "Pollution affects nobody", "Public spaces need no care"], correct: 0 },
      { n: 41, diff: "hard", q: "In the chain grass → grasshopper → bird, what is the producer?", options: ["Grass", "Grasshopper", "Bird", "All three are consumers"], correct: 0 },
      { n: 42, diff: "hard", q: "A class collects 30 pieces of litter and recycles 18. How many are left to manage?", options: ["12", "48", "18", "22"], correct: 0 },
      { n: 43, diff: "hard", q: "How can deforestation contribute to soil erosion?", options: ["Removing tree cover exposes soil to wind and water", "Trees cause all erosion", "Removing trees always strengthens soil", "Deforestation creates more roots"], correct: 0 },
      { n: 44, diff: "hard", q: "Why can loss of one species affect other species in a food web?", options: ["Organisms are connected through feeding and habitat relationships", "Species never interact", "Only plants depend on ecosystems", "Food webs contain no relationships"], correct: 0 },
      { n: 45, diff: "hard", q: "Which school plan best supports a healthy ecosystem?", options: ["Protect soil, plant diverse vegetation and manage waste properly", "Remove all vegetation and burn waste", "Pollute the pond and block drains", "Cover every soil surface with plastic"], correct: 0 },
      { n: 46, diff: "hard", q: "What is the difference between biodegradable and non-biodegradable waste?", options: ["Biodegradable materials can be broken down naturally more readily", "Both always break down at the same rate", "Plastic is always biodegradable like fruit peel", "Food scraps never decompose"], correct: 0 },
      { n: 47, diff: "hard", q: "A garden has 8 plant species and pupils add 4 new suitable species. How many species are represented?", options: ["12", "4", "8", "32"], correct: 0 },
      { n: 48, diff: "hard", q: "Why is preventing pollution usually better than cleaning it later?", options: ["Prevention can avoid harm and cleanup costs", "Pollution always cleans itself immediately", "Cleanup uses no resources", "Pollution benefits habitats"], correct: 0 },
      { n: 49, diff: "hard", q: "Which investigation best studies erosion?", options: ["Compare soil loss from bare and vegetation-covered surfaces", "Sing about soil only", "Guess without observing", "Remove all measurements"], correct: 0 },
      { n: 50, diff: "hard", q: "How do food chains show ecosystem interdependence?", options: ["They show how organisms depend on others for energy and food", "They show organisms never interact", "They show only soil types", "They explain electricity generation"], correct: 0 },
    ]
  },
  {
    slug: "climate", name: "Climate Literacy", icon: "🌧️",
    color: "#C8912E", badge: "Climate Champion", badgeIcon: "🌧️",
    questions: [
      { n: 1, diff: "easy", q: "What is weather?", options: ["Short-term atmospheric conditions", "A type of soil", "A food group", "A plant"], correct: 0 },
      { n: 2, diff: "easy", q: "What is climate?", options: ["Usual weather patterns over a long period", "Weather for one minute", "A type of animal", "A school tool"], correct: 0 },
      { n: 3, diff: "easy", q: "Which tool measures temperature?", options: ["Thermometer", "Ruler", "Rain boot", "Basket"], correct: 0 },
      { n: 4, diff: "easy", q: "Which instrument measures rainfall?", options: ["Rain gauge", "Thermometer", "Clock", "Balance"], correct: 0 },
      { n: 5, diff: "easy", q: "Which describes moving air?", options: ["Wind", "Soil", "Heat only", "Cloud"], correct: 0 },
      { n: 6, diff: "easy", q: "Which season is often wetter in many parts of Nigeria?", options: ["Rainy season", "Dry season", "Snow season", "Ice season"], correct: 0 },
      { n: 7, diff: "easy", q: "Which season is often drier?", options: ["Dry season", "Rainy season", "Snow season", "Ice season"], correct: 0 },
      { n: 8, diff: "easy", q: "What is drought?", options: ["An unusually long period of low water availability or rainfall", "One rainy afternoon", "A windy morning", "A cloudy hour"], correct: 0 },
      { n: 9, diff: "easy", q: "What is flooding?", options: ["Water covering land that is usually dry", "A hot sunny day", "A dry breeze", "A cloud forming"], correct: 0 },
      { n: 10, diff: "easy", q: "Which action is safer during a thunderstorm?", options: ["Stay in a safe building", "Stand in an open field", "Touch metal poles", "Play in floodwater"], correct: 0 },
      { n: 11, diff: "easy", q: "Which action helps during hot weather?", options: ["Drink water and use shade", "Avoid water", "Wear heavy blankets", "Stand on hot metal"], correct: 0 },
      { n: 12, diff: "easy", q: "Which can provide natural shade?", options: ["Tree", "Plastic bag", "Spoon", "Bottle"], correct: 0 },
      { n: 13, diff: "easy", q: "Which weather condition may increase evaporation?", options: ["Hot sunny weather", "Cool wet weather", "Heavy rainfall", "Cold cloudy weather"], correct: 0 },
      { n: 14, diff: "easy", q: "Which weather condition may fill streams quickly?", options: ["Heavy rain", "Dry wind", "Drought", "Clear sky"], correct: 0 },
      { n: 15, diff: "easy", q: "Why are weather forecasts useful?", options: ["They help people prepare", "They control weather", "They stop rainfall", "They create sunlight"], correct: 0 },
      { n: 16, diff: "easy", q: "Which is a weather observation?", options: ["It is windy today", "The region is usually dry", "This area has warm summers", "The climate is tropical"], correct: 0 },
      { n: 17, diff: "easy", q: "Which is a climate statement?", options: ["The region is usually warm and wet", "It rained this morning", "The wind is strong now", "A cloud passed today"], correct: 0 },
      { n: 18, diff: "easy", q: "Which can be recorded on a weather chart?", options: ["Temperature", "Shoe size only", "Desk colour only", "Book title only"], correct: 0 },
      { n: 19, diff: "easy", q: "Which hazard may follow very heavy rainfall?", options: ["Flood", "Drought immediately", "Snow everywhere", "Dust storm always"], correct: 0 },
      { n: 20, diff: "easy", q: "Which hazard may affect crops after a long dry period?", options: ["Drought", "Flood only", "Snow", "Tide"], correct: 0 },
      { n: 21, diff: "medium", q: "Why is climate different from weather?", options: ["Climate describes long-term patterns; weather describes short-term conditions", "They mean exactly the same thing", "Climate is only rainfall", "Weather always lasts decades"], correct: 0 },
      { n: 22, diff: "medium", q: "Why do farmers use weather information?", options: ["To plan activities such as planting and irrigation", "To control clouds", "To replace soil", "To stop all pests"], correct: 0 },
      { n: 23, diff: "medium", q: "How can heavy rainfall lead to flooding?", options: ["Water may arrive faster than land and drains can carry it away", "Rain always disappears immediately", "Heavy rain removes all rivers", "Floods occur only during drought"], correct: 0 },
      { n: 24, diff: "medium", q: "How can drought affect crops?", options: ["Crops may lack enough water", "Crops receive too much rain", "Drought creates irrigation water", "Drought replaces sunlight"], correct: 0 },
      { n: 25, diff: "medium", q: "Why can trees help reduce heat around schools?", options: ["They provide shade and can cool surroundings", "They make petrol", "They stop all wind", "They create plastic"], correct: 0 },
      { n: 26, diff: "medium", q: "Which action helps a school prepare for heavy rain?", options: ["Keep drainage paths clear", "Block gutters", "Throw waste into drains", "Remove all drainage"], correct: 0 },
      { n: 27, diff: "medium", q: "Which action helps a garden during dry conditions?", options: ["Use water efficiently and protect soil moisture", "Leave taps running", "Remove mulch and shade", "Waste stored water"], correct: 0 },
      { n: 28, diff: "medium", q: "What does a rain gauge measure?", options: ["Amount of rainfall", "Air temperature", "Wind speed only", "Sunlight colour"], correct: 0 },
      { n: 29, diff: "medium", q: "Why should weather measurements be taken regularly?", options: ["Regular records help reveal changes and patterns", "One observation explains every year", "Measurements create rain", "Records stop wind"], correct: 0 },
      { n: 30, diff: "medium", q: "Which is an example of climate adaptation?", options: ["Using drought-tolerant crops where appropriate", "Burning more waste", "Blocking drains", "Wasting water"], correct: 0 },
      { n: 31, diff: "medium", q: "Which action can reduce unnecessary greenhouse gas emissions from electricity use?", options: ["Switch off unused electrical devices", "Leave every device running", "Waste electricity", "Run empty-room fans"], correct: 0 },
      { n: 32, diff: "medium", q: "Why can planting and protecting trees support climate action?", options: ["Trees store carbon and provide other environmental benefits", "Trees produce fossil fuels", "Trees create plastic", "Trees stop all climate change alone"], correct: 0 },
      { n: 33, diff: "medium", q: "Which human activity can release carbon dioxide?", options: ["Burning fossil fuels", "Planting a tree", "Collecting rainwater", "Using a broom"], correct: 0 },
      { n: 34, diff: "medium", q: "What is a greenhouse gas?", options: ["A gas that can trap heat in the atmosphere", "A type of vegetable", "A soil particle", "A rain gauge"], correct: 0 },
      { n: 35, diff: "medium", q: "Which gas is released when fossil fuels are burned?", options: ["Carbon dioxide", "Liquid water", "Soil", "Plastic"], correct: 0 },
      { n: 36, diff: "medium", q: "Why is climate literacy important?", options: ["It helps people understand climate risks and choices", "It allows people to control weather", "It removes the need for science", "It guarantees no disasters"], correct: 0 },
      { n: 37, diff: "medium", q: "Which school activity supports climate literacy?", options: ["Record weather and discuss patterns", "Ignore weather information", "Burn plastic", "Waste water"], correct: 0 },
      { n: 38, diff: "medium", q: "How can water conservation support drought preparedness?", options: ["It helps available water last longer", "It creates drought", "It makes water unusable", "It increases leaks"], correct: 0 },
      { n: 39, diff: "medium", q: "Which subject helps pupils graph rainfall data?", options: ["Mathematics", "Drama only", "Music only", "Handwriting only"], correct: 0 },
      { n: 40, diff: "medium", q: "What is resilience?", options: ["Ability to prepare for, cope with and recover from challenges", "Ability to create storms", "A type of fuel", "A weather instrument"], correct: 0 },
      { n: 41, diff: "hard", q: "A rain gauge records 12 mm on Monday and 8 mm on Tuesday. What is the total rainfall?", options: ["20 mm", "4 mm", "96 mm", "10 mm"], correct: 0 },
      { n: 42, diff: "hard", q: "Temperatures are 29°C, 31°C and 33°C. What is the highest recorded temperature?", options: ["33°C", "29°C", "31°C", "30°C"], correct: 0 },
      { n: 43, diff: "hard", q: "Why can climate change affect food and water systems?", options: ["Changes in heat and rainfall can influence crops and water availability", "Climate never affects resources", "Food production does not depend on weather", "Water supply is unrelated to rainfall"], correct: 0 },
      { n: 44, diff: "hard", q: "Which school plan combines mitigation and adaptation?", options: ["Save energy while also improving shade and water conservation", "Waste electricity and remove trees", "Block drains and burn waste", "Use more energy and waste water"], correct: 0 },
      { n: 45, diff: "hard", q: "Why is one unusually hot day not enough to define climate change?", options: ["Climate is assessed using patterns over long periods", "Climate changes only every hour", "One day always defines decades", "Weather records are unnecessary"], correct: 0 },
      { n: 46, diff: "hard", q: "A week has 4 rainy days and 3 dry days. What fraction of the week was rainy?", options: ["4/7", "3/7", "4/3", "7/4"], correct: 0 },
      { n: 47, diff: "hard", q: "How can climate information improve farm decisions?", options: ["It can help farmers choose timing and practices suited to expected conditions", "It guarantees perfect harvests", "It replaces seeds", "It stops all droughts"], correct: 0 },
      { n: 48, diff: "hard", q: "Which action strengthens school resilience to both heat and flooding?", options: ["Provide shade, conserve water and maintain drainage", "Remove trees and block drains", "Waste water and electricity", "Pave drains closed"], correct: 0 },
      { n: 49, diff: "hard", q: "Why should climate solutions consider food, energy and water together?", options: ["Actions in one system can affect the others", "The systems never interact", "Only energy matters", "Food requires no water"], correct: 0 },
      { n: 50, diff: "hard", q: "Which project best integrates science, mathematics and climate literacy?", options: ["Measure weather, graph results and interpret patterns", "Draw one sun without data", "Sing one song only", "Guess temperatures"], correct: 0 },
    ]
  },
  {
    slug: "sustainability", name: "Sustainability", icon: "♻️",
    color: "#7A7488", badge: "Sustainability Star", badgeIcon: "♻️",
    questions: [
      { n: 1, diff: "easy", q: "What are the three Rs of waste management?", options: ["Reduce, Reuse, Recycle", "Read, Run, Rest", "Rain, River, Road", "Rice, Roots, Rocks"], correct: 0 },
      { n: 2, diff: "easy", q: "What does reduce mean?", options: ["Use less and avoid unnecessary waste", "Use more", "Throw everything away", "Burn everything"], correct: 0 },
      { n: 3, diff: "easy", q: "What does reuse mean?", options: ["Use an item again safely", "Throw it away immediately", "Burn it", "Put it in water"], correct: 0 },
      { n: 4, diff: "easy", q: "What does recycle mean?", options: ["Process suitable used materials into new products", "Throw all waste in drains", "Burn all materials", "Leave waste on roads"], correct: 0 },
      { n: 5, diff: "easy", q: "Which is a renewable resource?", options: ["Sunlight", "Coal", "Petrol", "Diesel"], correct: 0 },
      { n: 6, diff: "easy", q: "Which action conserves water?", options: ["Fix leaks", "Leave taps running", "Waste stored water", "Flood paths"], correct: 0 },
      { n: 7, diff: "easy", q: "Which action conserves energy?", options: ["Switch off unused devices", "Leave devices on", "Run empty-room fans", "Waste electricity"], correct: 0 },
      { n: 8, diff: "easy", q: "Which material can be composted?", options: ["Vegetable peel", "Glass", "Metal can", "Plastic bag"], correct: 0 },
      { n: 9, diff: "easy", q: "Which action reduces food waste?", options: ["Take suitable portions", "Throw edible food away", "Waste lunch", "Leave food to spoil"], correct: 0 },
      { n: 10, diff: "easy", q: "Which item can replace repeated single-use bottles?", options: ["Reusable bottle", "Smoke", "Dust", "Sunlight"], correct: 0 },
      { n: 11, diff: "easy", q: "Which action protects biodiversity?", options: ["Protect habitats", "Destroy nests", "Pollute ponds", "Remove every plant"], correct: 0 },
      { n: 12, diff: "easy", q: "Which action protects soil?", options: ["Keep harmful waste away", "Pour oil on soil", "Scatter glass", "Dump plastic"], correct: 0 },
      { n: 13, diff: "easy", q: "Which action protects water?", options: ["Keep waste out of streams", "Throw rubbish in rivers", "Pour oil in drains", "Pollute wells"], correct: 0 },
      { n: 14, diff: "easy", q: "Which action can make a school greener?", options: ["Plant and care for trees", "Burn plastic", "Block drains", "Scatter litter"], correct: 0 },
      { n: 15, diff: "easy", q: "Who benefits when shared resources are protected?", options: ["The community", "Nobody", "Only one pupil", "Only visitors"], correct: 0 },
      { n: 16, diff: "easy", q: "Which transport option uses human energy?", options: ["Walking", "Car", "Motorcycle", "Bus"], correct: 0 },
      { n: 17, diff: "easy", q: "Which habit can save paper?", options: ["Use both sides when suitable", "Throw blank paper away", "Tear unused sheets", "Wet books"], correct: 0 },
      { n: 18, diff: "easy", q: "Which is responsible consumption?", options: ["Use what you need", "Buy or take more only to waste it", "Throw useful items away", "Waste food"], correct: 0 },
      { n: 19, diff: "easy", q: "What does conservation mean?", options: ["Protecting and wisely using resources", "Wasting resources", "Polluting rivers", "Destroying habitats"], correct: 0 },
      { n: 20, diff: "easy", q: "Sustainability considers the needs of whom?", options: ["Present and future generations", "Only people today", "Only adults", "Only one community member"], correct: 0 },
      { n: 21, diff: "medium", q: "Why are the three Rs important?", options: ["They can reduce waste and resource use", "They create more litter", "They pollute water", "They require wasting materials"], correct: 0 },
      { n: 22, diff: "medium", q: "Why is a reusable bottle often more sustainable?", options: ["It can replace many single-use bottles", "It must be thrown away daily", "It creates more waste by design", "It cannot hold water"], correct: 0 },
      { n: 23, diff: "medium", q: "How does composting support sustainability?", options: ["It returns suitable organic material to soil", "It creates plastic", "It wastes all nutrients", "It pollutes soil by definition"], correct: 0 },
      { n: 24, diff: "medium", q: "Why should school equipment be maintained?", options: ["Maintenance can extend useful life", "Breaking equipment saves resources", "Maintenance creates waste only", "Old equipment must always be discarded immediately"], correct: 0 },
      { n: 25, diff: "medium", q: "Which action supports sustainable food systems?", options: ["Reduce food waste and grow food responsibly", "Waste harvests", "Pollute farmland", "Use resources carelessly"], correct: 0 },
      { n: 26, diff: "medium", q: "How does rainwater harvesting support sustainability?", options: ["It can provide water for suitable uses", "It wastes rainfall", "It creates fossil fuels", "It stops the water cycle"], correct: 0 },
      { n: 27, diff: "medium", q: "Why can energy efficiency reduce environmental impacts?", options: ["Less energy may be needed for the same service", "Efficiency means using more energy", "Efficiency always increases pollution", "Efficient devices need no resources"], correct: 0 },
      { n: 28, diff: "medium", q: "Which action demonstrates responsible consumption?", options: ["Choose durable or reusable items when practical", "Use disposable items unnecessarily", "Waste materials", "Replace working items without reason"], correct: 0 },
      { n: 29, diff: "medium", q: "Why should natural resources be conserved?", options: ["They support people, economies and ecosystems", "They are never limited or damaged", "Only animals use them", "Conservation increases waste"], correct: 0 },
      { n: 30, diff: "medium", q: "Which school activity supports a circular approach?", options: ["Compost suitable garden waste and return it to soil", "Throw all garden waste away", "Burn plastic with leaves", "Dump scraps into drains"], correct: 0 },
      { n: 31, diff: "medium", q: "How can pupils help reduce electricity use?", options: ["Use daylight when suitable and switch off unused lights", "Turn on all lights in daylight", "Leave fans running", "Open fridge doors"], correct: 0 },
      { n: 32, diff: "medium", q: "How can pupils help reduce water use?", options: ["Report leaks and close taps", "Leave taps open", "Waste water during cleaning", "Ignore dripping taps"], correct: 0 },
      { n: 33, diff: "medium", q: "What is sustainable agriculture?", options: ["Producing food while caring for resources and ecosystems", "Growing food while wasting all water", "Farming without soil or water considerations", "Producing food by polluting rivers"], correct: 0 },
      { n: 34, diff: "medium", q: "Why is soil conservation important?", options: ["Healthy soil supports food production and ecosystems", "Soil has no role in food", "Erosion always improves farms", "Soil cannot be degraded"], correct: 0 },
      { n: 35, diff: "medium", q: "Which choice can reduce packaging waste?", options: ["Use reusable containers where practical", "Use extra single-use wrappers", "Throw containers away after each use", "Choose more packaging than needed"], correct: 0 },
      { n: 36, diff: "medium", q: "Why does reducing food waste save more than food?", options: ["Food production uses land, water and energy", "Food production uses no resources", "Only plates are saved", "Waste creates resources"], correct: 0 },
      { n: 37, diff: "medium", q: "Which action supports social sustainability at school?", options: ["Share and care for common resources fairly", "Take all shared materials", "Damage common property", "Waste supplies"], correct: 0 },
      { n: 38, diff: "medium", q: "What is an environmental footprint?", options: ["The effect activities have on the environment", "A footprint made only in mud", "A type of shoe", "A weather instrument"], correct: 0 },
      { n: 39, diff: "medium", q: "Which subject can help calculate waste reduction percentages later in school?", options: ["Mathematics", "Music only", "Drama only", "Handwriting only"], correct: 0 },
      { n: 40, diff: "medium", q: "Which statement best describes sustainability?", options: ["Meeting present needs while protecting future opportunities and resources", "Using resources as quickly as possible", "Ignoring environmental effects", "Producing maximum waste"], correct: 0 },
      { n: 41, diff: "hard", q: "A class used 50 plastic cups last week and 20 this week after introducing reusable cups. How many fewer plastic cups were used?", options: ["30", "70", "20", "25"], correct: 0 },
      { n: 42, diff: "hard", q: "A garden needs 30 litres of water, but careful watering reduces use by 8 litres. How many litres are used?", options: ["22 litres", "38 litres", "8 litres", "30 litres"], correct: 0 },
      { n: 43, diff: "hard", q: "Why is reducing waste usually preferred before recycling?", options: ["Avoiding waste can prevent resource use before recycling is needed", "Recycling always creates more waste", "Reduction means throwing items away", "Waste prevention has no benefit"], correct: 0 },
      { n: 44, diff: "hard", q: "Which plan best applies food-energy-water sustainability at school?", options: ["Reduce food waste, conserve water and use energy efficiently", "Waste food, water and electricity", "Burn rubbish and leave taps open", "Use more resources than needed"], correct: 0 },
      { n: 45, diff: "hard", q: "How does a school garden demonstrate sustainability?", options: ["It can connect food production, composting, water care and learning", "It teaches only littering", "It requires wasting water", "It has no connection to resources"], correct: 0 },
      { n: 46, diff: "hard", q: "Why should sustainability include fairness?", options: ["Resources and opportunities should be considered across people and generations", "Only one person should receive shared resources", "Future users do not matter", "Fairness always increases waste"], correct: 0 },
      { n: 47, diff: "hard", q: "A class collects 40 kg of recyclable material and 10 kg cannot be recycled. How many kilograms can be recycled?", options: ["30 kg", "50 kg", "10 kg", "4 kg"], correct: 0 },
      { n: 48, diff: "hard", q: "Which decision follows a circular-economy idea?", options: ["Repair, reuse and recover materials before disposal where possible", "Throw working items away", "Use once and discard everything", "Burn all reusable materials"], correct: 0 },
      { n: 49, diff: "hard", q: "Why should sustainability decisions consider environmental, social and economic effects?", options: ["A solution can affect people, nature and resources in different ways", "Only environmental effects matter", "Only money matters", "The three areas never interact"], correct: 0 },
      { n: 50, diff: "hard", q: "Which project best integrates science, mathematics and sustainability?", options: ["Measure school waste, classify it, calculate totals and design reduction actions", "Draw a bin without collecting data", "Sing about recycling only", "Guess waste amounts"], correct: 0 },
    ]
  },
]

export function p4CategoryBySlug(slug: string): QuizCategory | undefined {
  return P4_QUIZ.find((c) => c.slug === slug)
}
